jgm/pandoc

pandoc.cabal
src/Text/Pandoc/Readers/Haddock.hs
src/Text/Pandoc/Readers/LaTeX.hs
src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Readers/RST.hs
src/Text/Pandoc/Readers/TWiki.hs
src/Text/Pandoc/Templates.hs
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/EPUB.hs
src/Text/Pandoc/Writers/ICML.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/Markdown.hs
src/Text/Pandoc/Writers/OpenDocument.hs
src/Text/Pandoc/Writers/RST.hs
src/Text/Pandoc/Writers/Texinfo.hs

Compiles with ghc 7.10.1 RC1 and ghc 7.8.4.

Allow compilation with ghc 7.10.1 RC1 and haddock-library 1.2

---

src/Text/Pandoc/PDF.hs

Don't log "Try xelatex..." if xelatex already in use

---

src/Text/Pandoc/Writers/HTML.hs

Fixed issue #1131 + small refactoring

---

src/Text/Pandoc/Writers/LaTeX.hs

LaTeX Writer: Don't use listings in headers

---

README
pandoc.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/PDF.hs

A simple demonstration :sparkles:

Fix issue #969, #1779 by providing --latex-engine-opt

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Org reader: add support for smart punctuation

---

src/Text/Pandoc/MediaBag.hs
src/Text/Pandoc/Options.hs

See https://github.com/jgm/highlighting-kate/pull/64

Derive from Data and Typeable for libpandoc

---

src/Text/Pandoc/Readers/Docx/StyleMap.hs

I've messed up badly with it, so it didn't work properly in many cases. Really sorry about that...
At the plus side, fallback mechanic is working wonderfully -- that's primary reason why it wasn't noticed until now.
I hope this is merged ASAP, since [some users are already affected][1]
[1]:https://groups.google.com/forum/#!topic/pandoc-discuss/iRml5jufqXg

Docx Writer: Fix StyleMap

---

src/Text/Pandoc/Writers/Docx.hs

Docx Writer: Filter out illegal XML characters

---

src/Text/Pandoc/Writers/Docx.hs

Docx Writer: Copy hyphenation settings from reference.docx

---

README

Also, adds note on pandoc-citeproc --bib2json and pandoc-citeproc --bib2yaml, and sorts table

Adds YAML biblio format

---

src/Text/Pandoc/Writers/Docx.hs

As per request at b29a8a5516ea36f143e3cb8db44e22630e3adb6b.
This version interprets `toc-title` as inlines, since Word does as well.

Docx Writer: Take TOC title from toc-title metadata field

---

src/Text/Pandoc/Writers/Custom.hs

Closes #2101, #1634
Also factored out ByteString, since it's only used as an intermediate
representation.
Not entirely sure it's a great idea to rely on GHC internals, but I see no other option short of reimplementing `Scripting.Lua` to use `ByteString` so that it becomes encoding-agnostic.

Custom Writer: Set foreign encoding to UTF-8

---

README

Motivated by https://github.com/jgm/pandoc-citeproc/issues/124.

Update README on in-field markup in biblio databases

---

README

Coupled with recent updates, this should close #2041.

README: bibliography updates

---

CONTRIBUTING.md
COPYRIGHT
HCAR-Pandoc.tex
man/man1/pandoc.1.template
pandoc.cabal
pandoc.hs
tests/docx/links.native
tests/docx/links_writer.native
tests/mediawiki-reader.native
tests/mediawiki-reader.wiki
tests/twiki-reader.native
tests/twiki-reader.twiki
windows/pandoc.wxs

@jgm, here you have the new request.
BTW, could you check jgm/pandoc-templates#101?

replace old url with pandoc.org

---

README
man/pandoc.1

Cleaned-up version of #2314, with working regenerated man page.

List all styles in manual for --reference-docx

---

data/epub.css

There are five levels of nested emphasis.

added selectors for nested emphasis (epub.css)

---

src/Text/Pandoc/Writers/RST.hs
tests/Tests/Writers/RST.hs

Hopefully helps with #2394
A test included.

[RST Writer] Don't normalize heading levels below input minimum

---

README
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/LaTeX.hs

`lang` variable is now in BCP47 format

---

README
src/Text/Pandoc/Writers/LaTeX.hs

closes #2437
depends on https://github.com/jgm/pandoc-templates/pull/129

Change variable to polyglossia-lang.name and .options

---

README

Accounts for changes in https://github.com/jgm/pandoc-templates/pull/141.

Update LaTeX/ConTeXt variable usage in README.

---

src/Text/Pandoc/Highlighting.hs

I think this will need changes to https://github.com/jgm/highlighting-kate.

Add highlighting support to GAP

---

COPYRIGHT

Update license year range to 2016

---

CONTRIBUTING.md

On my end, in a clean sandbox, I had to run this before I could run the tests, I'm a cabal / haskell noob so that might not be the best way to do so but :)

CONTRIBUTING.md : update test enabling documentation

---

README
man/pandoc.1

Very Minor update on the documentation

---

src/Text/Pandoc/Writers/Docx.hs

Docx Writer: handle image alt text

---

pandoc.cabal

include .tei files in pandoc.cabal

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Here's my attempt at fixing #2862 (I'm pretty new at Haskell, so let me know if there's a better way...)

Ignore leading space in org code blocks

---

appveyor.yml
windows/stack-appveyor.yaml

As discussed in https://github.com/jgm/pandoc/issues/2903#issuecomment-218214394
Example builds in https://ci.appveyor.com/project/JanSchulz/pandoc

Add appveyor artefacts for pandoc.exe

---

src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
src/Text/Pandoc/Writers/Org.hs
tests/Tests/Readers/Org.hs
tests/writer.org

Improve support for Org drawers.
This supersedes and hence closes #1984.

Org drawer improvements

---

src/Text/Pandoc.hs

Errors are encountered while reading, not writing

fix example in documentation

---

src/Text/Pandoc/Writers/LaTeX.hs

Latex doesn't like when hypertargets are put in the
options list of the section. They are not lost since
they were actually duplicated and present also in
the argument list.

[tex] No invalid inlines in sections' options

---

MANUAL.txt

Added to nocite section to add the wildcard functionality.

Add '@*' usage

---

INSTALL.md

Fixed typo in INSTALL docs

---

MANUAL.txt

Manual: Mention limitations of Literate Haskell Support

---

MANUAL.txt

alternative to https://github.com/jgm/pandoc/pull/3468

MANUAL.txt explain --webtex SVG url

---

src/Text/Pandoc/Writers/ODT.hs
src/Text/Pandoc/Writers/OpenDocument.hs

ODT writer: calculate aspect ratio for percentage-sized images

---

src/Text/Pandoc/Writers/Docx.hs

see https://github.com/jgm/pandoc/issues/1667

docx writer: lang meta, see #1667

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3530.md
test/command/sub-file-chapter-1.tex
test/command/sub-file-chapter-2.tex

Add support for LaTeX subfiles package

---

src/Text/Pandoc/Writers/Muse.hs
test/Tests/Writers/Muse.hs
test/tables.muse

It is required to trigger Muse table rendering.

Muse writer: Indent tables with one space

---

data/docx/word/styles.xml
src/Text/Pandoc/Writers/Docx.hs

Change FigureWithCaption to CaptionedFigure

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3681.md

Add LaTeX xspace support

---

src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs

Test checks that behavior is consistent with Amusewiki

Muse reader: avoid crashes on multiparagraph inline tags

---

doc/lua-filters.md
src/Text/Pandoc/App.hs
src/Text/Pandoc/Class.hs
src/Text/Pandoc/Lua.hs
src/Text/Pandoc/Lua/PandocModule.hs
test/Tests/Lua.hs

A lua module enabling users to interact with the MediaBag is added.

Lua mediabag module

---

.editorconfig
CONTRIBUTING.md
COPYRIGHT
MANUAL.txt
Setup.hs
benchmark/benchmark-pandoc.hs
doc/filters.md
doc/using-the-pandoc-api.md
linux/control.in
man/pandoc.1
pandoc.cabal
pandoc.hs
src/Text/Pandoc/Lua/Util.hs
src/Text/Pandoc/Readers/CommonMark.hs
src/Text/Pandoc/Writers/CommonMark.hs

Proofreading *.md files (i.e. excluding `MANUAL.txt` for now). The commit messages should be self-explanatory. They mainly are:
- add relevant links
- proofread on grammar, syntax, etc.
- consistency
Feel free to squash this into 1 commit. I want them to be more atomic in case you want to cherry-pick.

Proofread on *.md

---

MANUAL.txt

This takes the changes in #1592 into account.

Revise documentation of small caps syntax in manual.

---

INSTALL.md

MacOS instructions needed xar -f

---

src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Options.hs

Change Generic JSON instances to TemplateHaskell

---

src/Text/Pandoc/App.hs

fix --help output for --highlight-style to include FILE

---

MANUAL.txt
data/templates/default.context
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Pretty.hs
src/Text/Pandoc/Writers/ConTeXt.hs
test/Tests/Writers/ConTeXt.hs
test/tables.context
test/writer.context
test/writers-lang-and-dir.context

Fixes #2102.
This is a work in progress.  Because until about 5 minutes ago I had never written a single line of Haskell, I have no idea how to do even basic things, like passing a value to a function.  More changes will follow once I figure out how things work.  Linting from Haskell professionals is more than welcome!

ConTeXt writer: Use xtables instead of Tables

---

src/Text/Pandoc/Writers/RST.hs
test/Tests/Writers/RST.hs

Here it is, as you asked. `fixBlocks` here can easily become parametric if desired

in RST writer insert comment between lists and quotes, closes #4248

---

MANUAL.txt
src/Text/Pandoc/PDF.hs

Add the ability to use the header and footer parameters in wkhtmltopd.

Add header and footer parameters for wkhtmltopdf

---

CONTRIBUTING.md

See https://groups.google.com/forum/#!msg/pandoc-discuss/mrFsj5RzNFA/Pnd3zubWBwAJ;context-place=searchin/pandoc-discuss/%22good$20first$20issue%22%7Csort:date

CONTRIBUTING.md: label was renamed.

---

pandoc.cabal

Tests pass with the new test tool.

Allow tasty-quickcheck 0.10

---

src/Text/Pandoc/Writers/DokuWiki.hs
test/dokuwiki_multiblock_table.dokuwiki
test/dokuwiki_multiblock_table.native

Dokuwiki writer: fix LineBreaks in Tables

---

src/Text/Pandoc/PDF.hs

fixes #4413
Tested on macOS with `--pdf-engine weasyprint` and `--pdf-engine wkhtmltopdf`. Should work fine on Windows and with `--pdf-engine prince` but untested.

html2pdf: inject base tag wih current working directory

---

src/Text/Pandoc/Writers/EPUB.hs

EPUB writer: remove notes from TOC in nav.xhtml

---

MANUAL.txt

Otherwise I got:
[WARNING] Could not parse YAML metadata at line 4 column 3: found character that cannot start any token

MANUAL.txt fix raw content example

---

MANUAL.txt

Motivated by https://groups.google.com/forum/#!topic/pandoc-discuss/tqMp0UKPpZQ

MANUAL: clarify template vs metadata variables

---

src/Text/Pandoc/Readers/DocBook.hs

`informalequation` can appear at the top level, in which case it is converted
into a standalone paragraph.
This is an example of some docbook Latex math:
It's duplicated between a `alt` and `mathphrase` tags.
```
<informalequation>
<alt><![CDATA[m = \max\left( \left| { {\partial z_f} \over {\partial x_f} } \right|,
\left| { {\partial z_f} \over {\partial y_f} } \right|
\right).]]></alt>
<mathphrase><![CDATA[m = \max\left( \left| { {\partial z_f} \over {\partial x_f} } \right|,
\left| { {\partial z_f} \over {\partial y_f} } \right|
\right).]]></mathphrase>
</informalequation>
```

DocBook Reader: Read Latex math as output by asciidoctor

---

pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Readers/FB2.hs
test/Tests/Readers/FB2.hs
test/fb2/reader/emphasis.fb2
test/fb2/reader/emphasis.native
test/fb2/reader/epigraph.fb2
test/fb2/reader/epigraph.native
test/fb2/reader/meta.fb2
test/fb2/reader/meta.native
test/fb2/reader/poem.fb2
test/fb2/reader/poem.native
test/fb2/reader/titles.fb2
test/fb2/reader/titles.native
test/test-pandoc.hs

Not ready, PR is just to make sure nobody else starts from scratch

Add FB2 reader

---

src/Text/Pandoc/PDF.hs

see https://github.com/jgm/pandoc/issues/4413

Revert piping html to pdf-engine

---

MANUAL.txt

MANUAL: clarify pipe table width calculation

---

pandoc.cabal

All tests pass with tasty 1.1.0.1 here.

Allow tasty 1.1

---

src/Text/Pandoc/Writers/LaTeX.hs
test/command/1710.md
test/command/4016.md
test/command/4690.md

beamer output: fix single digit column percentage

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/2118.md
test/command/refs.md

LaTeX Reader: parse figure label into Image id

---

MANUAL.txt

MANUAL.txt add proxy description

---

MANUAL.txt

via https://groups.google.com/forum/#!topic/pandoc-discuss/7KizETE9iqE

MANUAL: clarify EPUB linked media

---

src/Text/Pandoc/Writers/AsciiDoc.hs
test/command/4545.md

AsciiDoc Writer: escape square brackets at start of line

---

MANUAL.txt

Updating documentation for change from a while back.

Adding beamer info for slide backgrounds

---

src/Text/Pandoc/App.hs

Better error message on `-t pdf -o out.pdf`

---

CONTRIBUTING.md

This is a minor documentation fix.

Fix mistake in REPL instructions for stack.

---

MANUAL.txt

Documents https://github.com/jgm/pandoc/commit/7318bc91ce58bb6c39e556e334f278e590439c3f.

MANUAL.txt epub:type attribute

---

MANUAL.txt
src/Text/Pandoc/Writers/CommonMark.hs
src/Text/Pandoc/Writers/Markdown.hs
src/Text/Pandoc/Writers/Shared.hs
test/command/4528.md

CommonMark writer: don't emit HTML for small caps without raw_html

---

doc/customizing-pandoc.md
doc/filters.md

Add docs about customizing pandoc

---

src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/Meta.hs

Implement changes previously suggested by jgm and tarleb.

Org reader: clean up

---

MANUAL.txt

see e.g. https://github.com/jgm/pandoc/issues/5017

MANUAL: clarify LaTeX image dimensions output

---

INSTALL.md

will work with https://github.com/jgm/pandoc-website/pull/30

WIP: INSTALL.md change button

---

MANUAL.txt

Add small clarification re $sep$ made by jgm on the mailing list.

Clarify that $sep$ must come right before $endfor$.

---

changelog

Updates for my most recent pull requests; I am not aware of any further changes needed.

Update changelog for LaTeX template

---

MANUAL.txt

Add additional headings to categorize variables, and alphabetize when there is large number; add more examples.

Manual: Reorganize template variables

---

src/Text/Pandoc/Readers/Markdown.hs

Make --metadata-file use pandoc-markdown

---

MANUAL.txt
data/templates/default.latex

Added support for the `subject` metadata variable to PDF.

---

src/Text/Pandoc/Writers/JATS.hs
test/writer.jats

JATS writer: wrap figure caption in <p> to fix validation

---

data/translations/de.yaml
data/translations/en.yaml
data/translations/ru.yaml
data/translations/uk.yaml
src/Text/Pandoc/Translations.hs

Translations: reorder alphabetically

---

src/Text/Pandoc/Readers/DokuWiki.hs
test/command/5416.md

Dokuwiki Reader fix: parse single curly brace

---

data/templates/default.xwiki
pandoc.cabal
src/Text/Pandoc/Writers.hs
src/Text/Pandoc/Writers/MediaWiki.hs
src/Text/Pandoc/Writers/XWiki.hs
test/writer.xwiki

This is very rudimentary for now. Based on DocuWiki/MediaWiki, but with less
support for special formatting because it's unclear what additional support
XWiki has for this.

Issue #1800 Add XWiki Support

---

doc/lua-filters.md

Recently this has been the version of this lua filter I have been using for blogging.  There are three changes:
1. It only processes elements which begin with `\begin{tikzpicture}`
2. It uses pdf2svg instead of imagemagick to preserve fidelity
3. The images produced have transparent backgrounds

Improved lua tikz filter

---

src/Text/Pandoc/Readers/FB2.hs
test/Tests/Readers/FB2.hs
test/fb2/reader/notes.fb2
test/fb2/reader/notes.native

FB2 reader: parse notes

---

pandoc.cabal
test/tables.xwiki

seems like this was forgotten in 40b60a911c222a00407726d5ce606abbafcea29c?

add test/tables.xwiki to git and pandoc.cabal

---

data/templates/default.latex

Fix using Beamer with geometry

---

data/templates/default.jira
pandoc.cabal
src/Text/Pandoc/Writers.hs
src/Text/Pandoc/Writers/Jira.hs
test/Tests/Old.hs
test/tables.jira
test/writer.jira

This adds support for Atlassian's jira markup.
Closes: #2497

Add jira writer

---

data/pandoc.lua
doc/lua-filters.md
src/Text/Pandoc/Lua/Marshaling/AST.hs
src/Text/Pandoc/Lua/Module/Types.hs
test/lua/module/pandoc.lua

Lua: add a `clone()` method to all AST elements

---

src/Text/Pandoc/Writers/JATS.hs

see https://github.com/jgm/pandoc/issues/5570#issuecomment-502861382
introduced by e87b54dcad5e37133bc0f4cfc8039e9fd0dd1b4e

JATS Writer: do not emit empty <fn-group>

---

src/Text/Pandoc/Lua/Filter.hs
src/Text/Pandoc/Lua/Module/Pandoc.hs
src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Readers/Ipynb.hs
src/Text/Pandoc/Readers/LaTeX.hs
src/Text/Pandoc/Readers/Man.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/TikiWiki.hs
src/Text/Pandoc/Writers/Shared.hs
test/Tests/Lua.hs

Removes compiler warnings about redundant constraints (-Wredundant-constraints).

Fix redundant constraint warnings.

---

data/templates/default.jats

JATS template: add abstract

---

src/Text/Pandoc/Writers/HTML.hs
test/command/5655.md

HTML writer: render inline formulas correctly

---

MANUAL.txt

MANUAL: link to YAML spec

---

src/Text/Pandoc/Writers/Docx.hs

Relates to https://github.com/jgm/pandoc/issues/1209#issuecomment-523961452

add proofState to settingsList

---

src/Text/Pandoc/Readers/DocBook.hs

Fixes #1234.
This parses admonitions not as a blockquote, but rather as a div with an
appropriate class. We also handle titles for admonitions as a nested div
with the "title" class.
(I followed the behaviour of other docbook-to-html converters in this -
there are clearly other ways you could encode it.)
In general, the handling of elements with nested title elements is very
inconsistent. I think we should make it consistent, but I'm leaivng that
for later to make this a small change.
Example:
```docbook
<warning xml:id="someId">
<title>My title</title>
<simpara>An admonition block</simpara>
</warning>
```
goes to
```html
<div id="someId" class="warning">
<div class="title">My title</div>
<p>An admonition block</p>
</div>
```

docbook: richer parse for admonitions

---

INSTALL.md

No real website to package, added simply official webpage as href

Add Void Linux

---

src/Text/Pandoc/Shared.hs
test/command/5797.md

It is a bit hard to believe that this is all it takes and since this is my first PR on any meaningful project I'm still somewhat skeptical :thinking: but the tests pass and manual testing in the shell also seemed fine. Thanks to the groundwork from #5796 
I don't quite understand the meaning of the numbered `*.md` files for command and couldn't find any info on whether they're generated based on some source. Anyway, let me know if anything's wrong :pray: and thanks for tagging with good first issue and for `pandoc` in general <3

Add support for <mark>

---

MANUAL.txt

Remove grffile requirement in MANUAL.txt

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Readers/Jira.hs
stack.yaml
test/Tests/Old.hs
test/Tests/Readers/Jira.hs
test/jira-reader.jira
test/jira-reader.native
test/test-pandoc.hs

Add jira reader

---

src/Text/Pandoc/MIME.hs

Added glsl mime type for WebGL maps

Added glsl mime type for WebGL maps

---

src/Text/Pandoc/Writers/Docx.hs

Starting in 2.8, the docx writer no longer distinguishes
between tight and loose lists, since the Compact style is
omitted.
This is a side-effect of the fix to #5670, as explained
in the changelog:
+ Preserve built-in styles in DOCX with custom style (Ben Steinberg,
#5670).  This change prevents custom styles on divs and spans
from overriding styles on certain elements inside them, like
headings, blockquotes, and links. On those elements, the
"native" style is required for the element to display correctly.
This change also allows nesting of custom styles; in order to do so,
it removes the default "Compact" style applied to Plain blocks,
except when inside a table.
This patch fixes the problem by extending the exception currently
offered to Plain blocks inside tables to Plain blocks inside …

Docx writer: fix regression with Compact style on tight lists (fixes #6072)

---

MANUAL.txt

I've changed _all_ `http:` URLs of which the respective web servers have properly configured HTTPS to their `https` equivalents.
Plus a bunch of URLs have simply been updated.

Update URLs and use HTTP**S** wherever possible

---

src/Text/Pandoc/Readers/Odt/Generic/Utils.hs
src/Text/Pandoc/Readers/Odt/Generic/XMLConverter.hs

Data.Bool already provides a bool function identical to this one.

Remove our bool function

---

src/Text/Pandoc/App.hs
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/BCP47.hs
src/Text/Pandoc/CSV.hs
src/Text/Pandoc/Class.hs
src/Text/Pandoc/ImageSize.hs
src/Text/Pandoc/MIME.hs
src/Text/Pandoc/Writers.hs

This is basically all stuff that slips completely under hlint's radar.

More in-depth refactoring and cleanup

---

trypandoc/index.html

* Use "strict mode" for javascript code
* Fetch resources over https
Otherwise it will depend on the protocol of the webpage served which is a bad idea.
* Remove unnecessary attributes
Those attributes are not required in HTML5.

Improvements to trypandoc

---

trypandoc/index.html
trypandoc/trypandoc.hs

I think it is really useful to generate the full document instead of just a fragment.
screenshot: ![screen](https://user-images.githubusercontent.com/9395168/76772730-5aad6300-67dc-11ea-97cd-3daeef8d4755.png)

trypandoc: Add checkbox for standalone option

---

trypandoc/index.html

* trypandoc: Add standalone option to the command text
I somehow missed it in PR #6189.
* trypandoc: Update 3rd party libraries
Those links are taken as-is from the library website.

trypandoc: Add standalone option to the command text

---

src/Text/Pandoc/Readers/HTML.hs
test/command/1592.md

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdo
Closes: #5794

HTML reader: support <bdo>

---

INSTALL.md

from https://yihui.name/tinytex to https://yihui.org/tinytex (the former will be automatically redirected to the latter)

Update the link to TinyTeX

---

MANUAL.txt
src/Text/Pandoc/Writers/LaTeX.hs
test/command/4805-beamer-columns-alignment.md

Add support for customizable alignment of columns in beamer (issues #4805 and #4150).

LaTeX Writer: Add support for customizable alignment of columns in beamer

---

data/templates/styles.html
src/Text/Pandoc/Writers/HTML.hs
test/command/5655.md
test/lhs-test.html
test/lhs-test.html+lhs
test/s5-basic.html
test/s5-inserts.html
test/writer.html4
test/writer.html5

Use CSS in favor of <br> for display math

---

data/templates/default.revealjs

cf.
- https://github.com/hakimel/reveal.js/releases/tag/4.0.0
- https://revealjs.com/upgrading/
see also https://github.com/jgm/pandoc-templates/pull/13

update template for reveal.js 4.0.0

---

pandoc.cabal

Builds fine and all tests pass here.

Allow aeson 1.5

---

data/templates/default.latex

Make polyglossia package options list-aware in the LaTeX template.

---

src/Text/Pandoc/Readers/JATS.hs
test/Tests/Readers/JATS.hs

JATS reader: parse abstract element into metadata field of same name

---

benchmark/benchmark-pandoc.hs

This is a quick hack to enable benchmarking on ByteString readers (e.g. docx). Not the safest code, due to sum-records, but I trust it's not that big of an issue in relatively short benchmark code.

[Bench] Benchmark bytestring readers

---

data/epub.css

epub.css: Fix cover page selectors and add note explaining their use.

---

src/Text/Pandoc/Writers/ICML.hs
test/command/5541-urlLink.md
test/command/6675.md
test/writer.icml

Changed default link state to invisible

---

src/Text/Pandoc/Readers/DocBook.hs

Support for bibliomisc and anchors which are used to link into
bibliomisc. Also refactor the bibliography into a bulletin list
(each under a bibliodiv if present). This is more consistent with
other DocBook behavior than just using paragraphs for each entry.

DocBook reader: bibliomisc and anchor support

---

src/Text/Pandoc/Readers/DocBook.hs
test/command/docbook-bibliography.md

Also add unit test to ensure the behavior stays consistent.

DocBook Reader: fix duplicate bibliography bug

---

MANUAL.txt
data/templates/styles.html
test/lhs-test.html
test/lhs-test.html+lhs
test/writer.html4
test/writer.html5

follow-up to https://github.com/jgm/pandoc/pull/6601
motivated by https://groups.google.com/g/pandoc-discuss/c/1oCCbois1G4

Updates to default CSS

---

data/templates/default.org
src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Writers/Org.hs
test/Tests/Readers/Org/Block.hs
test/Tests/Readers/Org/Block/CodeBlock.hs
test/Tests/Readers/Org/Block/Figure.hs
test/Tests/Readers/Org/Block/Header.hs
test/Tests/Readers/Org/Block/Table.hs
test/Tests/Readers/Org/Inline.hs
test/Tests/Readers/Org/Meta.hs
test/command/3706.md
test/command/4186.md
test/command/5178.md
test/org-select-tags.org
test/tables.org
test/writer.org

See commit messages for details, these commits enact the following changes:
- update the list of languages supported by org
- change keywords to be lower case

Update org supported languages and keyword case

---

data/templates/affiliations.jats
data/templates/article.jats_publishing
data/templates/default.jats_articleauthoring
doc/jats.md

JATS writer: support author affiliations

---

CONTRIBUTING.md

Also adds a paragraph aimed at highlighting the importance of feature
maintenance.

CONTRIBUTING: add section "How can I help?"

---

src/Text/Pandoc/Writers/ICML.hs
test/command/5541-nesting.md
test/command/svg.md
test/writer.icml

ICML writer: fix image bounding box for custom widths/heights

---

doc/filters.md

Assigned .pl file extension to perl interpreter and .rb to ruby

Fixed table with file extensions and interpreters

---

data/templates/default.latex
pandoc.cabal
src/Text/Pandoc/Writers/AnnotatedTable.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/LaTeX/Table.hs
src/Text/Pandoc/Writers/LaTeX/Types.hs
test/Tests/Old.hs
test/tables/nordics.latex
test/tables/planets.latex
test/tables/students.latex

LaTeX writer: support colspans and rowspans in tables.

---

src/Text/Pandoc/Readers/DocBook.hs

Add support for informalfigure.

DocBook reader: Support informalfigure

---

data/templates/default.revealjs

Illegal, turn into HTML comment

Remove JS comment from HTML

---

data/templates/default.context
data/templates/default.latex

See https://groups.google.com/g/pandoc-discuss/c/xqqWWleVO3s

list of figures before list of tables in LaTeX and ConTeXt templates

---

data/templates/default.revealjs

Support toc-title in revealjs

---

INSTALL.md

INSTALL: add note that parallel installations should be avoided.

---

data/templates/default.dzslides
data/templates/default.revealjs
data/templates/default.s5
data/templates/default.slideous
data/templates/default.slidy

This pull request adds support for the institute variable to all the HTML slide show templates.
In each case I have placed the institute after the author, and using the same HTML class (p, H3, span).
The formats are:
* revealjs
* s5
* dzslides
* slidy
* slideous

add support for institute

---

data/templates/styles.html
test/lhs-test.html
test/lhs-test.html+lhs
test/writer.html4
test/writer.html5

document-css: reset overflow-wrap on code blocks

---

src/Text/Pandoc/Lua/Init.hs

Prevent issues if Lua is misconfigured on the system.

Lua: fix global module loading

---

doc/lua-filters.md
pandoc.cabal
src/Text/Pandoc/Lua/Marshal/Reference.hs
src/Text/Pandoc/Lua/Module/Utils.hs

List with all cited references of a document.
Closes: #7752

Lua: add function `pandoc.utils.references`

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/Class/PandocMonad.hs
src/Text/Pandoc/Error.hs
test/command/5876.md
test/command/5876.yaml
test/command/5876/metadata/5876.yaml
test/command/5876/metadata/command/5876.yaml

If files specified with --metadata-file are not found in the working
directory, look in $DATADIR/metadata.
Closes #5876.

Search for metadata files in $DATADIR/metadata

---

pandoc.cabal
src/Text/Pandoc/Class/PandocMonad.hs
test/command/7861.md

If a file path does not exist relative to the working directory, but
it does exist relative to the user data directory, and it exists outside
of the user data directory, do not read it. This applies to readDataFile
and readMetadataFile in PandocMonad and, by extension, any module that
uses these by passing them relative paths.
Fix bug in makeCanonical where consecutive ".."s was removed.

Don't read files outside of user data directory

---

src/Text/Pandoc/App/OutputSettings.hs

PDF: allow custom writer as format if engine is explicitly specified

---

INSTALL.md

I found out that pandoc can be installed via winget

add reference to install via winget

---

src/Text/Pandoc/Writers/Docx.hs

Docx writer: add bookmark-marker for table

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Set permissions for GitHub actions

---

src/Text/Pandoc/Readers/Org/Blocks.hs
test/command/6466-beg.hs
test/command/6466-end.hs
test/command/6466-mid.hs
test/command/6466-whole.hs
test/command/6466.md

Org reader: support line selection in INCLUDE directives

---

MANUAL.txt

Following on discussion in the group.

Add section for highlighting markup

---

changelog.md

Small and less important fix of the changelog.

fix a link to an issue in the changelog

---

MANUAL.txt

Changed the "nested" to "not nested" to make it clear it wouldn't get nested.

Made example for blank_before_blockquote clearer

---

pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Pandoc.hs
pandoc-lua-engine/test/lua/module/pandoc.lua
pandoc-server/src/Text/Pandoc/Server.hs
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/App/OutputSettings.hs
src/Text/Pandoc/Error.hs
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Format.hs
src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Writers.hs

The module provides functions and types for format spec parsing.

Add new module "Text.Pandoc.Format"

---

doc/lua-filters.md
pandoc-lua-engine/src/Text/Pandoc/Lua/Marshal/Context.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Template.hs
pandoc-lua-engine/test/lua/module/pandoc-template.lua

The new function applies a context, containing variable assignments, to a template.

Lua: add function `pandoc.template.apply`

---

doc/lua-filters.md
pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Init.hs
stack.yaml

Allows to handle docx and epub files.

Lua: add new module `pandoc.zip`

---

pandoc-lua-engine/src/Text/Pandoc/Lua/Marshal/Format.hs
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Format.hs

T.P.Extensions [API change]:
+ Add CustomExtension constructor to Extension.
+ Remove Bounded, Enum instances for Extension.
+ Add `extensionsToList` function.
+ Revise `readExtension` so it can handle CustomExtension.
T.P.Format:
+ Revise error checking to handle CustomExtension.

Add custom extensions.

---

MANUAL.txt

Fix epub-embed-font documentation

---

doc/lua-filters.md

Fix a tiny typo in lua-filters.md

---

doc/lua-filters.md
pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Init.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/CLI.hs

Allow processing of CLI options in Lua.

Lua: add pandoc.cli module

---

src/Text/Pandoc/Templates.hs

Added more information on the wrappers from the commit https://github.com/renjianxiongqi/pandoc/commit/f36b5b8a5db8479bcf98827c267840304403bdf0
closes #8489

added Wrapper type documentation to Text.Pandoc.Templates

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-xref.docbook
test/docbook-xref.native

This also adds a test xref to book and part. See also 4ea0508e6 / #8712.

DocBook reader: handle "book" for xref references

---

src/Text/Pandoc/Writers/HTML.hs
test/command/tasklist.md

HTML writer: use first paragraph in task item as checkbox label.

---

data/templates/styles.html
test/lhs-test.html
test/lhs-test.html+lhs
test/s5-basic.html
test/s5-fancy.html
test/s5-inserts.html
test/writer.html4
test/writer.html5

styles.html: fix task-list styling in reveal.js

---

MANUAL.txt

MANUAL: add commonmark fenced_div note

---

doc/extras.md

add to "Academic publishing workflows"

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/8745.md

LaTeX reader: support alt text on images.

---

src/Text/Pandoc/Writers/AsciiDoc.hs
test/writer.asciidoc
test/writer.asciidoctor

update line-through for asciidoc writer to custom inline style

---

src/Text/Pandoc/Readers/JATS.hs

Add new getPermissions function, in the style of other metadata functions

Add support for <permissions> metadata

---

changelog.md

english spelling typos

---

flake.nix

Fixes https://github.com/jgm/pandoc/issues/9083

update flake.nix with specific crypton-connection version

---

MANUAL.txt
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Readers/CommonMark.hs

Support new GFM math constructions

---

changelog.md

Fix changelog.md typo: 2023->2024

---

INSTALL.md

Respect NixOS name capitalization and add OpenBSD.
Thanks <3

INSTALL.md: Minor tweaks.

---

pandoc-server/src/Text/Pandoc/Server.hs
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/App/Input.hs
src/Text/Pandoc/Readers/DocBook.hs
src/Text/Pandoc/Shared.hs
src/Text/Pandoc/Transforms.hs

Bundles all document transformations, i.e., functions that run predefined filters on Pandoc documents.

Collect transforms in new module T.P.Transforms. [API change]

---

pandoc-lua-engine/src/Text/Pandoc/Lua/Module.hs

The modules `lpeg` and `re` are now treated as if they had been loaded with `require`. Previously the modules were only assigned to global values, but could be loaded again via `require`, thereby allowing to use a system-wide installation. However, this proved to be too confusing.
The old behavior can be restored by adding the following lines to the top of Lua scripts, or to the `init.lua` in the data dir.
debug.registry()['_LOADED'].lpeg = nil
debug.registry()['_LOADED'].re = nil

Lua: keep `lpeg` and `re` as "loaded" modules.

---

data/translations/ua.yaml

Adding translations for Ukrainian, i.e. file data/translations/ua.yaml

add ua.yaml

---

MANUAL.txt

when CJKmainfont is used with lualatex
C.f. #3873

Document the use of luatexja

---

data/odt/styles.xml

Add TableCaption to styles.xml

---

changelog.md

Fix formatting issue in changelog to make sub-item be listed as such.

Fix formatting issue in changelog

---

MANUAL.txt
data/templates/default.beamer

I added variables for lists of options to be given to all types of beamer theme.

Beamer theme options

---

MANUAL.txt
data/templates/default.beamer

A list of images can be given to titlegraphic.
Options are applied to each image.

Support a list of images for titlegraphic

---

MANUAL.txt
data/templates/default.beamer

I added variables for short forms of the:
* title
* subtitle
* author
* institute
* date

Support short forms in Beamer

---

src/Text/Pandoc/Readers/RST.hs
test/command/10318.md

RST reader: implement option lists.

---

data/translations/ua.yaml

Fix a typo from
See.: див.
to
See: див.

Fix typo in ua.yaml

---

src/Text/Pandoc/Shared.hs
test/command/5793.md

Handle <abbr> as a span-like inline

---

data/docx/word/styles.xml

Base Author and Date styles on Title; remove condensed spacing.

Docx title style corrections

---

src/Text/Pandoc/Writers/Docx.hs

This fixes a regression introduced by af57648.
We are now preserving the ids from the reference doc's document.xml.refs, so we shouldn't renumber them or references introduced by the user (e.g. in a template) will fail.
Closes #10769.

Docx writer: don't renumber rels (fixes #10769).

---

data/templates/styles.html
test/s5-basic.html
test/s5-fancy.html
test/s5-inserts.html
test/writer.html4
test/writer.html5

HTML styles: prefix default styles with informative CSS comment

---

doc/lua-filters.md

See #10995. Use the `Pandoc:walk` method instead.

docs: Don't encourage returning tables of filters from Lua filters

---

COPYING.md

See https://mirror.team-cymru.com/gnu/Licenses/gpl-2.0.txt

Update FSF address
