src/Text/Pandoc/Writers/DokuWiki.hs
src/Text/Pandoc/Writers/HTML.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/MediaWiki.hs
src/Text/Pandoc/Writers/OpenDocument.hs
src/Text/Pandoc/Writers/Texinfo.hs
tests/dokuwiki_inline_formatting.dokuwiki
tests/writer.dokuwiki
tests/writer.html
tests/writer.latex
tests/writer.mediawiki
tests/writer.opendocument
tests/writer.texinfo

This change improves output formatting of content with a large amount of force line breaks, such as line-blocks. The following writers are affected:
* Dokuwiki
* HTML
* EPUB (via HTML)
* LaTeX
* MediaWiki
* OpenDocument
* Texinfo
This commit resolves #1924

Append newline to the LineBreak of various writers

---

src/Text/Pandoc/Writers/Texinfo.hs
tests/writer.texinfo

The Texinfo writer currently uses Pandoc.Pretty Doc combinator to format output, but converts a `Space` to `sp` literals instead of calling the `space` constructor which inserts a breakable space. I'm assuming this is not intended. Because of this, Texinfo writer output currently does not wrap properly.
Discovered while preparing pull request jgm/pandoc#1925

Texinfo writer: fix wrapping by using breakable spaces

---

src/Text/Pandoc/Writers/MediaWiki.hs
tests/writer.mediawiki

The preferred syntax for Images and other media is [[File:Foo.jpg]] in MediaWiki since v1.14 (6 years).  [[Image:Foo.jpg]] is deprecated but still works as an alias to the File namespace.  I don't think this would break any existing wikis since talk of switching the syntax/namespace for images started back in 2002 (https://phabricator.wikimedia.org/T2044).  NS_FILE became the new namespace for Files in v 1.14 in late 2008; released Feb 2009. (https://www.mediawiki.org/wiki/Release_notes/1.14)  There is still a namespace alias so '[[Image:]]' still works today.  It's just that MediaWiki supports other media as well, and so the name and syntax used in documentation (see https://www.mediawiki.org/wiki/Help:Images) has long been '[[File:foo.jpg]]'
This updates both the writer, and the test. …

update syntax for Images/Media files in MediaWiki

---

pandoc.hs

There have been several recent emails on pandoc-discuss from people thinking that Pandoc reads and writes generic JSON. [One of them mentioned the help message in particular as confusing](https://groups.google.com/d/msg/pandoc-discuss/9rRTNcaf0ko/Xbawkldkw4kJ). This commit updates the `--help` message with a note that only Pandoc's JSON version of native AST works as input or output, bringing it into closer alignment with the README and man pages.

Clarify JSON input and output in usage message

---

src/Text/Pandoc/Readers/LaTeX.hs
tests/Tests/Readers/LaTeX.hs

This enables pandoc to parse `tabular` environments with optional arguments and non-empty column separators (which should be fairly common in real world LaTeX documents).
Basic test cases for simple tables are also included, modeled roughly after the test cases for the Org reader.

LaTeX reader: minor table parsing improvements

---

README
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Writers/Markdown.hs
tests/Tests/Writers/Markdown.hs

Issue #1977
Most markdown processors support the [shortcut format] for reference links.
Pandoc's markdown reader parsed this shortcuts unoptionally.
Pandoc's markdown writer (with --reference-links option) never shortcutted links.
This commit adds an extension `shortcut_reference_links`. The extension is
enabled by default for those markdown flavors that support reading shortcut
reference links, namely:
- pandoc
- strict pandoc
- github flavoured
- PHPmarkdown
If extension is enabled, reader parses the shortcuts in the same way as
it preveously did. Otherwise it would parse them as normal text.
If extension is enabled, writer outputs shortcut reference links unless
doing so would cause problems (see test cases in `tests/Tests/Writers/Markdown.hs`).

Support shortcut reference links in markdown writer

---

README
changelog
src/Text/Pandoc/Options.hs
trypandoc/index.html

The website is called 'GitHub' afterall.

Replace occurrences of 'Github' with 'GitHub'

---

src/Text/Pandoc/Readers/Markdown.hs

Fixes related to #2026
values.
metadata field with no value, or a blank value.  So technically we
should both (a) skip one or more spaces, and (b) use many1 instead of
many for the value

Fixes for #2026

---

data/docx/word/footnotes.xml

Quick fix for issue #2032. Docx Writer puts this contents into footnotes.xml by default, ignoring reference.docx/word/footnotes.xml. If user tries to edit reference.docx directly, however, Word will complain about corrupt footnotes. This PR fixes it.

Reference Docx: update word/footnotes.xml

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Org-Mode's own html exporter converts the following org link:
[[http://example.com][https://www.haskell.org/static/img/logo.png]]
to
<a href="http://example.com">
</a>
but pandoc generates:
<a href="http://example.com">
<a href="https://www.haskell.org/static/img/logo.png" class="uri">
https://www.haskell.org/static/img/logo.png
</a>
</a>
which is useless. With this patch, it generates:
<a href="http://example.com">
</a>

Org reader: Allow image links with non-image targets

---

data/docx/word/styles.xml
src/Text/Pandoc/Writers/Docx.hs

Creates a "dirty" TOC at the beginning of document, before abstract, as per #458

Docx Writer: support for --toc option

---

README
data/docx/word/styles.xml
src/Text/Pandoc/Writers/Docx.hs

This changes `TableCaption` style, adding `w:keepNext` option, and adds `Figure` style to figure images and `FigureWithCaption` to figures with nonempty captions, which is based on `Figure`, and additionally has `w:keepNext` set as well
With this, caption and table/figure are not separated at page boundaries, as per #2031.

Docx Writer/Reference: Add keepNext to objects w/ captions

---

src/Text/Pandoc/Readers/LaTeX.hs
tests/latex-reader.latex
tests/latex-reader.native

This came to be in response to #1866. I'm creating a pull request to facilitate the process somewhat.
Comments are welcome.

LaTeX Reader: check for block-level newcommand aliases in blockCommand

---

data/odt/styles.xml
src/Text/Pandoc/Writers/ODT.hs
src/Text/Pandoc/Writers/OpenDocument.hs
tests/tables.opendocument
tests/writer.opendocument

Closes #376.
Works pretty much the same as Word writer.
Following styles are used for figures:
Figure -- for figure with empty caption
FigureWithCaption (based on Figure) -- for figure with caption
FigureCaption (based on Caption) -- for figure captions
Also, TableCaption (based on Caption) is used for table captions.
We need FigureWithCaption to set keepWithNext, in order to keep caption
with figure across pages.

ODT Writer: Figure captions

---

src/Text/Pandoc/Readers/LaTeX.hs
tests/Tests/Readers/LaTeX.hs

Something I wanted to do for a little while.
Removed redundant brackets and `$`s, consolidated imports, replaced some more obvious things with library functions, simplified nested `case` expressions, and changed `[Char]`s to `String`s.
I also accidentally stumbled on a little bug, that prevented `tildeEscape` parser from ever working. Fixed that as well (line 203 in new source). Should I also add a test, while I'm at it?
Behavior shouldn't be in any way changed, except for that bug thing, but wait for Travis just in case.

LaTeX Reader: Code cleanup

---

src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/Markdown.hs
tests/Tests/Readers/Markdown.hs

Closes #1909.
This essentially just parses apostrophe immediately following inline math and not immediately followed by whitespace as smart apostrophe.
Adds new parser combinator to Parsing.hs
`a <+?> b`
>   if `a` succeeds, applies `b` and `mappend`s output (if any) to result of `a`. If `b` fails,   it's just `a`, if `a` fails, whole expression fails.

MD Reader: Smart apostrophe after inline math

---

README

Fixed a minor Markdown syntax error that caused formatting problems and various minor formatting and consistency fixes for the program options.

Various minor formatting and consistency fixes for the README

---

pandoc.cabal
src/Text/Pandoc/Writers/RST.hs
tests/Tests/Writers/RST.hs
tests/test-pandoc.hs

This is pretty much required by docutils.
First level will be interpreted as level 1 anyway, and subsequent levels must be sequential.
See [pandoc-discuss thread][1] for background.
I'm not entirely sure it's OK to handle this in such way, since heading level information is irreversibly lost during conversion, but I see no other option really.
[1]: https://groups.google.com/d/msg/pandoc-discuss/mTG4phv5roA/ljApKvFDrY4J

RST Writer: Normalize headings to sequential levels

---

README
src/Text/Pandoc/Parsing.hs
tests/Tests/Readers/Markdown.hs

* Update parser to recognize citation keys starting with a digit.
* Update documentation accordingly.
* Test case added.
See https://github.com/jgm/pandoc-citeproc/issues/97

Allow digit as first character of a citation key.

---

src/Text/Pandoc/Writers/LaTeX.hs
tests/Tests/Writers/LaTeX.hs
tests/lhs-test.latex
tests/lhs-test.latex+lhs
tests/writer.latex

Currently, pandoc has hard-coded the following in order to make tight lists in LaTeX:
```hs
text "\\itemsep1pt\\parskip0pt\\parsep0pt"
```
Which is fine, but does not allow customizations.  For example, the `memoir` class already has a `\tightlist` declaration for this purpose:
```tex
\newcommand{\tightlist}{%
\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
```
I'm proposing to use a similar solution:
```diff
@@ In Writers/LaTeX.hs:
-then text "\\itemsep1pt\\parskip0pt\\parsep0pt"
+then text "\\tightlist"
@@ In templates/default.latex:
+\newcommand{\tightlist}{%
+  \setlength{\itemsep}{1pt}\setlength{\parskip}{0pt}\setlength{\parsep}{0pt}}
```
This allows us to customize the tightness to our needs.
If a person is using a custom LaTeX template (not based upon the `memoir` class), the …

LaTeX writer: Use a declaration for tight lists

---

src/Text/Pandoc/Readers/Markdown.hs
tests/Tests/Readers/Markdown.hs

Closes #2083
Footnotes: check if '^' follows '['
Links: check if '[' or '(' follows ']'

Fix for #2083 (citation suffix clashes with links and footnotes)

---

pandoc.cabal

Allow `pandoc` to build with the latest version of `zlib`.

Bump zlib upper version bounds

---

.travis.yml

Travis is planning to roll out a new [Container-based VM system](http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/) in the future. It promises shorter queue times and the possibility of [persisting/caching](http://docs.travis-ci.com/user/caching/) built dependencies. The latter could possibly be combined with LTS Haskell to enable <1 minute Travis build times, instead of ~15 minutes like now.
To do this safely they have to remove the ability to run as root via `sudo`. Since most uses of root access is to install APT packages, they came up with a [config syntax](http://docs.travis-ci.com/user/apt/) for specifying sources and packages.
@hvr suggested how the multi-version GHC build environments can use this new syntax [here](https://github.com/hvr/multi-ghc-travis/issues/17). …

Use the new Travis sudo-less syntax for APT dependencies

---

src/Text/Pandoc/MIME.hs

I was getting a MIME type not defined error when generating HTML from RMarkdown, saying that it did not recognize woff2.  I am using a bootstrap css theme that references a woff2 file.

Added woff2 to MIME types

---

README

Closes #2135
Current docs imply that `fenced_code_blocks` work for both `~` and `` ` ``, which is not true.
Also, removed some trailing spaces.

README: Add documentation on backtick_code_blocks

---

src/Text/Pandoc/Writers/ICML.hs
tests/writer.icml

InDesign expects LinkResourceURI to start with "file:" for local filenames, and won't render/link the image without.

Fix image URIs in ICML output

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Org mode allows headers to be tagged:
``` org-mode
* Headline         :TAG1:TAG2:
```
Instead of being interpreted as part of the headline, the tags are now
put into the attributes of empty spans.  Spans without textual content
won't be visible by default, but they are detectable by filters.  They
can also be styled using CSS when written as HTML.
This fixes #2160.

Org reader: put header tags into empty spans

---

src/Text/Pandoc/Readers/Org.hs

Code blocks can be followed by optional result blocks, representing the
output generated by running the code in the code block.  It is possible
to choose whether one wants to export the code, the result, both or
none.
This patch allows any kind of `Block` as the result.  Previously, only
example code blocks were recognized.
The change doesn't quite fix issue #2167, but offers a workaround.

Org generalize result block

---

src/Text/Pandoc/Writers/ICML.hs
tests/writer.icml

Colons are valid characters in URLs, and used e.g. by the Internet Archive's Wayback Machine - a popular resource amongst researchers. When InDesign encounters a HyperlinkURLDestination with more than one colon character in it, it crashes when placing the ICML. (This was tested against CS6.) The IDML specification hints at this requirement in section 6.4.1: "The colon apppears in the Name attribute of the style, but is encoded as %3a when it appears in the Self attribute". Follow this example for all colon characters in URLs.

Fix InDesign crash with URLs containing more than one colon character

---

src/Text/Pandoc/Readers/RST.hs
tests/Tests/Readers/RST.hs

The reference ``A-B_`` had the name ``ABB`` prior to this change, because the result of ``lookAhead`` was used.

Fix RST reference names with special characters

---

src/Text/Pandoc/Writers/OpenDocument.hs
tests/writer.opendocument

Fixes #2254 Removes the carriage return after a hard line break that causes the ODT writer to add a space at the beginning of the new line. Also changed the test, `tests/writer.opendocument`, to reflect this change.

Fix #2254 : OpenDocument writer adds space with hard line break

---

src/Text/Pandoc/Writers/CommonMark.hs

Switches the `<sup>` and `<sub>` tags.
This corrects the results of the following:
```shell
pandoc -t commonmark << EOT
^1^ ~2~
EOT
```
Previous output:
```html
<sub>1</sub> <sup>2</sup>
```
New output:
```html
<sup>1</sup> <sub>2</sub>
```

CommonMark Writer: Correct tags used for superscript/subscript

---

src/Text/Pandoc/Readers/RST.hs
tests/Tests/Readers/RST.hs

I’m not entirely sure if/how interpreted text (\`abc\`:emph:) is supposed to work in this context though.

RST: Support inline markup for field list names

---

src/Text/Pandoc/Writers/DokuWiki.hs
tests/writer.dokuwiki

MathJax seems currently to be the only maintained math rendering
extension for DokuWiki and it uses $..$ instead of <math>..</math>.

DokuWiki: write $..$ instead of <math>..</math>

---

src/Text/Pandoc/Readers/Markdown.hs
tests/Tests/Readers/Markdown.hs

Fixes #2321, which affects setext headers and atx headers with trailing `#`s.
I’m not confident this is the best solution. (For example, would `skipSpaces` make certain code blocks get parsed as headers instead?) I should probably also write more tests.

Fix implicit header refs for headers with extra spaces

---

README
src/Text/Pandoc/Readers/Markdown.hs

Using atx-style headers in markdown+lhs doesn't give a legal literate haskell file, since the usage of '#' is reserved.  I suggest supporting '=' instead of '#' for headings of level 3 or more.  This should pose no compatibility problems, since '#' is already illegal, and the '=' syntax is not used for anything else.  Using html style subheaders works only when generating html, not for other backends.

Use '=' instead of '#' for atx-style headers in markdown+lhs.

---

src/Text/Pandoc/Shared.hs

The issue was originally reported by CasperVector as
https://github.com/gentoo-haskell/gentoo-haskell/issues/427
Mainfests itself as a builg failure full of missing zip-archive
names:
src/Text/Pandoc/Shared.hs:756:49:
Not in scope: type constructor or class ‘Archive’
src/Text/Pandoc/Shared.hs:777:38: Not in scope: ‘toEntry’
src/Text/Pandoc/Shared.hs:786:19:
Not in scope: ‘toArchive’
Perhaps you meant ‘mbArchive’ (line 778)
Included Codec.Archive.Zip unconditionally.
Signed-off-by: Sergei Trofimovich <siarheit@google.com>

fix build failure with --flags=-https

---

pandoc.cabal
src/Text/Pandoc/CSS.hs
src/Text/Pandoc/Readers/HTML.hs
tests/html-reader.html
tests/html-reader.native

Fixes #2313 follow-up bug.
Now without css-text.

HTML Reader: Correctly parse inline list-style(-type) for <ol>

---

src/Text/Pandoc.hs
src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Refs #2354
This should also fix the table of contents (--toc) when generating a html file
from org input

Org reader: add auto identifiers if not present on headers

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

The previous verse parsing code made the faulty assumption that empty
strings are valid (and empty) inlines.  This isn't the case, so lines
are changed to contain at least a newline.
It would generally be nicer and faster to keep the newlines while
splitting the string.  However, this would require more code, which
seems unjustified for a simple (and fairly rare) block as *verse*.
This fixes #2402.

Make sure verse blocks can contain empty lines

---

README
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/LaTeX.hs

closes #2191 as long as you're not using LuaTex of pdfTex. I [tried to come up with fallbacks](http://tex.stackexchange.com/questions/262827/right-to-left-script-with-pdflatex-lualatex) for them but they don't seem to work reliably.
template adjustments: https://github.com/jgm/pandoc-templates/pull/120

Support bidirectional text output with XeLaTeX, ConTeXt and HTML

---

pandoc.hs

Update the default KaTeX JS/CSS links to the current version. KaTeX v0.5.1 has far more functions and symbols than v0.1.0, so it seems like a better default. I think technically this might break compatibility because we released a breaking change due to the greediness of the `\color` function, but this probably has very little impact.
I have not tested or linted this, but it shouldn't affect the build. I'm not sure if the tests will be affected by this change, I can run them if that is necessary.

Update KaTeX JS and CSS versions.

---

README

This adds a few headers to the variables section to separate the sections for various formats and editing templates, and fixes a few other minor details.
Note that there is still some inconsistency in the file in referring to the program as Pandoc or pandoc.

Revise variables discussion in README.

---

README

This includes links to all LaTeX packages and the suggested edits to the `lang` section from @mb21. Notes:
- ~~Trailing `#`s were removed from cross-referenced ATX-style headers (due to #2444: let me know if you would prefer to put these back or remove them from all headings).~~
- Link references will always be found at the end of each section.
- There is still inconsistency in capitalization (e.g. between Markdown and markdown; Pandoc, pandoc, and `pandoc`).
- The listing of LaTeX packages omits `fixltx2`, `xltxtra`, and `xunicode`, on the grounds that the first is simply part of LaTeX and the last two are required by `fontspec` (and technically it is redundant to load them separately). I wonder, however, about the utility of this entire section.

Improve links and cross-references in README.

---

pandoc.hs
src/Text/Pandoc.hs
src/Text/Pandoc/Shared.hs
src/Text/Pandoc/Writers/Man.hs

1. To allow the variable **pandocVersion** to be accessed by all writers, **pandocVersion** is being moved from `src/Text/Pandoc.hs` to  `src/Text/Pandoc/Shared.hs` to avoid circular import. (Since if writers were to access **pandocVersion**, it would need to import `src/Text/Pandoc.hs`, but we know writers are imported by `src/Text/Pandoc.hs`, causing circular import.)
2. Export **pandocVersion** as **pandoc-version** template variable.
3. Set **hyphenate** to be **true** by default.
This PR is required to implement https://github.com/jgm/pandoc-templates/issues/117.

Better man writer (revised)

---

README

This reflects the inclusion of all reveal.js variables in <https://github.com/jgm/pandoc-templates/pull/134>.

Update slides variables in README.

---

README

I was trying to figure out how could `Dogs?–in my house?` become `dogs--in-my-house` in the documentation page...

Fixed auto_identifiers examples

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Paragraphs can be followed by lists, even if there is no blank line
between the two blocks.  However, this should only be true if the
paragraph is not within a list, were the preceding block should be
parsed as a plain instead of paragraph (to allow for compact lists).
Thanks to @rgaiacs for bringing this up.
This fixes #2464.

Org reader: fix paragraph/list interaction

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Org-mode allows to skip the argument of a code block header argument if
it's toggling a value.  Argument-less headers are now recognized,
avoiding weird parsing errors.
The fixes are not exactly pretty, but neither is the code that was
fixed.  So I guess it's about par for the course.  However, a rewrite of
the header parsing code wouldn't hurt in the long run.
Thanks to @jo-tham for filing the bug report.
This fixes #2269.

Org reader: allow toggling header args

---

src/Text/Pandoc/Writers/LaTeX.hs

Only the environment name should be capitalised (`\begin{Arabic} … \end{Arabic}`), but not the command, which has to be `\textarabic{…}`.

LaTeX writer: \textarabic fix

---

src/Text/Pandoc/Writers/LaTeX.hs

el-polyton, not el-poly, see http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Added de-CH-1901, fixed el-polyton

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Markup as the very first item in a header wasn't recognized.  This was
caused by an incorrect parser state: positions at which inline markup
can start need to be marked explicitly by changing the parser state.
This wasn't done for headers.  The proper function to update the state
is now called at the beginning of the header parser, fixing this issue.
This fixes #2504.

Org reader: fix markup parsing in headers

---

src/Text/Pandoc/Readers/LaTeX.hs

With this change, the `comment` environment is handled in a similar way to the `verbatim` environment, except that its content is discarded.

LaTeX reader: Handle `comment` environment.

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Smart quotes, ellipses, and dashes should behave like normal quotes,
single dashes, and dots with respect to text markup parsing.  The parser
state was not updated properly in all cases, which has been fixed.
Thanks to @conklech for reporting this issue.
This fixes #2513.

Org reader: Fix emphasis rules for smart parsing

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Definition list markers (i.e. double colons `::`) must be surrounded by
whitespace to start a definition item.  This rule was not checked
before, resulting in bugs with footnotes and some link types.
Thanks to @conklech for noticing and reporting this issue.
This fixes #2518.

Org reader: Require whitespace around def list markers

---

pandoc.hs

`.adoc` is the extension recommended at <http://asciidoctor.org/docs/asciidoc-writers-guide/>.

Allow .adoc file extension for AsciiDoc.

---

README

Depends on #2508 and https://github.com/jgm/pandoc-templates/pull/141.

Update LaTeX/ConTeXt link colour usage in README.

---

src/Text/Pandoc/Writers/HTML.hs

This is no longer needed with the updates to the template in https://github.com/jgm/pandoc-templates/commit/da139313d2e2ba99f4d31be6ea376dabf8c877ff

Remove redundant `center` variable for reveal.js.

---

src/Text/Pandoc/Writers/HTML.hs

Previously, when using headers below the slide level, pauses are left
uninterpreted into pauses. In my opinion, unexpected behavior but
intentional looking at the code.
Fixes #2530

Interpret pauses correctly for all headers

---

README

One could also tell users to add this to header-includes if `subtitle` is desired for `article` and so forth, but I will leave it out for now for the sake of simplicity:
```tex
\providecommand{\subtitle}[1]{%
\usepackage{titling}
\posttitle{%
\par\large#1\end{center}}
}
```

Document change to subtitle in LaTeX.

---

src/Text/Pandoc/Writers/ICML.hs
tests/tables.icml
tests/writer.icml

instead of appending them to every ParagraphStyleRange
closes #2501 
I've looked over the `tests/writer.icml` pretty carefully so I think we've got all the line breaks now where they're supposed to be. But if someone wants to run a few documents of his own to make sure I didn't break anything, that would be great.

ICML writer: intersperse line breaks

---

README
src/Text/Pandoc/Writers/LaTeX.hs

If one wants to use csquotes for LaTeX output one currently have to modify the template, which is annoying as one then have to keep one's modified template in sync with the official version.
This pull request offers a solution to this: pandoc should also scan the included header files. Then one can use csquotes without having to modify the template.

Consider header files when determining whether to use csquotes

---

.gitignore

The .stack-work directory is analogous to a cabal sandbox;
it comprises temporary build artifacts.

Add .stack-work to gitignore

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Continue scanning for comment subtrees beyond only the first block.
Note to self: when writing an recursive function, don't forget to, you
know, actually recurse.
Shout to @mrvdb for noticing this.
This fixes #2628.

Fix function dropping subtrees tagged :noexport:

---

stack.full.yaml
stack.yaml

Missing end-quote in the stack yaml files makes them unparseable.

Fix typo in stack build files

---

src/Text/Pandoc/Writers/LaTeX.hs

Removing the centering option `[c]` to the `longtable` environment allows LaTeX templates to control the overall table alignment in a document by setting the `longtable` length variables `LTleft` and `LTright`.
Example:
```latex
\setlength\LTleft\parindent
\setlength\LTright\fill
```
results in left aligned tables that respect paragraph indentation.
This patch will not change the default behavior of pandoc because `centering` is the default for tables even if `[c]` is not specified.

LaTeX writer: Allow more flexible table alignment

---

README
pandoc.cabal
pandoc.hs
src/Text/Pandoc.hs
src/Text/Pandoc/Writers/TEI.hs
tests/Tests/Writers/TEI.hs
tests/test-pandoc.hs

Add a TEI Writer (see https://github.com/jgm/pandoc/issues/2047), outputting TEI XML consistent with the [TEI Simple](https://github.com/TEIC/TEI-Simple) subset. 
This writer was developed by modifying the DocBook writer.
The standalone output for this writer depends on a new template, `default.tei`, submitted as part of a [separate pull request](https://github.com/jgm/pandoc-templates/pull/179) (#179) to the `pandoc-templates` repostiory.

Add TEI Writer.

---

INSTALL

Stack installation instructions have moved to docs.haskellstack.org

Fix stack link in INSTALL

---

stack.full.yaml

The line causes an error with stack 1.0.2:
```
Could not parse '/pandoc-build/pandoc/stack.full.yaml':
AesonException "Error in $.extra-deps: failed to parse field 'extra-deps': failed to parse field extra-deps: expected [a], encountered Null"
See http://docs.haskellstack.org/en/stable/yaml_configuration.html.
```

Remove stray line from stack.full.yaml

---

README

Remove extra `be`
`overriden` → `overridden`

Fix typos in Readme

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

Cleanup of the code for link target handling.  Most notably, the
canonicalization of a link is handled by a separate function.
This fixes #2684.

Org reader: Refactor link-target processing

---

src/Text/Pandoc/Writers/Markdown.hs
tests/writer.markdown

I use pandoc as a formatter and pretty pretty-printer for markdown documents. Many markdown tools in my pipeline accept YAML metadata blocks delimited top and bottom by three hyphens `---` (for example: [jekyll](http://jekyllrb.com), [mustache](https://mustache.github.io) or [hugo](https://gohugo.io)). Pandoc generated markdown uses three dots `...` to mark the bottom of a metadata block which breaks these tools.
This patch changes the markdown writer to use three hyphens to mark the end of a metadata block. 
Some notes:
- The reader remains untouched and will still accept dots as well
- Other tools that rely on the dots may break
- The YAML spec suggests `...` to mark the end of a document in a stream of YAML documents
- This time I did not forget to update the tests

Markdown writer: Use hyphens for yaml metadata block bottom line

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

The convention used by pandoc for figures is to mark them by prefixing
the name with "fig:".  The org reader failed to do this if a figure had
no name.  The test for this was broken as well.
This fixes #2643.

Prefix even empty figure names with "fig:"

---

src/Text/Pandoc/Writers/LaTeX.hs

This allows one to access the hyphenation patterns at <http://mirrors.ctan.org/language/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-la-x-classic.tex>, using its private language tag.

Recognize `la-x-classic` as Classical Latin.

---

src/Text/Pandoc/Writers/LaTeX.hs
tests/writers-lang-and-dir.latex

Updates the list from the hyphenation files at <http://mirror.ctan.org/language/hyph-utf8/tex/generic/hyph-utf8/loadhyph/>.

LaTeX writer: Add missing languages.

---

src/Text/Pandoc/Writers/LaTeX.hs
tests/writers-lang-and-dir.latex

allow for optional argument in square brackets, closes #2728

LaTeX Writer: fix polyglossia to babel env mapping

---

src/Text/Pandoc.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Writers/Docbook.hs
tests/Tests/Old.hs
tests/tables.docbook5
tests/writer.docbook5

- Extends docbook writer to add support for DocBook 5
- Avoids having to post-process DocBook 4.5 output with db4-upgrade.xsl
- Includes namespace in top-level element
- Use link with xlink:href attribute instead of ulink
Partially addresses feature request https://github.com/jgm/pandoc/issues/2164

Docbook5 write support

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

The org-reader was droping space after unescaped LaTeX-style symbol
commands: `\ForAll \Auml` resulted in `∀Ä` but should give `∀ Ä`
instead.  This seems to be because the LaTeX-reader treats the
command-terminating space as part of the command.  Dropping the trailing
space from the symbol-command fixes this issue.

Org reader: fix spacing after LaTeX-style symbols

---

src/Text/Pandoc/Readers/Org.hs
tests/Tests/Readers/Org.hs

- Fix parsing of empty rows.
- Allow and recognize empty table cells.
- Reduce table normalization.  This reflects the Emacs Org exporter's behavior, as opposed to that of the Org editor. The behavior of the latter was what the reader originally aimed for.

Org reader: table parsing code refactoring and fixes

---

src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Writers/Org.hs
tests/Tests/Readers/Org.hs

- Fix reader regression introduced in the previous fix.
- Include empty table rows in org-mode output.

Org fixes (reader and writer)

---

pandoc.cabal
src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
tests/Tests/Readers/Org.hs

Org-mode allows to specify export settings via `#+OPTIONS` lines <http://orgmode.org/manual/Export-settings.html#Export-settings>.  Basic support for this is added to the reader.  Only toggling of the simple sub-/superscript syntax is supported as of now, other options are currently ignored.

Org reader: basic support for export settings

---

src/Text/Pandoc/Writers/LaTeX.hs
tests/tables.latex

Reimplement on 4c684561ee0665b014e887ae559b7020e4e9f2d3
The problem with 4c68456 was a space between the cell contents and the `\strut` that affected the alignment.

Retake on strut with \minipage inside tables

---

src/Text/Pandoc/Readers/RST.hs
tests/Tests/Readers/RST.hs

According to http://docutils.sourceforge.net/docs/ref/rst/directives.html#code,
the code directive supports the ":class:" option.

Add class option for code block in RST reader

---

appveyor.yml

Also enable the build again (build: off just prevents a default msbuild based one)
See https://github.com/jgm/pandoc/pull/2910#issuecomment-218842826 for the problem with the artifacts.

Better way to find the artifacts on appveyor

---

src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
tests/Tests/Readers/Org.hs

Arbitrary key-value pairs can be added to some block types using a `#+ATTR_HTML` line before the block.  Emacs Org-mode only includes these when exporting to HTML, but since we cannot make this distinction here, the attributes are always added.
The functionality is now supported for figures.
This closes #1906.

Org reader support for ATTR_HTML statements

---

src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Writers/Org.hs
tests/Tests/Readers/Org.hs
tests/writer.org

Add support for `:PROPERTIES:` drawers to both Org reader and writer.

Org properties drawer

---

src/Text/Pandoc/Readers/EPUB.hs

Consider this [example epub](https://www.dropbox.com/s/u11iwp021sqtslb/linktest.epub).
With this pull, at least `pandoc linktest.epub -o out.html` preserves all the links.
However, because the epub reader [prepends each file in the epub simply with a span with the appropriate id](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Readers/EPUB.hs#L75) and that (empty) span is not rendered in the LaTeX writer, the following still has broken links: `pandoc linktest.epub -o out.pdf`

EPUB Reader: normalise Link id as well

---

src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/Inlines.hs
tests/Tests/Readers/Org.hs

Org-mode version 9 usees a new syntax for export blocks.  Instead of the old
`#+BEGIN_<FORMAT>`, where `<FORMAT>` is the format of the block's
content, the new format uses `#+BEGIN_export <FORMAT>` instead.  Both
types are supported now.
This PR also includes a commit to refactor `BEGIN..END` parsing code, increasing
Emacs Org-mode compatibility with regard to block content indentation handling.

Org export blocks

---

src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/Parsing.hs
tests/Tests/Readers/Org.hs

The *org-ref* package is an org-mode extension commonly used to manage
citations in org documents.  Basic support for the `cite:citeKey` and
`[[cite:citeKey][prefix text::suffix text]]` syntax is added.

Org reader: support org-ref style citations

---

pandoc.cabal
src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
src/Text/Pandoc/Readers/Org/Parsing.hs
src/Text/Pandoc/Readers/Org/Shared.hs

Support for *smart quotes*, *emphasized text*, and *special string* export settings is added to the Org-mode reader.  This means that `'`, `-`, and  `*` settings now have an effect when specified in `#+OPTIONS` lines,

Org reader: support more export settings

---

src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/Parsing.hs
tests/Tests/Readers/Org.hs

Support for the citation style which was [discussed](https://lists.gnu.org/archive/html/emacs-orgmode/2015-02/msg00475.html) on the Org-mode mailing list.  The syntax is based on Pandoc Markdown's citation style, it was adjusted to respect and handle Org-mode idiosyncrasies by Richard Lawrence and contributors on the Org-mode mailing list.  It's dubbed *Berkeley style* due to its place of origin.
This was developed in close cooperation with @wyleyr.

Org reader: "Berkeley style" citation support

---

src/Text/Pandoc/Writers/Docbook.hs

Declare 'xlink' namespace in Docbook5 XML output, since the xlink namespace is used for external links in Docbook 5.0 output.

Docbook writer: Declare xlink namespace in Docbook5 output

---

pandoc.cabal

Building with the new release went fine here, and it works correctly.

Allow tagsoup 0.14

---

src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Writers/Org.hs
tests/Tests/Readers/Org.hs

Org mode allows arbitrary raw inlines ("export snippets" in Emacs
parlance) to be included as `@@format:raw foreign format text@@`.
Support for this features is added to the Org reader and writer.

Org reader: raw inlines in arbitrary formats

---

README

Document MultiMarkdown explicitly as possible input/output format and Emacs Org mode as a format which includes raw TeX and HTML.
The last commit assumes #2980 to be merged.

Documentation updates

---

src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/Inlines.hs

Partial functions like `head` lead to avoidable errors and should be
avoided.  They are replaced with total functions.
This fixes #2991.

Org reader: remove partial functions

---

src/Text/Pandoc/Readers/Org/Blocks.hs
tests/Tests/Readers/Org.hs

Figure labels given as `#+LABEL: thelabel` are used as the ID of the
respective image.  This allows e.g. the LaTeX writer to add proper `\label`
markup.
This fixes half of #2496 and #2999.

Org reader: support figure labels

---

pandoc.cabal
src/Text/Pandoc/Readers/Org.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/ExportSettings.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
tests/Tests/Readers/Org.hs

Support for the `H` (maximum level of headlines) and `arch` (treatment of archived trees) settings is added to the reader.
The document is now parsed into a document tree consisting of headlines and their block contents nodes and subsections as subtrees.  This structure resembles that used by the Emacs Org mode parser and simplifies transformations of the document tree.

Org reader: support archived trees, headline levels export setting

---

src/Text/Pandoc/Readers/Org/Blocks.hs

Some less-than-smart code required a pragma switching off overlapping
pattern warnings in order to compile seamlessly.  Using view patterns
makes the code easier to read and also doesn't require overlapping
pattern checks to be disabled.

Org reader: replace ugly code with view pattern

---

src/Text/Pandoc/Writers/Org.hs
tests/writer.org

Div blocks handling is changed to make the output look more like
idiomatic org mode:
- Div-wrapped content is output as-is if the div's attribute is the
null attribute.
- Div containers with an id but neither classes nor key-value pairs
are unwrapped and the id is added as an anchor.
- Divs with classes associated with greater block elements are
wrapped in a `#+BEGIN`...`#+END` block.
- The old behavior for Divs with more complex attributes is kept.

Org writer: improve Div handling

---

src/Text/Pandoc/Readers/Org/Inlines.hs
tests/Tests/Readers/Org.hs

Org rules for allowed characters before or after markup chars were not
checked for verbatim text.  This resultet in wrong parsing outcomes of
if the verbatim text contained e.g. space enclosed markup characters as
part of the text (`=is_substr = True=`).  Forcing the parser to update
the positions of allowed/forbidden markup border characters fixes this.
This fixes #3016.

Org reader: fix parsing of verbatim inlines

---

README.md

The link to the online manual used the `https` schema, which doesn't work for this resource.  Changed to `http`.

Use http to access online documentation

---

README.md

Parenthesized items following [ ] links need to be escaped. Otherwise, those will be turned into the URLs for those links.

Fix the LaTeX and EPUB links

---

src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/Shared.hs
tests/Tests/Readers/Org.hs

Image sources as those in plain images, image links, or figures, must be
proper URIs or relative file paths to be recognized as images.  This
restriction is now enforced for all image sources.
This also fixes the reader's usage of uncleaned image sources, leading
to `file:` prefixes not being deleted from figure
images (e.g. `[[file:image.jpg]]` leading to a broken image 
`<img src="file:image.jpg"/>`)
Thanks to @bsag for noticing this bug.

Org reader: ensure image sources are proper links

---

src/Text/Pandoc/Readers/Org/Blocks.hs
tests/Tests/Readers/Org.hs

Leading spaces in verse lines are converted to non-breaking spaces, so
indentation is preserved.
This fixes #3064.

Org reader: preserve indentation of verse lines

---

pandoc.hs

- remove a space between `[` and `*` in the list of input formats, to match the list of output formats
- add space after the `*`s, for improved readability

synchronize spacing of footnotes in help output

---

src/Text/Pandoc/Writers/LaTeX.hs

Translate NARROW NO-BREAK SPACE into LaTeX' `\,`.

Translate NARROW NO-BREAK SPACE into LaTeX.

---

MANUAL.txt

Make it clearer that structured author variables require a custom
template.
Many thanks to John Muccigrosso (@Jmuccigr) for his help in addressing
this issue.
This supersedes and closes #2148.

Put note on structured vars in separate paragraph

---

src/Text/Pandoc/Writers/LaTeX.hs
tests/writer.latex

Do not set `[htbp]` placement options on each figure to allow overriding them by them using `\fps@figure` redefintion either in header or in template. See also #3103.

LaTeX: Do not set [htbp] figure placement options.

---

pandoc.hs

Reference:
- [Releases · Khan/KaTeX](https://github.com/Khan/KaTeX/releases)
- [KaTeX - cdnjs.com - The best FOSS CDN for web related libraries to speed up your websites!](https://cdnjs.com/libraries/KaTeX)

Update KaTeX to v0.6.0

---

MANUAL.txt
man/pandoc.1
pandoc.hs

I can't reopen #3142. So I open a new one here.
Google Chart API has already been deprecated on April 20, 2015. It is now a "zombie" service:
>While the dynamic and interactive Google Charts are actively maintained, we officially deprecated the static Google Image Charts way back in 2012. This gives us the right to turn it off without notice, although we have no plans to do so.
> from [Image Charts  |  Google Developers](https://developers.google.com/chart/image/)
Info on CodeCogs:
1. [Usage Policy | CodeCogs Equation Editor](http://www.codecogs.com/latex/usage.php): **up to 3,000 equations a day for testing and non-commercial use**
2. [Implement an API call to display LaTeX as inline image - Meta Stack Exchange](http://meta.stackexchange.com/questions/53436/implement-an-api-call-to-displa …

Replace Google Chart API by CodeCogs

---

MANUAL.txt
man/pandoc.1
src/Text/Pandoc/Options.hs
temp2.txt

According to [MultiMarkdown-5/using_mmd.md](https://github.com/fletcher/MultiMarkdown-5/blob/gh-pages/using_mmd.md#multimarkdown-and-latex), MultiMarkdown expects raw LaTeX to be within HTML comments, *e.g.*,
```html
<div align="right">
testing flush right.
</div>
```
I tried to compile the above file by `pandoc -f markdown_mmd -o test-pandoc.md test.md` and the HTML comments is not parsed as raw LaTeX.
I don't think pandoc should have a reader for that syntax since by [MultiMarkdown-5/Raw Source](http://fletcher.github.io/MultiMarkdown-5/raw.html), the same syntax could be used for "Raw LaTeX/OpenDocument/etc.".
The pull request is to remove the inclusion of `raw_tex` in `markdown_mmd` variants.
In other words, a raw LaTeX in the pandoc sense would never appears in a valid MultiMarkdown …

Remove mmd raw tex

---

MANUAL.txt
pandoc.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Writers/Markdown.hs
tests/Tests/Writers/Markdown.hs

As discussed in #3076 
A couple of notes:
1. I've used the option `--reference-location=block|section|document`. I didn't want to specify markdown, since it seemed like this could be used for rst and org as well (though I don't know as much about those formats). If this seems like it's overloading the term "reference," I'm open to changing it.
2. For the `--reference-location=block` option, I've implemented it so that it comes after top-level blocks -- i.e., not after pars in a table cell, or list items. I think this is more in line expectations, and will produce better looking output. Also, per a quick check on babelmark, it will produce output that is more likely to be compliant with other parsers., 
3. The changes to the markdown writer required a reader monad for keeping track of …

Specify location for footnotes (and reference links) in MD output

---

src/Text/Pandoc/Readers/Odt/ContentReader.hs
tests/odt/native/imageIndex.native
tests/odt/native/imageWithCaption.native

Latex Writer only handles captions if the image's title
is prefixed with 'fig:'.

[odt] proper formatting of an image with a caption

---

MANUAL.txt
pandoc.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/Docbook.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/TEI.hs
tests/Tests/Writers/Docbook.hs
tests/Tests/Writers/LaTeX.hs

Add --parts command line argument.
This only effects LaTeX writer, and only for non-beamer output formats.
It changes the output levels so the top level is 'part', the next
'chapter' and then into sections.
This is a rebased and slightly altered version of PR #1554.  @cwoac, I hope you don't mind the changes.

Add command line option allowing to set type of top-level divisions

---

src/Text/Pandoc/Readers/Markdown.hs
tests/Tests/Readers/Markdown.hs

This should fix the first part of #2678.

Markdown Reader: add attributes for autolink

---

src/Text/Pandoc/Readers/Odt/ContentReader.hs
tests/odt/native/simpleTable.native

ODT reader simply provided an empty header list
which meant that the contents of the whole table,
even if not empty, was simply ignored.
While we still do not infer headers we at least have
to provide default properties of columns.

[odt] Infer tables' header props from rows

---

MANUAL.txt
man/pandoc.1
src/Text/Pandoc/Readers/Markdown.hs

I adapted the relevant code from `spanHtml` into `bracketedSpan` to check if small caps style is used in bracketed spans.
I then update the `MANUAL.txt` accordingly to reflect this use.
I tested and it compile successfully. The code I used to test if the small caps with bracketed span works is:
``` markdown
1. HTML:
- <span style="font-variant:small-caps;">Small caps</span>
- <span style="font-variant:small-caps">Small caps</span>
- <span style="font-variant: small-caps">Small caps</span>
2. markdown:
- [Small caps]{style="font-variant:small-caps;"}
- [Small caps]{style="font-variant:small-caps"}
- [Small caps]{style="font-variant: small-caps"}
```
I don't know anything about the tests yet so I didn't modify any of the test to test this.
Edit: this should partially resolves issue #2761

Small caps in Bracketed Spans

---

CONTRIBUTING.md

Split off from #3193, let each pull request deal with a slightly different issue:
- em-dash should be used here, not en-dash (which is for, e.g., ranges).
- unicode em-dash is used because GitHub don’t do SmartyPants on dashes.

CONTRIBUTING.md: minor change in wording and punctuation

---

pandoc.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/Docbook.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/TEI.hs
tests/Tests/Writers/Docbook.hs
tests/Tests/Writers/LaTeX.hs

Pandoc uses heuristics to determine the most resonable top-level
division type when emitting LaTeX or Docbook markup.  It is now possible
to overwrite this implicitly set top-level division via the
`top-level-division` command line parameter.
API change (`Text.Pandoc.Options`): the type of the
`writerTopLevelDivision` field in of the `WriterOptions` data type is
altered from `Division` to `Maybe Division`. The field's default value
is changed from `Section` to `Nothing`.
Closes: #3197

Allow to overwrite top-level division type heuristics

---

src/Text/Pandoc/Writers/OpenDocument.hs

Nested blockquotes start using indents like before. Quotation style is still in use, so the style's indent settings take effect on the first level of blockquotes. This is to fix #2747. Some mechanism to set a starting indent for the second level block quotes and a delta for increasing levels might be useful, but that is beyond my capabilities in Haskell.

Open Document writer: set first level of blockquotes to not use indent

---

MANUAL.txt
pandoc.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/Docbook.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/TEI.hs
tests/Tests/Writers/Docbook.hs
tests/Tests/Writers/LaTeX.hs

The "default" option is no longer represented as `Nothing` but via a new
type constructor, making the `Maybe` wrapper superfluous.
The default behavior of using heuristics can now be enabled explicitly
by setting `--top-level-division=default`.
API change (`Text.Pandoc.Options`): The `Division` type was renamed to
`TopLevelDivision`. The `Section`, `Chapter`, and `Part` constructors
were renamed to `TopLevelSection`, `TopLevelChapter`, and
`TopLevelPart`, respectively. An additional `TopLevelDefault`
constructor was added, which is now also the new default value of the
`writerTopLevelDivision` field in `WriterOptions`.

Refactor top-level division selection

---

.travis.yml

See commercialhaskell/stack#2784:
>Although `language: generic` is undocumented, it is widely used...
It doesn’t give any visible speed boost, if any, probably only shave dozens seconds in boot up time. But since commercialhaskell/stack accepted this pull request, I figure it at least does no harm to make into pandoc.

travis: use language generic

---

MANUAL.txt

Hi John,
While reading the Pandoc manual on the website, I noticed that the `--list-hightlight-styles` had an extra `t`. I created this pull request to fix this type and another spelling mistake. In a separate commit, I also fixed the case for a few other nouns, e.g., “ASCII”, “Unicode”, “Latin”, “JavaScript”, “CSS” (I used a separate commit in case you don’t want to merge those changes).
I noticed that the same spelling mistakes are in `man/pandoc.1` but I figured that the Troff file is automatically generated from the Markdown file.
Thanks for creating such a great program (and for CommonMark),
Anthony

Minor spelling typos in the manual

---

MANUAL.txt
README.md

- ConTeXt garden: trivial editing
- groff man: Apple's link returned 401. But if clicked through, it actually works. Nonetheless, I replace the link to GNU's version since it is the source.
- docx openxml: the link is broken. I replaced it with the best I can find. Please double check it is ok.
By the way, when building the `man`, it got errors. It doesn't affect this commit because the `man` doesn't have those links. The error is:
```bash
$ make man/pandoc.1
pandoc MANUAL.txt -t man -s --template man/pandoc.1.template \
--filter man/capitalizeHeaders.hs \
--filter man/removeNotes.hs \
--filter man/removeLinks.hs \
--variable version="pandoc 1.19.1" \
-o man/pandoc.1
pandoc: Error running filter man/capitalizeHeaders.hs
fd:4: hPutBuf: resource vanished (Broken pipe)
make: *** …
```

MANUAL/README: Fixed broken links

---

src/Text/Pandoc/Readers/Markdown.hs
tests/Tests/Readers/Markdown.hs

closes #3323
I think the change is worth the risk of possibly breaking a small handful of existing documents... maybe discussion needed?

markdown reader: disallow space between inline code and attributes

---

INSTALL.md

Previously, not all code on the installation page was highlighted/wrapped in code blocks due to incorrect indentation.
A screenshot of incorrectly generated output is attached.
http://pandoc.org/installing.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jgm/pandoc/3335)

Indent code on the installation page.

---

src/Text/Pandoc/Readers/MediaWiki.hs

Change MediaWiki reader's behavior when the smart option is parsed to
match other readers' behavior.
Fix #2012.

MediaWiki reader: Fix quotation mark parsing

---

README.md

- Reorder badges, resulting in a more pleasant look of the readme.
- Alter some badge labels to clarify the badge's purpose (e.g. the label "current release" of the hackage badge is replaced with "hackage release").
- Change the color of the "license" label to gray.
- Ensure that only the travis build status of the master branch is shown.
- Add a badge for homebrew.
- Add a badge for the pandoc-discuss mailing list.

Rearrange and extend badges in README

---

data/sample.lua

Fix for "pandoc: user error (Incorrect result type (string expected, got nil))." when the source format contains Raw data.

Fix sample.lua barfing on Raw data

---

.travis.yml

I added GHC 8.0.2 to the Travis build and allow it to fail (since it is not a stable release yet)
I tried to catch the error reported in #3372 but instead [it just passed](https://travis-ci.org/ickc/pandoc/jobs/194631003).

travis: catch #3372

---

src/Text/Pandoc/Writers/Org.hs

This comment is likely copied from RST.hs where 'refs' variable indeed exists, but makes no sense here.

Org.hs: remove misleading comment

---

MANUAL.txt
src/Text/Pandoc/Writers/Docbook.hs
src/Text/Pandoc/Writers/HTML.hs

fixes #3397
btw, the Haddock writer also uses `writerIdentifierPrefix` for its fake notes, which is not documented in the README... not sure whether to change the writer or the README...

HTML and DocBook writers: fix internal links with writerIdentifierPrefix opt

---

MANUAL.txt
src/Text/Pandoc/Shared.hs

Fixes #3384 
When requesting a document from a URL, a user can now specify the User-Agent by doing something like:
```
USER_AGENT="Mozilla/5.0" pandoc -f html -t markdown http://www.fsf.org
```
This should fix the problem of Pandoc appearing as an "unsupported browser" to some websites. :)

Allow user to specify User-Agent

---

pandoc.cabal
src/Text/Pandoc/Writers/Org.hs
test/Tests/Writers/Org.hs
test/test-pandoc.hs

According to [The Org Manual](http://orgmode.org/manual/Internal-links.html#Internal-links), internal links should contain `#`. Links without `#`
> lead to a text search in the current file
Likely stripping `#` was not intended.

Org anchor links

---

src/Text/Pandoc/Writers/ZimWiki.hs
test/tables.zimwiki
test/writer.zimwiki

ZimWiki writer: removed internal formatting from note and table cells because ZimWiki does not support it. Changed source code type mapping to match the one used by the ZimWiki's sourcecode plugin.

ZimWiki writer: added source code naming, removed internal formatting from note and table cells

---

INSTALL.md

People probably stop reading after "for debian and ubuntu" if they're on, say, redhat...

INSTALL.md put rpm-based distros on separate point

---

src/Text/Pandoc/ImageSize.hs
src/Text/Pandoc/Writers/Docx.hs
src/Text/Pandoc/Writers/ICML.hs
src/Text/Pandoc/Writers/ODT.hs
src/Text/Pandoc/Writers/RTF.hs

This only looks at the `width` and `height` attributes of the SVG root element which are not mandatory. So it ignores e.g. the `viewBox` attribute, see https://www.w3.org/TR/SVG/coords.html#ViewportSpace and https://css-tricks.com/scale-svg/
Partly resolves https://github.com/jgm/pandoc/issues/3462

make imageSize recognize basic SVG dimensions, see #3462

---

CONTRIBUTING.md
COPYRIGHT
INSTALL.md
benchmark/benchmark-pandoc.hs
benchmark/weigh-pandoc.hs

I noticed failures running the benchmarks:
```
pandoc-2.0: benchmarks
Running 1 benchmarks...
Benchmark benchmark-pandoc: RUNNING...
benchmark-pandoc: tests/testsuite.txt: openFile: does not exist (No such file or directory)
Benchmark benchmark-pandoc: ERROR
Completed 2 action(s).
--  While building package pandoc-2.0 using:
/home/or/programming/haskell/pandoc/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 bench benchmark-pandoc
Process exited with code: ExitFailure 1
```
So I looked and saw stale references to a directory `tests` which should instead be `test`.  Updating the references fixed the benchmark failures.  I then searched through the project to see if there were other references to it, and found and updated a …

Fix stale references to `tests` directory

---

MANUAL.txt
src/Text/Pandoc/App.hs

add template variables for source and destination filename

---

src/Text/Pandoc/Writers/AsciiDoc.hs
src/Text/Pandoc/Writers/DokuWiki.hs
src/Text/Pandoc/Writers/Man.hs
src/Text/Pandoc/Writers/Org.hs
src/Text/Pandoc/Writers/RST.hs
src/Text/Pandoc/Writers/Textile.hs
src/Text/Pandoc/Writers/ZimWiki.hs

Replaced  `liftM`, `fmap` and recurring `get >>= return` with dedicated `gets`

Writers: Use gets to access MonadState where possible

---

data/templates/default.html5
test/lhs-test.html
test/lhs-test.html+lhs
test/writer.html5

This is a pull request (pr) to make default.html5 polyglot markup conformant. default.html4 is left alone. 
Issue jgm/pandoc-templates#237, "default.html5. Polyglot Markup", ~~(the first two commit messages wrongly reference #237 in jgm/pandoc)~~ contains a prior discussion although the resulting conclusions are expressed here, in the pr comments and commit messages. The following commits are intended to be pushed to this PR. Those ticked have been pushed to this PR:
* ~~html5. Polyglot. Add default title value: "My Title".~~
In-principle consensus has been reached in issue jgm/pandoc-templates#237 on the changes contained in the first two commits. Consensus has not yet been achieved on the changes contained in the last two commit (yet to be pushed).
Polyglot Markup is a W3C standard: …

Issue237 html5 polyglot: Make default.html5 polyglot markup conformant.

---

MANUAL.txt

Make clear that template variable `meta-json` does not contain plain text values or JSON output format but field values transformed to the selected output format.

Clarify that meta-json contains transformed values

---

README.md
data/templates/default.muse
deb/control.in
pandoc.cabal
src/Text/Pandoc.hs
src/Text/Pandoc/Writers/Muse.hs
test/Tests/Old.hs
test/Tests/Writers/Muse.hs
test/tables.muse
test/test-pandoc.hs
test/writer.muse
trypandoc/index.html

Add Muse writer

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3534.md

lstinline with braces can be used (verb cannot be used with braces)

---

pandoc.cabal
src/Text/Pandoc/Lua.hs
src/Text/Pandoc/Lua/PandocModule.hs
src/Text/Pandoc/Lua/StackInstances.hs
test/Tests/Lua.hs
test/lua/markdown-reader.lua

Plain text readers are exposed to lua scripts via the `pandoc.reader`
submodule, which is further subdivided by format.  Converting e.g. a
markdown string into a pandoc document is possible from within lua:
doc = pandoc.reader.markdown.read_doc("Hello, World!")
A `read_block` convenience function is provided for all formats,
although it will still parse the whole string but return only the first
block as the result.
Custom reader options are not supported yet, default options are used
for all parsing operations.

Lua module: add readers submodule

---

src/Text/Pandoc/Writers/LaTeX.hs

Updated the LaTeX writer to also include \VerbatimFootnotes in the
preamble for highlighted code blocks. Previously this was only done for
raw code blocks.
This is my first attempt in contributing to pandoc, so my apologies for any mistakes I might have made.

Include \VerbatimFootnotes for highlighted code blocks

---

src/Text/Pandoc/Writers/HTML.hs
test/writer.html4
test/writer.html5

The HTML writer now also adds the class `footnoteBack` to back references
of footnotes. This allows for easier CSS styling.
Fixes #1831

Add class to footnote back references

---

src/Text/Pandoc/Writers/HTML.hs

HTML links containing classes originally now preserve them when using javascript email obfuscation.
Fixes #2989

Add original classes to JS obfuscated links

---

stack.yaml

Change 1778f232921cd7ef0cf34e8d87562a83262ae367 was not enough, as foundation-0.0.4 from lts-8.8 does not build on FreeBSD.

Make pandoc compile on FreeBSD with stack

---

data/pandoc.lua
pandoc.cabal
src/Text/Pandoc/Lua.hs
src/Text/Pandoc/Lua/StackInstances.hs
stack.full.yaml
stack.pkg.yaml
stack.yaml
test/Tests/Lua.hs
test/lua/markdown-reader.lua
test/lua/plain-to-para.lua
test/lua/strmacro.lua

Lua filter functions and `Inline` constructors in the `pandoc.lua` module are changed to take the same arguments as those lua functions used for custom writers.  The result is a uniform interface for the lua subsystem.
Example for filtering on `Span`:
``` lua
Span = function(lst, attr)
return pandoc.Span(lst, attr)
end
```
Performance is improved slightly and lua documentation can be generated via `ldoc`.  The only downside is that `pandoc.lua` becomes larger and less simple.

Destructuring lua filter functions

---

src/Text/Pandoc/ImageSize.hs

Read image size of Inkscape SVGs

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3587.md

I want to resolve #3587.
Basic command parsing works, but preunit, value, and unit do not get parsed further (e.g. `\euro` is not translated into `€`). I assume I have to use the function `tok`.  @jgm, can you help me to use it correctly?

Add siunitx Support

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/dots.md

In LaTeX you can use the `\vdots` command outside of the math environment to show vertical dots. This feature is very helpful to show a sequence in a `tabular` environment. 
```latex
\begin{tabular}{|c|}
\hline
start \\
\hline
\vdots \\
\hline
end \\
\hline
\end{tabular}
```
This PR enables that pandoc produces following HTML code:
```html
<table>
<thead>
<tr class="header">
<th style="text-align: center;">start</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">⋮</td>
</tr>
<tr class="even">
<td style="text-align: center;">end</td>
</tr>
</tbody>
</table>
```

Add support for \vdots

---

src/Text/Pandoc/Readers/TWiki.hs

Avoid constructing list of one element ([B.str url]) just to flatten it
back with mconcat.

Simplify linkText in Text.Pandoc.Readers.TWiki

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/hyphenat.md

Many LaTeX documents use the [hyphenat](ftp://ftp.tu-chemnitz.de/pub/tex/macros/latex/contrib/hyphenat/hyphenat.pdf) package. This PR adds support of `\hyp{}`, `\bshyp{}`, `\fshyp{}`, `\dothyp{}`, and `\colonhyp{}` commands.

Add basic support for hyphenat package

---

src/Text/Pandoc/Writers/Muse.hs

Directives at the beginning of documents cannot
span multiple lines so they must not be reflown.

Muse writer: Do not reflow directives

---

src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
src/Text/Pandoc/Readers/Org/Parsing.hs

Extended version of #3604, supplemented with an approach to build the different F monads used in the readers from a single data type.  Changes to the Markdown reader are kept to a minimum.

Created shared F monad functions

---

src/Text/Pandoc/Writers/FB2.hs

I need this when converting from Muse to FB2. Muse uses `#lang` according to its [manual](http://amusewiki.org/library/manual#toc11) and FB2 uses `<lang>` tag, and EPUB writer also uses `lang` metadata, so everything is compatible.

FB2 writer: Add support for "lang" metadata

---

src/Text/Pandoc/Writers/Markdown.hs
test/command/3615.md

Ensure that we do not generate reference links
whose labels differ only by case.
Also allow implicit reference links when the link
text and label are identical up to case.
Closes #3615.

Markdown writer: Case-insensitive reference links.

---

src/Text/Pandoc/Writers/Markdown.hs
test/command/3630.md

fixes https://github.com/jgm/pandoc/issues/3630

Markdown Writer: put space before refLinks, fixes #3630

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/tabularx.md

In LaTeX you can use the `tabularx` environment as an alternative to `tabular` environment. For example:
```latex
\begin{tabularx}{\linewidth}{|b{0.25\linewidth}|c|m{0.25\linewidth}|}
\hline
Column Heading 1
& Column Heading 2
& Column Heading 3 \\
\hline
Cell 1.1 
& Cell 1.2
& Cell 1.3 \\
\hline
Cell 2.1 
& Cell 2.2
& Cell 2.3 \\
\hline
Cell 3.1 
& Cell 3.2
& Cell 3.3 \\
\hline
\end{tabularx}
```
This PR adds support for this environment.

LaTeX: Add support for tabularx environment

---

src/Text/Pandoc/Writers/Markdown.hs
test/command/3619.md

Add rules for ':' and '(', as well as '[' following a LineBreak.
Closes #3619.
Not sure this is the cleanest way to fix it, but it seemed like the simplest.

Markdown writer: Selectively disable shortcut links.

---

src/Text/Pandoc/Writers/Markdown.hs

This fixes the behaviour of `echo '<ul><li>foo</li></ul><ul><li>bar</li><li>baz</li></ul>' | pandoc -f html -t markdown-raw_html | pandoc`

Markdown writer: missing \n

---

data/templates/default.latex

Declare our redefined `\href` robust.

Fix #3651.

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

According to `hyperref` package's [`README.pdf`](http://mirror.jmu.edu/pub/CTAN/macros/latex/contrib/hyperref/README.pdf), page 22, `hyperref` package
should be loaded after `parskip` package.

LaTeX: Load `parskip` before `hyperref`.

---

src/Text/Pandoc/Readers/LaTeX.hs
test/latex-reader.native

Latex has very good support for [Horizontal Spacing](https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing). Pandoc misses this support. Following should be converted:
```latex
e.\,g.
```
Following html code contains the [six-per-em space](https://en.wikipedia.org/wiki/Whitespace_character#Unicode)
```html
<p>e. g.</p>
```

Added support for horizontal spacing in LaTeX

---

src/Text/Pandoc/Readers/Txt2Tags.hs

space parses '\n', while spaceChar parses only ' ' and '\t'

Txt2Tags parser: newline is not indentation

---

data/templates/default.latex

Attempt to fix issue #3660 
In `template.latex`: reordered `lang` variable handling to immediately before `bidi`, in order to avoid errors related to `bidi` being called too early, as `bidi` is loaded by `polyglossia` for RTL languages as described in #3660.

modified template.latex to fix XeLaTex being used with tables

---

src/Text/Pandoc/App.hs
src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/Txt2Tags.hs
src/Text/Pandoc/SelfContained.hs
src/Text/Pandoc/Shared.hs
src/Text/Pandoc/Writers/ConTeXt.hs
src/Text/Pandoc/Writers/DokuWiki.hs
src/Text/Pandoc/Writers/FB2.hs
src/Text/Pandoc/Writers/Haddock.hs
src/Text/Pandoc/Writers/ICML.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/Markdown.hs
src/Text/Pandoc/Writers/MediaWiki.hs
src/Text/Pandoc/Writers/RST.hs
src/Text/Pandoc/Writers/Texinfo.hs
src/Text/Pandoc/Writers/ZimWiki.hs

MediaWiki wikis frequently have pages with names like `User:John` which
were interpreted as URIs, thus turning internal links into global links.
This is prevented by also checking whether the scheme of a URI is
frequently used (i.e. is IANA registered or an otherwise well-known
scheme).

Mediawiki writer: treat links with unknown schemes like wikilinks

---

src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/TWiki.hs
src/Text/Pandoc/Readers/Textile.hs
test/Tests/Readers/Org.hs

This PR fixes parsing of `org-ref` cite-keys that are followed by punctuation: Before, the citation key in 
> From cite:pandoc: ...
would incorrectly be parsed as `pandoc:`. This changes `orgRefCiteKey` to ignore all special characters at the end of a cite-key and the key in the example is read as `pandoc` without the colon at the end.
To do so, I also changed `many1Till p end` to fail if not at least one occurrence of `p` would be read before `end` succeeds. I think this only has an effect if `p` is a prefix of `end`, so this should make it more consistent.
But if the current behaviour of `many1Till` is actually as expected, I will make a separate `many1Till'` and leave the original untouched.
The zip file [org-inline.zip](https://github.com/jgm/pandoc/files/1032690/org-inline.zip) …

Org: Fix reading of citations before punctuation

---

src/Text/Pandoc/Readers/Odt/Arrows/State.hs
src/Text/Pandoc/Readers/Odt/Arrows/Utils.hs
src/Text/Pandoc/Readers/Odt/ContentReader.hs
src/Text/Pandoc/Readers/Odt/Generic/Fallible.hs
src/Text/Pandoc/Readers/Odt/Generic/Utils.hs
src/Text/Pandoc/Readers/Odt/Generic/XMLConverter.hs
src/Text/Pandoc/Readers/Odt/StyleReader.hs

The ODT reader contained a lot of general code useful for working with
arrows. However, a lot of these utils weren't used and are hence removed.
It might make sense to keep this dead code around if the ODT reader is to
be extended or reworked in the near future, but it's probably cleaner to revert 
this commit selectively if parts of the code become needed again.
cc @MarLinn

Odt reader: remove dead code

---

src/Text/Pandoc/Writers/Docx.hs

Hi, I don't know haskell so possibly this is wrong, but DOCX stores keywords in <cp:keywords> in core.xml, and this should be easy to add from the pandoc metadata (I copy and paste the author code). As far as I can tell (no clear documentation, just a few refs), keywords should be separated with a comma.

Add keywords metadata to docx core.xml document properties

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/latex-fontawesome.md

This PR adds support for some fontawesome commands. 
Check: ✓ 
Close: ✗

Support for \faCheck and \faClose

---

pandoc.cabal

GHC 8.2 is very likely to ship with process-1.6.0.0
and time-1.8.0.1.
Consult:
https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory

Relax time and process in preparation for GHC 8.2

---

pandoc.cabal
src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs
test/test-pandoc.hs
trypandoc/index.html

I have created a basic Muse reader.  It supports headings, inline markup and footnotes, but no tables and lists. It is far from full markup support, but it satisfies my needs so I plan to continue development slowly from now on. Hope it gets merged.

[WIP] Add Muse reader

---

src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs

Found a bug by testing on Text::Amuse `lists.muse` testcase, now `pandoc -f muse -t muse` successfully passes it.

Muse reader: fix list item continuation parsing

---

src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs

Do not parse 3 dashes as horizontal rule and allow whitespace after rule

Muse reader: fix horizontal rule parsing

---

src/Text/Pandoc/Readers/Vimwiki.hs
trypandoc/index.html

- updated comments in Vimwiki.hs to reflect current status of
implementation
- added vimwiki to trypandoc
I haven't found a way to test `trypandoc/index.html`. When I open this webpage locally and write something in say markdown and click "convert" nothing happens. Anyway I've added vimwiki to the "from" list.

Vimwiki reader: minor updates

---

src/Text/Pandoc/Readers/Muse.hs

This is just to avoid unnecessary parsing

Muse reader: do not parse blocks inside comments

---

src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs

Take only first line indentation into account
and do not start new paragraph on indentation change.

Muse reader: debug indented paragraph support

---

src/Text/Pandoc/Readers/HTML.hs
test/Tests/Readers/HTML.hs

Doing the reverse transformation in the HTML writer, and probably other writers too, might make sense, but this is a very good semantic match as it is.

HTML reader: parse <main> like <div role=main>.

---

data/templates/default.latex

Avoids an options clash when loading a package (e.g. `tufte-latex`) that uses `hyperref` settings different from those in the template (introduced in <https://github.com/jgm/pandoc-templates/commit/feffd7c64abab863abd3f6458d1c445d6bfe7fc4>).
This replaces <https://github.com/jgm/pandoc-templates/pull/230>.

Fix hyperref options clash

---

MANUAL.txt
man/pandoc.1
src/Text/Pandoc/Writers/HTML.hs

The reason behind this pull request is that if I deliver my presentation over https, the browsers (tested on Safari and Chrome) will block the access of non-https files like the http css and js used in slidy.
Edit: although `slidy-url` can be used to change this manually, but I think defaulting to https is good practice enough for a pull request.

slidy uses https instead of http

---

data/templates/default.docbook5
test/writer.docbook5

$lang$ is needed for non-English documents.
Many articles and books have a $subtitle$.

forward $lang$ and $subtitle$ attributes

---

src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs

This behavior is compatible to Amusewiki

Muse reader: do not allow closing tags with EOF

---

INSTALL.md
MANUAL.txt
RELEASE-CHECKLIST
RELEASE-CHECKLIST.md
macos/make_macos_package.sh
macos/uninstall-pandoc.pl
man/pandoc.1
stack.full.yaml
windows/Pandoc-en-us.wxl

fix commit c96b64e
This commit finishes remaining osx to macOS change, as well as replacing MacOS with macOS.
The reason for the later one is because the "correct" casing of macOS is like that. Apple styles it to looks like iOS, watchOS, tvOS, etc. And unfortunately they all start with a lowercase letter, making propercasing (or even title-casing) odd.
Edit: I add 1 more commit to fix the casing of Linux, UNIX, and Windows when they are addressed as the name of the OSes. (I noticed them when they are addressed alongside macOS.)

Name change OSX -> macOS

---

MANUAL.txt

- grid tables with row spans (variable number of
columns per row) are not supported
- see discussion: https://groups.google.com/forum/#!topic/pandoc-discuss/r9fAeeV3dSw
I think the formatting makes sense (h5 section, link to example grid tables that would not work), but am happy to change things upon request.
As a side note, I couldn't actually figure out how to build the full website and make sure the real formatting worked as expected.  I just used
```console
$ pandoc -i MANUAL.txt -t html -o test.html
```
Sorry for my ignorance, how does the full website get built?

add documentation of limitations of grid tables

---

src/Text/Pandoc/Readers/LaTeX.hs
test/Tests/Readers/LaTeX.hs

This is not bug-for-bug compatible: it barfs on weird input, whereas biblatex will accept just about anything that starts with a digit and several things that don't. Is that acceptable?
I had a go at bug-for-bug compatibility, but the implementation was getting a little bit silly. Here are the test cases that I cut out when I gave up:
```
, "internal spaces" =:
"\\RN{ 2 3 }" =?>
para (str "II3")
, "internal spaces many words" =:
"\\RN{5 hello there}" =?>
para (str "V" <> str "HELLO" <> space <> "THERE")
, "newlines" =:
"\\RN{\n15\n17\n}" =?>
para (str "XV17")
, "number then space then non-number" =:
"\\Rn{5 HELLO}" =?>
para (str "vHELLO")
, "number then non-number, non-number gets upcased by RN" =:
"\\RN{4hello}" =?>
para (str "IVHELLO")
, "internal command" =:
"\\Rn{4\\textit{8}}" =?> …
```

LaTeX reader: RN and Rn, from biblatex

---

data/templates/default.latex

...by using the `luatexja-fontspec` and `luatexja-preset` packages. Use
existing `CJKmainfont` and `CJKoptions` template variables. Add
`luatexjafontspecoptions` for `luatexja-fontspec` and `luatexjapresetoptions`
for `luatexja-preset`.
This resolves jgm/pandoc-templates#227.

Allow setting Japanese fonts when using LuaLaTeX

---

src/Text/Pandoc/Parsing.hs
test/Tests/Readers/RST.hs

Test is checked to be consisted with http://rst.ninjs.org/

RST reader: treat preceding and following blank lines equally in line blocks

---

pandoc-template-mode.el
tools/pandoc-template-mode.el

This `pandoc-template-mode` adds highlighting of Pandoc template preprocessor directives to help with their editing.

Add simple Emacs mode to help with Pandoc templates editing.

---

data/pandoc.lua
doc/ldoc.ltp
doc/lua-filters.md

Append docs generated from the `data/pandoc.lua` code to the lua filters documentation.
Closes: #3608

Lua module documentation

---

MANUAL.txt
data/templates/default.latex
src/Text/Pandoc/Writers/LaTeX.hs
test/writer.latex
test/writers-lang-and-dir.latex

The textcomp package allows pdfLaTeX to parse `€` directly, making the \euro command unneeded. Closes #3801.

Write euro symbol directly in LaTeX

---

src/Text/Pandoc/Readers/Muse.hs
test/Tests/Readers/Muse.hs

Previously code was not allowed to be followed by comma,
and emphasis was allowed to be followed by letter.

Muse reader: allow inline markup to be followed by punctuation

---

MANUAL.txt
data/bash_completion.tpl
src/Text/Pandoc/App.hs
src/Text/Pandoc/Error.hs
src/Text/Pandoc/Options.hs
src/Text/Pandoc/PDF.hs

Rename `--latex-engine` to `--pdf-engine` and add support for `weasyprint` and `prince`, in addition to `wkhtmltopdf`
closes #3906 
Three remarks/TODOs.
1. In `PDF.hs#html2pdf`: could we use "program - html2pdf.pdf" to read from stdin instead of using a tempFile? All three HTML-to-PDF-engines support it.
2. It's still a bit counter-intuitive that you have to specify a writer when not using LaTeX, e.g. see:
$ pandoc -o output.pdf --pdf-engine=weasyprint
pdf-engine weasyprint is not compatible with format latex, please use `-t html`
I guess we could change the `App.hs#defaultWriterName` function to depend on the pdf-engine. Then the only question is: why can't I also use `context` and `pdfroff` with `--pdf-engine`?
3. TODO: research and implement best approach to [math-handling for …

Support for `weasyprint` and `prince`

---

src/Text/Pandoc/App.hs

This triggers `Rscript` when encountering a filter ending in `*.R` or `*.r`.
#3940

Support R filters #3940

---

Makefile
doc/lua-filters.md
tools/update-lua-docs.lua

The pandoc module documentation in doc/lua-filters.md was automatically
generated from `data/pandoc.lua`.  A make target is provided which uses
a lua filter to update the documentation.

Provide make target to update lua module docs

---

data/pandoc.lua
src/Text/Pandoc/Lua/PandocModule.hs

The pipe command is wrapped in a lua function, throwing a lua error if the command returns with an error. A wrapper is needed as Haskell functions exposed to lua may not throw lua errors due to limitations of hslua.
The error handling is written such that a table can be returned as an error object in the future. This is potentially useful when finer control is required while catching the error in lua code. Current limitations of hslua require error objects to be strings.

Lua pipe wrapper

---

data/templates/default.dzslides

Otherwise they won't show up in current version of firefox/chromium.
https://greut.github.io/slides-devweb/00-presentation.html

Load Google Font using HTTPS by default

---

src/Text/Pandoc/Writers/Docx.hs

Fixes #3901 by checking for the evenAndOddHeaders mark in the
reference doc, and copying it to the resulting docx if present.

docx writer - activate evenAndOddHeaders from reference doc

---

src/Text/Pandoc/Writers/FB2.hs

Previously writer produced one paragraph with `<empty-line/>` elements,
which are not allowed inside `<p>` according to FB2 schema.
[reStructuredText Markup Specification](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#line-blocks) suggests using line blocks for verse and Muse reader parses <verse> as LineBlocks, so it makes sense to convert LineBlocks to `<poem>` in FB2 writer.
Also Linux FBReader has problems parsing current output and stops parsing `<p>` after first `<empty-line/>`. It was "fixed" in mobile FBReader at my [request](https://github.com/geometer/FBReaderJ/issues/465), but now that I look at XML schema it looks like it is a bug in pandoc. And with new output we get actual line breaks instead of empty lines (two line breaks) on display.

FB2 Writer: format LineBlock as poem

---

src/Text/Pandoc/Writers/Markdown.hs

this should fix https://github.com/jgm/pandoc/issues/3790.

markdown writer: always write bracketed_spans' attributes

---

src/Text/Pandoc/Readers/LaTeX.hs
test/Tests/Readers/LaTeX.hs

Fixes things like this:
```
\includegraphics[width=12cm, height = 5cm]{foo.png}
```

Latex reader: Skip spaces in image options

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/lettrine.md

Lettrine, e.g. as in https://tex.stackexchange.com/a/52744/33952
Not sure what's up with all the empty spans (this is something we have in https://github.com/jgm/pandoc/issues/3488 as well).
I was thinking of adding a class to the span, but this can probably be done just as well using CSS pseudo-elements like `p::first-letter`.

LaTeX Reader: support \lettrine

---

src/Text/Pandoc/Readers/Creole.hs
test/Tests/Readers/Creole.hs

I found and fixed a problem with my creole parser: when there was trailing white space in list items, the next item was not correctly detected.
In addition I added another test for no-wiki (verbatim code) blocks, to ensure they are not affected by an similar problem (they are not).  And made some minor corrections of typos and code formatting...

Creole Reader: fix lists with triling white space

---

pandoc.cabal
test/Tests/Writers/FB2.hs
test/test-pandoc.hs

We already have some FB2 tests in `test/Tests/Old.hs` with files in `test/fb2/`.
This is an attempt to add new style tests which are IMO easier to maintain than lots of files which all have to be changed if, for example, boilerplate (added by `fb2` function here) is changed.

Add new style FB2 tests

---

src/Text/Pandoc/Writers/FB2.hs
test/writer.fb2

Previously bullet lists interacted in odd way with ordered lists.
For example, bullet lists nested in ordered list had incorrect
indentation. Besides that, indentation with spaces is not rendered
by FBReader and fbless. To avoid this problem, bullet lists are
indented by appending bullets to marker just the same way it is
done for ordered lists.

FB2 writer: make bullet lists consistent with ordered lists

---

data/epub.css
data/templates/default.s5
src/Text/Pandoc/Writers/HTML.hs
test/s5-basic.html
test/s5-fancy.html
test/writer.html4
test/writer.html5

see #3556
I went through the HTML writer and corrected those I could find. However, I left `smallcaps` and `literatehaskell` as is, since it feels like that could also be one word, or what do you think?

HTML Writer: consistently use dashed class-names

---

MANUAL.txt

Add paragraph at end of `Extension: fenced_divs` section to clarify that the actual number of colons in fences is irrelevant. (See issue #4037).

Manual: Edit "Extension: fenced_divs"

---

INSTALL.md

Some links were outdated. Link to the package search page if no separate page for pandoc exists, and use HTTPS where possible.
All other links have been clicked once and deemed okay.

INSTALL.md: update links to Linux distributions

---

INSTALL.md

Since Pandoc v2.0 the xz instead of the gz format is used for the data archive inside the deb (`data.tar.xz`) and the old commands to extract a gzip archive fail.

update commands to extract deb archive on Linux

---

src/Text/Pandoc/Options.hs
src/Text/Pandoc/Readers/CommonMark.hs

`enabled` from CommonMark.hs was duplicate of isEnabled from Options.hs

Extend isEnabled to WriterOptions to remove code duplication

---

pandoc.cabal
src/Text/Pandoc/Lua.hs
stack.pkg.yaml
stack.yaml
test/Tests/Lua.hs
test/lua/uppercase-header.lua

The `text` module is preloaded in lua. The module contains some UTF-8
aware string functions, implemented in Haskell.  The module is loaded on
request only, e.g.:
text = require 'text'
function Str (s)
s.text = text.upper(s.text)
return s
end

Lua filters: preload text module

---

data/pandoc.lua
test/Tests/Lua.hs
test/lua/attr-test.lua

Attribute lists are represented as associative lists in Lua. Pure
associative lists are awkward to work with. A metatable is attached to
attribute lists, allowing to access and use the associative list as if
the attributes were stored in as normal key-value pair in table.
Note that this changes the way `pairs` works on attribute lists. Instead
of producing integer keys and two-element tables, the resulting iterator
function now returns the key and value of those pairs.  Use `ipairs` to
get the old behavior.
Warning: the new iteration mechanism only works if pandoc has been
compiled with Lua 5.2 or later (current default: 5.3).
Closes: #4071

data/pandoc.lua: enable table-like behavior of attributes

---

pandoc.cabal

Tested on GHC-8.2 with [`http-types-10.0`](http://hackage.haskell.org/package/http-types-0.10).

Relax `http-types` dependency.

---

src/Text/Pandoc/App.hs

The `Generic` JSON instances for `Text.Pandoc.App.Opt` seem to tickle a
particulary bad quadratic complexity case (Generics complexity is worse
than quadratic with respect to the number of fields in the datatype).
This is with GHC-8.2.1, I didn't test it using 8.0 but I assume it is
similar.
Using `Generic`, compilation of the `Text.Pandoc.App` module takes
minutes and often gets killed due to out of memory on slower machines
with "only" 8GB of accessible memory.  This is particularly annoying to
me since it means I cannot build pandoc on Travis.
TemplateHaskell is a little uglier, but the module seems to compile
within a few seconds, and compilation doesn't take more than 1GB of
memory.
Should I also change the other JSON instances throughout the codebase
for consistency?

Change JSON instances for Opt to TemplateHaskell

---

src/Text/Pandoc/Shared.hs

also parse two-digit days, e.g. "April 20, 2017"
replace some `%d` with `%e`, from [docs](https://www.stackage.org/haddock/lts-8.21/time-1.6.0.1/Data-Time-Format.html#v:formatTime):
> `%d`: day of month, 1-padded to two chars, 01 - 31
> `%e`: day of month, space-padded to two chars, 2 - 31
this was brought up in #4086

make normalizeDate more forgiving

---

data/List.lua
data/pandoc.lua
pandoc.cabal
src/Text/Pandoc/Lua/PandocModule.hs

The List module is automatically loaded, but not assigned to a global
variable. It can be included in filters by calling `List = require
'List'`.
Lists of blocks, lists of inlines, and lists of classes are now given
`List` as a metatable, making working with them more convenient. E.g.,
it is now possible to concatenate lists of inlines using Lua's
concatenation operator `..` (requires at least one of the operants to
have `List` as a metatable):
function Emph (emph)
local s = {pandoc.Space(), pandoc.Str 'emphasized'}
return pandoc.Span(emph.content .. s)
end
Closes: #4081

Add basic lua List module

---

doc/epub.md

Because `--smart/-S` has been removed.
Maybe ` -f markdown+smart` shoud also be added?

Delete removed -S option from command in epub.md

---

pandoc.cabal
src/Text/Pandoc/Writers/JATS.hs
test/Tests/Writers/JATS.hs
test/test-pandoc.hs
test/writer.jats

Support writing `<fig>` and `<table-wrap>` elements with `<title>` and
`<caption>` inside them by using Divs with class set to on of
fig, table-wrap or cation.  The title is included as a Heading
so the constraint on where Heading can occur is also relaxed.
Also leaves out empty alt attributes on links.

fig, table-wrap & caption Divs for JATS writer

---

src/Text/Pandoc/Writers/JATS.hs
test/tables.jats

If the contents are single `Plain` block then do not wrap them with
a <p> element.

JATS writer: Make <p> optional in <td> and <th>

---

MANUAL.txt

We've started using extensions in other formats than markdown more and more recently. However from the questions I've seen, user awareness hasn't followed suit. I think we should therefore update the documentation accordingly.
The following was the best I could come up with...

MANUAL introduce dedicated extensions section

---

src/Text/Pandoc/Readers/HTML.hs
test/command/4183.md

HTML Reader: be more forgiving about figcaption

---

src/Text/Pandoc/Extensions.hs

In Pandoc v2 using --section-divs and -t html results in <section>s, not <div>s, by default, as was the case for v1.9.
This change to the Manual emphasizes that you must use -t html4 if you want divs, otherwise you get sections.

clarify default html output for --section-divs

---

src/Text/Pandoc/Writers/ODT.hs
src/Text/Pandoc/Writers/OpenDocument.hs
test/writer.opendocument

This commit greatly improves the formatting of formulas in ODT documents.
Formulas are wrapped in a `span` element. Two formula styles are generated. One for display math and one for inline math.
An inline math formula is marked as text. See "Text mode" in [Math Guide](https://wiki.documentfoundation.org/Documentation/Publications#LibreOffice_Math_Guide).
Display math is placed in a paragraph of its own, which is centered. A new paragraph style is generated for each formula.

improve formatting of formulas in OpenDocument

---

MANUAL.txt

This structures the `Description` section and streamlines some of the wording, which was sometimes outdated.

MANUAL.txt simplify and add more structure

---

src/Text/Pandoc/Writers/Docx.hs

docx output has two bugs:
- if a subtitle is defined, the subtitle was appended to the title string (output as pStyleM "Title" paragraph), and in addition to that written as new paragraph (pStyleM "Subtitle") after the title. This leads to double subtitle. As the subtitle is added as a separate paragraph, there is no need to append it to the title
- Word 2016 seems to default to a header format in tables, if there is no "firstRow" definition. setting it explicitly to "0" is compatible with Word 2013 and fixes it for Word 2016

fixes for docx writer

---

doc/lua-filters.md
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/Filter.hs
src/Text/Pandoc/Filter/Json.hs
src/Text/Pandoc/Filter/Lua.hs
src/Text/Pandoc/Filter/Path.hs
src/Text/Pandoc/Lua/Module/Utils.hs
src/Text/Pandoc/Lua/Packages.hs

Allow running JSON filters from within Lua.  This is useful when only a temporary sub-document should be processed. E.g., [chapter wise bibliography](https://groups.google.com/d/topic/pandoc-discuss/N4Hmr8wErBs/discussion) could be created using this filter.
``` lua
local List = require 'pandoc.List'
local utils = require 'pandoc.utils'
-- flatten should probably be provided by pandoc.utils
local function flatten (lst)
local res = List:new{}
for i, el in ipairs(lst) do
if el.t == 'Sec' then
res[#res + 1] = pandoc.Header(el.level, el.label, el.attr)
res:extend(flatten(el.contents))
else
res[#res + 1] = el
end
end
return res
end
function Pandoc (doc)
local res = List:new{}
local sections = utils.hierarchicalize(doc.blocks)
for _, sec in ipairs(sections) do
-- create temporary sub-documents …
```

Run JSON filters from Lua filters

---

src/Text/Pandoc/Readers/HTML.hs

Rather than take user input, and place a "0." in front, actually
calculate the percentage to catch cases where small column sizes are
needed.
[Example File and Results](https://gist.github.com/n3fariox/c8b3ef2e23d81479c8bbce0db1276411)

HTML reader: Fix col width parsing

---

src/Text/Pandoc/Writers/LaTeX.hs

I get an error when I've got a backticked `&` in my document and `--listings` enabled.
```
! Improper alphabetic constant.
<to be read again> 
\unskip 
l.69 \passthrough{\lstinline!&!}
```
Strangely, it only seems to happen inside tables like
```
col1 col2
---- ----
`&`  abc
```
Also see #4111.

LaTeX writer: escape & in lstinline

---

data/templates/default.ms

I believe the title is self-describing. Should I also write some documentation, since this variable, and some others mentioned in the template aren't explicitly found in the manual?

Ms writer: Added papersize variable

---

src/Text/Pandoc/Writers/ConTeXt.hs
test/Tests/Writers/ConTeXt.hs
test/tables.context

ConTeXt writer: xtables: correct wrong usage of caption

---

src/Text/Pandoc/Writers/ConTeXt.hs
test/Tests/Writers/ConTeXt.hs
test/command/3968.md
test/writer.context
test/writers-lang-and-dir.context

Fixes #2609.
This PR introduces the new-style section headings.
```latex
\section[my-header]{My Header} -> \section[title={My Header},reference={my-header}]
```
On top of this, the ConTeXt writer now supports the `--section-divs` option to write sections in the fenced style
```latex
\startsection[title={My Header},reference={my-header}]
contents...
\stopsection
```
@pmazaitis @ousia @DaveJarvis

ConTeXt writer: new section syntax and --section-divs

---

default.nix

A month ago bdb911550c2894925be6893a5d93fca484448dd4 bumped `hslua` to version 0.9.5, but the change was not incorporated into `default.nix`. Consequently, `nix-build` fails while complaining about conflicting versions. Updating to a more recent nixpkgs channel resolves this, and the previously specified overrides are no longer necessary.
The revision was taken from [nixos.org/channels/nixpkgs-unstable/git-revision](nixos.org/channels/nixpkgs-unstable/git-revision) and the sha256 hash can be double-checked by running `nix-prefetch-git https://github.com/nixos/nixpkgs.git --rev 42b9b8f7c8687cb26e69c3559e0e1346fb0e680f` and inspecting the output.

Update default.nix to current nixpkgs-unstable for hslua-0.9.5

---

INSTALL.md

Since I was using Stack from Ubuntu repositories, [I've lost some time](https://stackoverflow.com/questions/48595711/error-building-pandoc-error-in-ghc-options-failed-to-parse-field-ghc-opt/48595712#48595712) trying to figure out why pandoc was not building. I believe mentioning the version can be useful to other developers. (Now, if you don't think this is a relevant question, that's ok as well, I just thought I needed to suggest the change.)

INSTALL.md: mentioning Stack version.

---

src/Text/Pandoc/ImageSize.hs
src/Text/Pandoc/Writers/Docx.hs
src/Text/Pandoc/Writers/Powerpoint/Output.hs

ref #3798
Correct aspect ratio for *.emf files when exporting to docx. There are two issues however unrelated to this PR:
1. If using multiple of the same image in a docx, the docx will resize every image (not just .emf) to the size of the first image. The size descriptions of the other copies are ignored. (#3930)
2. .emf files exported by Inkscape are non-compliant to the specification of emf, so don't use these images for testing. 
The only emf files I could find that weren't generated by Inkscape were included by default on windows.

EMF Image size support

---

MANUAL.txt
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Readers/Docx.hs
test/Tests/Readers/Docx.hs
test/docx/custom-style-no-styles.native
test/docx/custom-style-with-styles.native

As discussed on #1843:
We still resolve dependent styles, but we optionally wrap elements in div/span tags derived from paragraph/character style names. This is controlled by `--verbose-docx` which defaults to off.
~~~
$ pandoc test/docx/german_styled_lists.docx -t markdown
-   One level of the list.
-   Second level of the list.
-   Next level of the list
-   Back to the top level.
~~~
~~~
$ pandoc --verbose-docx test/docx/german_styled_lists.docx -t markdown
-   ::: {.AufzhlungStrich}
One level of the list.
:::
-   ::: {.AufzhlungStrich}
Second level of the list.
:::
-   ::: {.AufzhlungStrich}
Next level of the list
:::
-   ::: {.AufzhlungStrich}
Back to the top level.
:::
~~~

RFC: Verbose docx

---

src/Text/Pandoc/Writers/DokuWiki.hs

After fixing #4313, I felt confident enough to rewrite `backSlashLineBreaks` to be more readable and more efficient. Behaviour should be the same as `backSlashLineBreaks . vcat` previously.
Maybe @jkr can have a quick look, just to be sure?

DokuWiki writer: rewrite backSlashLineBreaks

---

data/templates/default.latex
test/writers-lang-and-dir.latex

This avoids option clash when `polyglossia` loads it first and then it is loaded again for XeLaTeX when `latex-dir-rtl` defined.
This fixes `Option clash for package bidi` issue observed in #4355.

Provide `bidi` package's option using `\PassOptionsToPackage`.

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3587.md

Add support to parse unit string of \SI command

---

MANUAL.txt

The documentation states that the target format name should match the output format, which isn't the case for `docx`/`openxml`.
This PR adds a remark and a frequently requested example (inserting a pagebreak in docx output) to the documentation.

Add example for raw docx blocks

---

doc/lua-filters.md

Fixes Macro Replacement example filter in lua-filters doc. Fixed by copying elements from MetaInline (with table.unpack) instead of storing the MetaInline element directly.

Fix example in lua-filters docs. Fixes #4459

---

src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Readers/DocBook.hs
src/Text/Pandoc/Readers/EPUB.hs
src/Text/Pandoc/Readers/JATS.hs
src/Text/Pandoc/Readers/MediaWiki.hs
src/Text/Pandoc/Readers/OPML.hs
src/Text/Pandoc/Readers/TWiki.hs
src/Text/Pandoc/Readers/TikiWiki.hs
src/Text/Pandoc/Templates.hs
src/Text/Pandoc/Writers/ICML.hs

Removed most unused extensions from the modules in the src directory. This has been done using the OrganizeExtensions refactoring of the Haskell-Tools framework.

Removed unused extensions

---

MANUAL.txt
data/templates/default.latex

Hi,
This PR implements https://github.com/jgm/pandoc/pull/4242#discussion_r163044697 and supersedes #4242 .
I also add `pgfpages` package which is very common when using beamer, and required for using `show notes on second screen`, the target case of `beameroption`.
I'm closing #4242 as soon as this PR is opened.

Add -V beameroption variable

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/sloppypar.md

The `sloppypar` environment is used to tell LaTeX to adjust word spacing less strictly. While parsing with the extension `+raw_tex` `sloppypar` is parsed as `RawBlock`. However, pandoc should threat `sloppypar` not as `RawBlock` because it has no effect on writers.

LaTeX reader: parse sloppypar environment

---

src/Text/Pandoc/Writers/CommonMark.hs
test/command/4527.md

CommonMark writer: correctly ignore LaTeX raw blocks when not raw_tex

---

MANUAL.txt

These are two related commits, both changing the input/output formats documentation in the MANUAL.
The first, consolidates the list of input/output formats in one place (namely, the options). There were a couple of formats missing there. Also, my hope is that people will now read the part of the intro about how pandoc works with the AST etc., if they don't have to scroll over the looong list of formats first.
The second commit uses the unordered list for the formats instead, and orders them alphabetically. This makes it much easier to read, at the expense of taking a bit more space (but scrolling is free on computers...).

MANUAL: consolidate input/output format documentation

---

pandoc.cabal

without these flags i get errors similar to those described in #4130 when trying to run the benchmarks (ubuntu 16.04 LTS)
```
pandoc (4581)*$ stack bench
pandoc-2.1.4: unregistering (local file changes: pandoc.cabal)
pandoc-2.1.4: configure (lib + exe + bench)
Configuring pandoc-2.1.4...
pandoc-2.1.4: build (lib + exe + bench)
Preprocessing library for pandoc-2.1.4..
Building library for pandoc-2.1.4..
Preprocessing benchmark 'benchmark-pandoc' for pandoc-2.1.4..
Building benchmark 'benchmark-pandoc' for pandoc-2.1.4..
Linking .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/benchmark-pandoc/benchmark-pandoc ...
/home/francesco/pandoc/rts/posix/OSThreads.c:137:0: error:
error: undefined reference to 'pthread_create'
/home/francesco/pandoc/rts/posix/OSThreads.c:139:0: error:
error: …
```

use the `-threaded` GHC flag when building benchmarks, related to #4130

---

data/templates/default.revealjs

Provide alternate variable that may be used with other presentation formats.

Adding background-image variable to reveal.js template

---

src/Text/Pandoc/Writers/RST.hs
test/Tests/Writers/RST.hs
test/writer.rst

after the refactoring we can apply transformations to inlines in a bottom-up direction, thus it becomes possible to transform inlines flattening them according to the the readability criteria discussed in #4368

flatten nested inlines following readability criteria, closes #4368

---

src/Text/Pandoc/Writers/LaTeX.hs

Don't delimit `\lstinline` with characters that are normally escaped in LaTeX, specifically those which Pandoc already needs to escape, like `&` and `_`:
https://github.com/jgm/pandoc/blob/6dcb9744237be713f4ef94017a6b68fc0cfddb73/src/Text/Pandoc/Writers/LaTeX.hs#L1018
This avoids "undefined control sequence" issues with the `\passthrough` command encountered in https://github.com/laboon/ebook/issues/139, and follows up on #4111 and #4271.

LaTeX writer: Update \lstinline delimiters.

---

src/Text/Pandoc/Writers/RST.hs
test/Tests/Writers/RST.hs

this fixes a bad error introduced with #4554

RST writer: preserve empty inline parents in flatten

---

data/templates/default.html5

The HTML produced by this template may not be well-formed in an XML sense due to this line:  \<link rel="stylesheet" href="$css$"\>
So by making the link element self-closing the HTML produced by the template will be polyglot.

Make template polyglot

---

src/Text/Pandoc/Class.hs
src/Text/Pandoc/Logging.hs

if we do not catch these errors, any malformed entry in a media bag
could cause the loss of a whole document output. an example of
malformed entry is an entry with an empty file path.
for the error logging i looked for a way to preserve information from the IO error. An IO error like `media/.: openBinaryFile: inappropriate type (Is a directory)` can give helpful troubleshooting information to the users in case of errors in a path or problems with permission

catch IO errors when writing media files, closes #4559

---

MANUAL.txt

closes #2281
I couldn't find the relevant code in https://www.stackage.org/haddock/lts-11.7/doctemplates-0.2.2.1/src/Text.DocTemplates.html
- Is this list of truthy values exhaustive or should it be defined in terms of which things are _not_ truthy?
- Does the YAML standard define types? Or are they just falling back on the JSON type definitions? Should we mention this here?
- How come `--metadata x=no` is parsed as a YAML boolean `false`? Is that specific to pandoc or a YAML thing?

MANUAL: clarify truthiness in template variables

---

src/Text/Pandoc/Extensions.hs

According to https://github.com/jgm/pandoc/issues/3703, `Ext_east_asian_line_breaks` will not take effect when readers/writers are called as libraries. And I think this is a nice solution for universal conversion with `Ext_east_asian_line_breaks`. However, I have spent hours to find out why my reader options don't take effect, until discover your discussion in https://github.com/jgm/pandoc/issues/3703. So I think it would be great if we add some description about the limitation.

emphasize Ext_east_asian_line_breaks will not take effect when called as libraries

---

src/Text/Pandoc/App.hs
src/Text/Pandoc/PDF.hs

regression: path to --pdf-engine works again

---

MANUAL.txt

https://citationstyles.org/styles/ will give a 404 error. https://citationstyles.org/authors/ should be the new link with the same content.

README: Citation styles link updated

---

MANUAL.txt
src/Text/Pandoc/Writers/LaTeX.hs

As noted [here](https://tex.stackexchange.com/a/49805) ([beamer commit here](https://github.com/josephwright/beamer/commit/ff70090f36b631667b472cfe675fc3514fe46f7e)), `noframenumbering` is an undocumented, but long existing option to disable frame numbering for a particular slide. This is useful to avoid numbering backup slides (the natural approach of defining an appendix doesn't work due to the issue described [here](https://github.com/jgm/pandoc/issues/4403)). This PR makes the trivial change to support this option by adding it to the available `frameoptions`.
(I also noted the "standout" option in the manual while adding "noframenumbering")
Thanks for developing such an excellent tool!

Beamer: Allow "noframenumbering" option

---

pandoc.cabal

`prettyPrintParseException` was added to yaml-0.8.11:
https://hackage.haskell.org/package/yaml-0.8.30/docs/src/Data.Yaml.Internal.html#prettyPrintParseException
Noticed by tgbugs in https://github.com/gentoo-haskell/gentoo-haskell/issues/725
Reported-by: tgbugs
Bug: https://github.com/jgm/pandoc/issues/4726
Bug: https://github.com/gentoo-haskell/gentoo-haskell/issues/725
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

pandoc.cabal: fix lowe yaml bound up to 0.8.11

---

src/Text/Pandoc/Readers/TikiWiki.hs
test/command/4722.md
test/tikiwiki-reader.native

- remove trailing Space from list items
- also parse lists that have no space after list marker (fixes #4722)
@rlpowell what do you think?

TikiWiki reader: improve list parsing

---

src/Text/Pandoc/Emoji.hs
src/Text/Pandoc/Readers/CommonMark.hs
src/Text/Pandoc/Readers/Markdown.hs
test/Tests/Readers/Markdown.hs
test/command/4743.md
test/command/gfm.md

This is the alternative implementation as discussed in issue #4743 that instead does the wrapping unconditionally on the reader side  (#4744 is the pull request that did it in html writer)

Wrap emojis in span nodes

---

MANUAL.txt

Hopefully, this wording is clearer? There was at least [someone](https://github.com/jgm/pandoc/issues/4782) thinking `gfm` and `markdown_github` were synonyms. And a few other people asking why `gfm` doesn't support certain extensions.

MANUAL: clarify gfm vs markdown_github

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/Utils.hs
src/Text/Pandoc/Shared.hs
test/Tests/Lua.hs
test/lua/test-pandoc-utils.lua

Exposes a function converting which flattenes a list of blocks into a
list of inlines. An example use case would be the conversion of Note
elements into other inlines.

Lua Utils module: add function blocks_to_inlines

---

INSTALL.md

Fixed the broken link for cabal-install under the Quick cabal method section in the INSTALL.md.

Fix broken link for cabal-install in INSTALL.md

---

data/templates/default.rst
src/Text/Pandoc/Writers/RST.hs
test/Tests/Writers/RST.hs

after this commit use `$titleblock` in order to get what was contained
in `$title` before, that is a title and subtitle rendered according to
the official rST method
http://docutils.sourceforge.net/docs/user/rst/quickstart.html#document-title-subtitle. from
now on, the `$title` and `$subtitle` metadata are available and they
simply carry the metadata values

RST writer: metadata interface change, add `titleblock`, closes #4803

---

changelog

Follow-up to #4801. Happy to update the website too once we agree on the wording.

Describe required space after hash as breaking change

---

MANUAL.txt
data/templates/default.latex

It is a bit awkward to have a title for every frame, but not for the one
that holds the table of contents. Allow users to specify a title if they
wish.

Support "toc-title" in the beamer template.

---

src/Text/Pandoc/Readers/HTML.hs

Preserve leading and trailing spaces inside links.

---

src/Text/Pandoc/PDF.hs

When rsvg-convert is not available, pandoc would tell the user to check for rsvg2pdf instead

PDF: fix reference to rsvg-convert

---

MANUAL.txt
data/templates/default.latex

This PR adds support for a [custom toc title](https://pandoc.org/MANUAL.html#variables-set-by-pandoc) to the default LaTeX template (and resulting PDFs). It also updates the manual for the option `toc-title`.

Add support for $toc-title$ to LaTeX (and PDF).

---

data/templates/default.opendocument

Remove unnecessary indenting of TOC title in ODT template.
Fixes #4798

Remove unnecessary indenting of TOC title in ODT template

---

MANUAL.txt

Small patch to provide more details about potential UTF8 enconding problems with `listings` and a link to possible workarounds.
Closes #4871

[doc] FIX #4871 : Encoding issue with `--listings`

---

src/Text/Pandoc/Writers/ODT.hs
src/Text/Pandoc/Writers/OpenDocument.hs

Image scaling in ODT was broken when a width was set to
a percentage. The width was passed to the svg:width field
as a pecentage, which is not correct according to the ODT
standard.
Instead the real dimensions should be passed as width and
height and the style:rel-width attribute should be set to the
percentage while style:rel-heigh attribute should be set to
"scale". The converse is true if a percentage height is given.
This is now fixed and documents produced are now properly
scaled.

Fix percentage image scaling in ODT

---

data/templates/default.html5
test/writer.html5

I've added an ID to the `header` element of the HTML5 template in order to style the element with a more-precise CSS rule. This should enable more flexibility without damaging any existing style rules out there which styled the `header` tag without reference to the ID I've added.
Composing an article in Typora triggered this change. Pandoc's HTML5 template generates a `header` with document information that I didn't want to display, which led me to style it as `header { display: none; }`. Typora, unfortunately, uses the `header` tag to implement its editor sidebar, including useful things like a file tree and a document outline. By styling the document with `header { display: none; }`, I was turning that useful feature off. I wanted it back on.
Yes, I could use just a local template …

Make HTML5 header easier to style precisely in default template

---

src/Text/Pandoc/Writers/Docx.hs

Docx writer: add MetaString case for abstract, subtitle

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/Readers/Markdown.hs
test/command/yaml-metadata-blocks.md
test/command/yaml-metadata.yaml

implements #1960 and solves https://github.com/jgm/pandoc/issues/3115
I finally got this compiling... still need to do some testing (especially around whether metadata from different sources has the right precedences) and write docs.
But feel free to play around with it!
Also: since YAML is a superset of JSON, you can actually already use this with `--metadata-file file.json`

Introduce --metadata-file option

---

src/Text/Pandoc/Readers/RST.hs
test/Tests/Readers/RST.hs

this eliminates a regression error introduced after pandoc 2.1.1,
affecting rST inline parsing. see the issue for details

parse rST inlines containing newlines closing #4912

---

src/Text/Pandoc/Writers/RTF.hs

Building with ghc-8.6.1 causes the following error:
```
src/Text/Pandoc/Writers/RTF.hs:345:3: error:
• Could not deduce (Control.Monad.Fail.MonadFail m)
arising from a do statement
with the failable pattern ‘(first : rest)’
from the context: PandocMonad m
bound by the type signature for:
listItemToRTF :: forall (m :: * -> *).
PandocMonad m =>
Alignment -> Int -> String -> [Block] -> m String
at src/Text/Pandoc/Writers/RTF.hs:(335,1)-(340,25)
Possible fix:
add (Control.Monad.Fail.MonadFail m) to the context of
the type signature for:
listItemToRTF :: forall (m :: * -> *).
PandocMonad m =>
Alignment -> Int -> String -> [Block] -> m String
• In a stmt of a 'do' block:
(first : rest) <- mapM
(blockToRTF (indent + listIncrement) alignment) list
In the expression:
do (first : rest) <- mapM …
```

RTF writer: Fix build failure with ghc-8.6.1 caused by missing MonadFail instance.

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/tables.opendocument

This changes the way styles for cells in the header row
and normal rows are handled in ODT tables.
Previously a new (but identical) style was generated for
every table, specifying the style of the cells within the table.
After this change there are two style definitions for table cells,
one for the cells in the header row, one for all other cells.
This doesn't change the actual styles, but makes post-processing
changes to the table styles much simpler as it is no longer
necessary to introduce new styles for header rows and there are
now only two styles where there was previously one per table.

ODT Writer: Improve table header row style handling

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/4928.md

Fixes #4928.
Adding multiprenote (multipostnote) to a single prefix (suffix) seems reasonable to me, but it also feels like a bit of a hack. I'm new to Haskell, so if there's a cleaner way of doing this, let me know and I'll resubmit.

Add support for multiprenote and multipostnote arguments in LaTeX.

---

src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/Shared.hs
test/command/4885.md

Force inline org-mode code blocks to honor export options.

---

src/Text/Pandoc/Readers/Org/Inlines.hs
test/Tests/Readers/Org/Inline.hs

This allows `src_emacs-lisp[]{(+ 1 1)}` to be handled like `src_emacs-lisp{(+ 1 1)}`, which wasn't the case previously.

Parse empty argument array in inline org-mode src blocks.

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/writer.opendocument

Figure captions are now numbered 1, 2, 3, ... The format in
the caption is "Figure 1: <caption>" and so on.
This is necessary in order for libreoffice to generate an
Illustration Index (Table of Figures) for included figures.

OpenDocument writer: Implement figure numbering in captions

---

src/Text/Pandoc/Readers/Org/DocumentTree.hs
src/Text/Pandoc/Writers/Docx.hs
src/Text/Pandoc/Writers/OpenDocument.hs
src/Text/Pandoc/Writers/Powerpoint/Presentation.hs
src/Text/Pandoc/Writers/RST.hs
src/Text/Pandoc/Writers/Shared.hs

~~depends on https://github.com/jgm/pandoc-types/pull/51~~

use lookupMeta* functions wherever possible

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/tables.opendocument

Implement table caption numbering with a format
"Table 1: <caption>".
Translations are enabled and numbering is consecutive for
captioned tables, uncaptioned tables are not enumerated.
Captioned figures are now also numbered consecutively
and uncaptioned figures are not enumerated.

OpenDocument writer: Implement table caption numbering

---

src/Text/Pandoc/Readers/Org/DocumentTree.hs
src/Text/Pandoc/Readers/Org/Meta.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
src/Text/Pandoc/Readers/Org/Parsing.hs
test/command/4284.md

Closes #4284.
If one or more of the specified tags contains a non-tag character
like `+`, Org-mode will not treat that as a valid tag, but will
nonetheless continue scanning for valid tags. That behavior is not
replicated in this patch; entering `cat+dog` as one of the entries in
`#+EXCLUDE_TAGS` and running the file through Pandoc will cause the
parser to fail and result in the only excluded tag being the default, `noexport`.
I couldn't think of a particularly clean way of handling this particular edge case.

Add partial support for `#+EXCLUDE_TAGS` option.

---

data/templates/default.revealjs

so `% pandoc -V notes-server=true` works again.

revealjs: typo in the socket.io javascript plugin

---

data/abbreviations

A less commonly used abbreviation, but one that is always used sentence-internally and where we want a non-breaking space after.

Add viz. to abbreviations file

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/4306.md

LaTeX reader: add support for `nolinkurl` command.

---

pandoc.cabal
src/Text/Pandoc/Filter.hs
src/Text/Pandoc/Filter/JSON.hs
src/Text/Pandoc/Filter/Lua.hs
src/Text/Pandoc/Lua.hs
src/Text/Pandoc/Lua/Filter.hs
src/Text/Pandoc/Lua/Init.hs
src/Text/Pandoc/Writers/Custom.hs
test/Tests/Lua.hs

Expose more useful functions via `Text.Pandoc.Lua`.
The `Text.Pandoc.Filter` is now also exposed, as importing `Text.Pandoc.App` just for its filtering features seems like overkill. This also helps with testing.

Cleanup Text.Pandoc.Lua module

---

MANUAL.txt
src/Text/Pandoc/Writers/EPUB.hs

EPUB writer: use metadata field `css` instead of `stylesheet`

---

data/templates/default.latex

It would be nice to have a possibility to set the romanfont in xelatex/lualatex over a variable since mainfont actually oversets sansfont in headings

Adding a variable romanfont

---

src/Text/Pandoc/Writers/Docx.hs

This is prompted by https://github.com/lierdakil/pandoc-crossref/issues/147
Long story short, pandoc creates docx bookmarks for divs/spans with `id` set but fails to do so for images and code blocks. I'm pretty sure it's an oversight, so this PR adds those.
I also moved the bookmark-related code into a new utility function, since copy-pasting that code two more times didn't seem like a very good solution.

Docx image and code block bookmarks

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/writer.opendocument

Previously lists were indented by half an inch on the first line
for each level of nesting. This resulted in lists that looked like
this:
```
1.      The first line of the list point text
the second line of the same list point.
```
Fix this and bring style into line with libreoffice standards:
```
1.  The first line of the list point text
the second line of the list point text.
```

ODT writer: Fix list indentation

---

INSTALL.md

There have been quite a few users asking questions, that were simply using the outdated Linux version from their package manager.
I've also seen people new to the commandline getting confused with the zips, and whether they should move the binary in the zip to the macOS `Applications` folder. That's why I switched the order of the `zip` and `brew` install methods.
We could also consider adding some JavaScript that constructs a direct link to the right installer, depending on the User Agent String of the browser.

simplify INSTALL.md

---

INSTALL.md

Includes explanation of how to install related tools with package managers (since the method of installing `rsvg-convert` is not obvious).

Improve installation notes on associated software

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

As discussed in https://github.com/jgm/pandoc/issues/5131 it is better to let KOMA document classes handle parskip itself.
Please check the indentation of the added code, which might not be the style that should be adhered to.

let KOMA document class handle parskip when applicable

---

INSTALL.md

odd formatting at the end of the document was making markdown
choke on link rendering; deleting that fixed the issues with all
links.
also update version: 1.6.5 produced an error;
1.7.0 and higher seems OK

fix various links in INSTALL.md; bump required stack version

---

MANUAL.txt
src/Text/Pandoc/Writers/ICML.hs

see #2106 
This turned out to be a lot easier than expected. For better or worse (this time for the better), the ICML writer implements styles simply as a list of Strings that are being passed around.

ICML writer: support custom-styles

---

MANUAL.txt

The example to create a div with id `refs` instead creates a div with class `#refs`.  The fix is to add curly brackets.

Fix typo in MANUAL.txt

---

src/Text/Pandoc/Writers/Org.hs
test/command/5178.md

``` html
<div class="sourceCode" id="cb1" data-org-language="lisp" data-startFrom="20">
<pre class="sourceCode numberSource commonlisp numberLines">
<code class="sourceCode commonlisp">
<a class="sourceLine" id="cb1-20" title="20">(<span class="op">+</span> <span class="dv">1</span> <span class="dv">1</span>)
</a>
</code>
</pre>
</div>
```
I noticed that writing to HTML doesn't list the `startFrom` data as an attribute in `<pre>`; is this supposed to happen? If so I'll need to modify this patch slightly, since converting the above HTML back to Org does not write the `startFrom` data.
Closes #5178.

Org writer: preserve line-numbering for example and code blocks.

---

src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Readers/LaTeX/Parsing.hs
src/Text/Pandoc/Readers/MediaWiki.hs
src/Text/Pandoc/Readers/Muse.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
src/Text/Pandoc/Readers/RST.hs

It is updated by some readers, but never actually used.

Remove unused HasHeaderMap

---

src/Text/Pandoc/Writers/DokuWiki.hs
test/dokuwiki_external_images.dokuwiki
test/writer.dokuwiki

closes #5183
* `![](foo.png)` should be converted to `{{foo.png}}` (relative path)
* `![](/foo.png]` should be converted to `{{/foo.png}}` (absolute path)
Therefore the ':' prefix is useless and must be removed.
It blocks users from making relative image links.

FIX #5183 : dokuwiki : remove automatic ':' prefix before internal image links

---

src/Text/Pandoc/Writers/ZimWiki.hs
test/writer.zimwiki

This is patch is similar to the PR #5184
https://github.com/jgm/pandoc/pull/5184
* `![](foo.png)` should be converted to `{{foo.png}}` (relative path)
* `![](/foo.png)` should be converted to `{{/foo.png}}` (absolute path)
Therefore the ':' prefix is useless and must be removed.
I never used the zimwiki, but i submitted the similar dokuwiki fix.
1. The zimwiki syntax is inspired by dokuwiki
2. The zimwiki documentation does not mention the colon character for images
3. The pandoc zimwiki writer seems to be a copy-paste for the dokuwiki writer
http://zim-wiki.org/manual/Help/Wiki_Syntax.html
If the PR #5184 is applied, I think this one should be applied too.

FIX #5183 : zimwiki : remove automatic colon prefix before internal  images

---

MANUAL.txt
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Readers/CommonMark.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Shared.hs
src/Text/Pandoc/Writers/CommonMark.hs
src/Text/Pandoc/Writers/HTML.hs
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/Markdown.hs
test/command/gfm.md
test/command/tasklist.md

closes #3051 
rationale:
- basis for the markdown syntax is [GFM task list items spec](https://github.github.com/gfm/#task-list-items-extension-)
- checkboxes in HTML output are [disabled on GitHub](https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/) as well
This currently does not create an extra span, but matches directly on the unicode characters. The code seems reasonably concise to me, but if you think going with a span is a better solution, I can change it of course...
~~TODO: adjust GFM reader/writer~~

Implement task lists

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Readers/DokuWiki.hs
test/Tests/Readers/DokuWiki.hs
test/test-pandoc.hs

Possible improvements:
- If table contains header row, parse alignment and apply it to the whole column. DokuWiki allows to align each cell separately, but Pandoc has no way to represent it.
- [Text conversions](https://www.dokuwiki.org/wiki:syntax#text_conversions) if `smart` extension is enabled.

Add DokuWiki reader

---

pandoc.cabal
src/Text/Pandoc/Readers/RST.hs
test/Tests/Readers/RST.hs
test/command/5182.md
test/command/5182.txt

Directives of this type without numeric inputs should not have a
`startFrom` attribute; with a blank value, the writers can produce
extra whitespace.
Also, the stuff around line 1000 is modified because previously, it failed to catch newlines.
Closes #5182.

Change treatment of `number-lines` directives.

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

When `Scale=MatchLowercase` is set as a default font option, this scales `mainfont` against the old default, meaning that it resizes whatever is set as the main font to match the metrics of Latin Modern. This can result, for example, in a document set to 12pt appearing in 11pt or 13pt. Setting this option for individual families allows everything to scale against the main font, and permits the user to override the setting if desired. Note that it is not necessary to specify `Ligatures=TeX`, as this is already set by default for the appropriate families. See the `fontspec` manual: <https://ctan.org/pkg/fontspec>.

LaTeX template: Prevent scaling of main font

---

MANUAL.txt
data/templates/default.latex

This renders `\subtitle` without requiring a different document class such as `scrartcl`, ~~using the `titling` package. This integrates the solution in the manual, which I believe was based on an example from Enrico Gregorio, <https://tex.stackexchange.com/a/50186> but is simplified.~~ The matter has come up several times (#4675, #3896, #1327 and on pandoc-discuss), so it seems worthwhile to include it by default even if requiring `titling` isn't ideal.
The blank command was added in <https://github.com/jgm/pandoc/commit/4ac59af2429d97c1bb1f54088453a97205c0fcdc> to avoid problems with packages that define `\subtitle`. I've verified that this solution will not load with Beamer or KOMA (I was initially using a separate test for KOMA, but `\providecommand` is sufficient to stop `titling` …

 LaTeX template: Render \subtitle

---

MANUAL.txt
data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Simplify the approach of #5212, ensuring that `mainfont` is used as the base font for scaling and that LuaLaTeX does not display the mono font with TeX ligatures (as it does not use the `Mapping=tex-ansi` option).
With this modified version of `\defaultfontfeatures`, fontspec erroneously reports scaling against the old default font in the log (this had confused me earlier, hence my previous approach), but it nonetheless displays the main font at the specified size. Using this rather than setting `Scale=MatchLowercase` for each family individually means that users will not lose scaling when upgrading to the new template if they were using other font options. Scaling can be disabled for an individual family by adding the option `Scale=1` to `sansfontoptions`, `monofontoptions`, etc.
Remove …

LaTeX template: Simplify fontspec usage

---

data/sample.lua

* The closing tag ' </table' was missing a '>'.
* The content of list items was not escaped.

sample.lua: Fix some minor issues

---

src/Text/Pandoc/Writers/ODT.hs

fixes #2839 
This is just a quick fix. I'd like to improve custom properties support like I'm doing for docx in https://github.com/jgm/pandoc/pull/5215 but I might do it there.

odt writer: fix typo in custom properties

---

data/templates/default.latex

The `\large` command does not reset the spacing without adding `\par` to the end, which caused `\subtitle` to use the same line spacing as `\title`.
(I missed this earlier because it is only visible in multi-line subtitles.)

LaTeX template: Fix subtitle spacing

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Ensure that `\part` and `\chapter` are only numbered if `numbersections` is set. To return to the previous behaviour, use `-V numbersections -V secnumdepth=0`.
With the Pandoc 2.5 template, one has to set `numbersections` to remove part/chapter numbering:
```markdown
pandoc -o chnum.pdf << EOT
---
documentclass: book
numbersections: true
secnumdepth: -2
---
EOT
```

LaTeX template: Respect `numbersections` for books

---

MANUAL.txt
data/templates/default.latex

Use the [`footnotehyper`](https://ctan.org/pkg/footnotehyper/) package if available, a rewrite of `footnote` that is compatible with `hyperref` and `babel-frenchb`. This also addresses the incompatibility with `xcolor` noted in #4861, but the new package has only been available since 2016, so this template still loads `xcolor` earlier for compatibility with older distributions. Note that the `footnote` package is part of `collection-latexrecommended` in TeX Live, so there shouldn't be any situations where it isn't available.

LaTeX template: Use `footnotehyper` if available

---

MANUAL.txt
data/templates/default.latex

Use the `etoolbox` package (same technique as #5213) to add the `institute` variable to `\maketitle`. Verified to work with `article`, `book`, `report`, `memoir`, `scrartcl`. Closes #4209.
It's not the prettiest thing ever: the tabular environment of `\author` and `\and` is rather inflexible. I'm wondering if the `institute` variable was intended only to support Beamer users (in which case it could simply be excluded from normal LaTeX output), but the manual indicates that it's supposed to work in both LaTeX and Beamer.
Example:
```shell
pandoc -o institute.pdf << EOT
---
title: Test
subtitle: More tests
author:
- Tester 1
- Tester 2
institute:
- University of Testing
- University of Diagnostics
date:
- 2019
---
EOT
```

LaTeX template: Restrict `institute` to Beamer

---

MANUAL.txt

In HTML based formats the `date` metadata variable is converted to ISO 8601 and available as `$date-meta$`, but it's not documented at the moment. This PR adds a block with all allowed date formats.

Manual: document `date-meta` template variable

---

data/init.lua
doc/lua-filters.md
src/Text/Pandoc/Lua/Init.hs

The file `init.lua` in pandoc's data directory is run as part of
pandoc's Lua initialization process. Previously, the `pandoc` module was
loaded in `init.lua`, and the structure for marshaling was set-up after.
This allowed simple patching of element marshaling, but made using
`init.lua` more difficult:
- it encouraged mixing essential initialization with user-defined
customization;
- upstream changes to init.lua had to be merged manually;
- accidentally breaking marshaling by removing required modules was
possible;
Instead, all required modules are now loaded before calling `init.lua`.
The file can be used entirely for user customization. Patching
marshaling functions, while discouraged, is still possible via the
`debug` module.

Use init.lua only for customizations

---

trypandoc/index.html

It's currently possible to craft a URL manually to convert to `jats` using the Try pandoc site [like this](http://pandoc.org/try/?text=!%5BFigure+1.+Citation+counts+for+PLOS+Biology+articles+published+in+2010.+Scopus+citation+counts+plotted+as+a+probability+distribution+for+all+197+*PLOS+Biology*+research+articles+published+in+2010.+Data+collected+May+20%2C+2013.+Median+19+citations%3B+10%25+of+papers+have+at+least+50+citations.%5D(%2Fimages%2F2013-12-11_figure_1.svg)%0A&from=markdown&to=jats)
This PR adds `jats` to the dropdown menu options.

Add JATS to output option on Try pandoc.

---

MANUAL.txt

There is frequent confusion as to whether the `styles` extension needs to be enabled when converting from md to docx (and if so, whether on the markdown reader or docx writer), while actually neither the md reader nor the docx writer make use of that extension.
That's why I propose this patch which consists of:
- a small change in the `Extension: styles` section
- switching the "Input" and "Output" sections, as outputting docx is the far more common case.
- adding this sentence:
> For docx output, you don't need to enable any extensions for custom styles to work.

MANUAL: reorder custom-styles section

---

MANUAL.txt

Add `The value of a variable will be indented to the same level as the variable.` to the MANUAL.
Fixes https://github.com/jgm/pandoc/issues/5337

Clarify variable substitution indentation in templates

---

src/Text/Pandoc/App.hs
src/Text/Pandoc/Readers/Markdown.hs

fixes #5272
Unfortunately, that's an API change. Meanwhile, we could use the default pandoc-markdown extensions as a stop-gap-measure instead:
let opts = def{ readerExtensions = pandocExtensions }

Markdown Reader: yamlToMeta respects extensions

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Ensures that section numbering does not reappear with custom section levels. See <https://tex.stackexchange.com/questions/473653/>. (This also has the advantage of being slightly more readable.)

 LaTeX template: Robust section numbering removal

---

src/Text/Pandoc/Writers/LaTeX.hs

The KOMA-Script `scrreprt` class follows the pattern of `report`, and does not support `\frontmatter`.

LaTeX writer: Add classes for frontmatter support

---

MANUAL.txt
data/bash_completion.tpl
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/PDF.hs

Add tectonic as an option for --pdf-engine.

---

test/latex-reader.latex

The test could not compile in LaTeX due to missing `setspace` package. Remove redundant packages.

LaTeX reader test: Allow compilation of file

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

This improves the readability of the template in the following ways:
- Use `hidelinks` option for hyperref, which has the same effect as `pdfborder={0 0 0}`, but its purpose is clearer. (The template didn't use it before because the `pdfborder` option was previously used alongside link colouring, before the `colorlinks` option existed.)
- Remove hyperref `breaklinks` option: according to the documentation, hyperref sets this automatically as appropriate to the driver.
- Use a simpler conditional for Polyglossia/Babel.
- Format comments consistently.

 LaTeX template: Improve readability

---

src/Text/Pandoc/ImageSize.hs

This is a small improvement to commit [9573141](https://github.com/jgm/pandoc/commit/957314143faec08b4687822557dac6ac32216cb9). That commit fixed PDF image sizes for PDFs created with Illustrator, but it was not working with PDFs created using Figma. The fix for this was to ignore all of the whitespace in the /MediaBox line. 
This fix ignores all whitespace in the PDF /MediaBox line so that a wider range of PDF sizes can be read. This improves fix to #4322.

Improve pdfSize in ImageSize by ignoring all whitespace in /MediaBox command

---

data/templates/default.latex

Ensures that `\maketitle`, `\tableofcontents`, and so forth are not affected by changes to line spacing. Closes #5179 by partially working around <https://github.com/reutenauer/polyglossia/issues/218>.
I haven't been able to find a major drawback to moving `\setstretch` outside the preamble, but have put up a [StackExchange question](https://tex.stackexchange.com/questions/480143/is-there-a-drawback-to-using-setstretch-outside-the-preamble) to see whether I'm missing anything.

LaTeX template: Move \setstretch after front matter

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

The default figure placement was added in <https://github.com/jgm/pandoc/commit/f3ab4bc2b99e9f7f3917708a9110d6500aa051a0>; there does not appear to have been a reason for placing it at the end of the preamble.
Other minor cleanup.

LaTeX template: Group graphics-related code

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Credits pandoc in content creator metadata (the default is 'LaTeX with hyperref').

LaTeX template: Add pandoc to PDF metadata

---

MANUAL.txt
data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Improve the workaround for #1658, adapting a solution by @u-fischer in <https://github.com/latex3/latex2e/issues/131> that works whether or not the `indent` variable is enabled. Rename the previous approach under the `subparagraph` variable as `block-headings`. This is no longer enabled by default, as it gives headings 3–5 an identical appearance. Provide an example in the manual of reformatting the appearance of headings more thoroughly using KOMA-Script. Closes #5365.

LaTeX template: Ensure correct heading/table order

---

MANUAL.txt

Corrects usage of 'heading' and 'header' in text (but does not change programmed names). Partially addresses #5423.

Manual: Improve 'header' and 'heading' usage

---

data/templates/default.revealjs

The latest Reveal.js (3.8.0) loads reset.css before loading reveal.css to remove the browser's default css.
https://github.com/hakimel/reveal.js/blob/3da09f1fef1fa3c140d2daa5bdee2a32683dd964/index.html#L9

default.revealjs: css loading follows the latest revealjs

---

pandoc.cabal

As can be seen at
https://matrix.hackage.haskell.org/package/pandoc@1555514886
the build fails for base-4.8 due to `blaze-html` unfortunately providing the Semigroup instance for `Html` conditionally only for base >= 4.9 (see below)
There's now immediate action required on your part as I've already fixed up the metadata of the three affected releases on Hackage:
- https://hackage.haskell.org/package/pandoc-2.7.2/revisions/
- https://hackage.haskell.org/package/pandoc-2.7.1/revisions/
- https://hackage.haskell.org/package/pandoc-2.7/revisions/
----
```
[101 of 149] Compiling Text.Pandoc.Writers.HTML ( src/Text/Pandoc/Writers/HTML.hs, /tmp/matrix-worker/1555517101/dist-newstyle/build/x86_64-linux/ghc-7.10.3/pandoc-2.7/build/Text/Pandoc/Writers/HTML.o ) …
```

Don't advertise base-4.8 support anymore

---

data/templates/default.revealjs

This file has been removed in 3.8.0: https://github.com/hakimel/reveal.js/commit/29b0e86089eb3ec0d4bb5811c9b723dfcf36703c

Remove reference to head.min.js

---

doc/customizing-pandoc.md
doc/epub.md
doc/filters.md
doc/getting-started.md
doc/lua-filters.md
doc/using-the-pandoc-api.md

"User's Guide" links are pointing to MANUAL.html which gives 404 page.
This replaces them with http://pandoc.org/MANUAL.html.

Fix broken links in documents

---

src/Text/Pandoc/Readers/MediaWiki.hs

Got similiar error with #2649
> Error at "source" (line 37, column 26):
> unexpected "c"
> expecting lf new-line
> |----- bgcolor="#DDDDFF" class="bottom"
>                          ^
> Pandoc could not convert successfully, error code: 65. Tried to run the following command: /usr/bin/pandoc --from=mediawiki --to=markdown_github /tmp/pandoc5cc73e2708042

Replace parseAttr with parseAttrs

---

data/templates/default.epub3

It’s seems that the commit https://github.com/daamien/pandoc/commit/411119b603509d9c9c42e48a661a61bc33eb6a24 removes the `type="text/css"` from both `<style>` and `<rel="stylesheet">` elements in all templates. The rationale for the change is described in https://github.com/jgm/pandoc/issues/5146 — the elements are optional and can cause HTML validators to complain.
However, this change causes Amazon’s [Kindlegen](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211]) (MAC OSX V2.9 build 1028-0897292) to not pick up the stylesheet when converting a Pandoc generated ePub3 to Mobi. No styles! This is probably a bug on Amazon’s end 😳—Epub3 uses XHTML5, so I think the type attribute should indeed be optional. But it is probably much easier reverting the change at Pandoc’s end, at …

Epub3 stylesheet link compatible with kindlegen

---

src/Text/Pandoc/Writers/FB2.hs

In current implementation FB2 genre tag contains hardcoded value "unrecognised".
This PR makes use of genre field specified in metadata.
@jgm, could you review this please?

FB2 writer: use genre metadata field

---

src/Text/Pandoc/Writers/FB2.hs
test/fb2/basic.fb2
test/writer.fb2

Existing FB2 readers, such as FBReader, already display links with type="note" as a superscript.
As for brackets, "official" FB2 converters add their own brackets, so they would be duplicated:
https://github.com/gribuser/fb2any/blob/c4a8b96d616f901d737f457e6d06daaad19836d6/FB_2_txt/fb2txt_engine.pas#L311

FB2 writer: do not wrap note references into <sup> and brackets

---

src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Shared.hs
src/Text/Pandoc/Writers/CommonMark.hs
src/Text/Pandoc/Writers/Markdown.hs
src/Text/Pandoc/Writers/Muse.hs
test/html-reader.native

add `onlySimpleTableCells` to Text.Pandoc.Shared
[API change]
Motivation was an inconsistency in the HTML reader, which only checked for `Plain`, but not `Para` in table cells (thus the change in the test). Via https://groups.google.com/forum/#!topic/pandoc-discuss/99dNIjLLQaE.

consolidate simple-table detection

---

src/Text/Pandoc/Class.hs
test/command/5517.md

move up the pattern match to be reachable, closes #5517
seems this goes all the way back to https://github.com/jgm/pandoc/commit/4cb124d147790814cf2055afdfd17e500cece559

fix handling of `file:` URL scheme in `downloadOrRead`

---

src/Text/Pandoc/Writers/HTML.hs
test/command/3577.md
test/command/4677.md
test/command/5121.md
test/writer.html4
test/writer.html5

The same alt text is already in the `<figcaption>` and screen-readers would read it twice, see #4737
Note: `Image attr [] (s,tit)` wouldn't work, since this would emit no alt tag which is invalid HTML.

HTML writer: emit empty alt tag in figures

---

src/Text/Pandoc/MIME.hs
src/Text/Pandoc/Writers/HTML.hs
test/command/2662.md
test/command/3450.md
test/command/4012.md
test/command/4677.md
test/command/5121.md
test/command/video-audio.md

As requested on [pandoc-discuss](https://groups.google.com/forum/#!topic/pandoc-discuss/BkBPXQ8pb3A) and also discussed in a [commonmark thread](https://talk.commonmark.org/t/embedded-audio-and-video/441/25), so I gave it a try.
Some tests needed to be changed slightly because the `alt` attribute comes last now.
---
I was also thinking of adding a way to disable the media player controls (which I enabled by default), like:
But the equivalent HTML would actually show the controls, since it doesn't take the value of the attribute into account, only the key. We could of course still implement it this way, but it sort of sets a precedent that the string `"false"` is somehow special in pandoc markdown attribute values. Or alternatively something like `{.no-controls}`.
---
About the list of …

Output HTML5 video and audio elements

---

doc/lua-filters.md
pandoc.cabal
src/Text/Pandoc/Lua/Marshaling/MediaBag.hs
src/Text/Pandoc/Lua/Module/MediaBag.hs
src/Text/Pandoc/MediaBag.hs
test/Tests/Lua/Module.hs
test/lua/module/pandoc-mediabag.lua

This adds three functions to the `pandoc.mediabag` Lua module:
- `delete`, which removes a single entry;
- `empty`, which empties the whole bag;
- `iter`, which simplifies iterating over the bag using Lua's generic `for` statement.

Pandoc mediabag extension

---

src/Text/Pandoc/Lua/Module/System.hs

Fixed function names of pandoc.system.get_working_directory() and
pandoc.system.with_temporary_directory() which are written in the
manual of lua filter. This PR is for fixing of #5594.

Update Lua function names in pandoc.system

---

data/jats.csl

Related to #5397, if a bibtex entry has editor names, the current `jats.csl` allows punctuation between citations elements which are not allowed by the [PubMed Central validator](https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker/).
**Steps to reproduce the current issue**
Pandoc v2.7.3
**Files**
[jats-example-files.zip](https://github.com/jgm/pandoc/files/3359726/jats-example-files.zip)
**Produce the JATS output using `jats.csl` from `master`**
```
pandoc -s --metadata-file metadata.json --bibliography bib.json --filter pandoc-citeproc --csl jats.csl.master --to jats example.md -o output.xml
```
Results in the following error using the online validator https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker/
```
50:    <given-names>A.</given-names></name>, <name><surname>Second
> …
```

Fix JATS issue with commas between editor name-part elements.

---

src/Text/Pandoc/Readers/Markdown.hs
test/command/5627.md

Markdown reader: handle inline code more eagerly within lists.

---

data/templates/default.jats
test/writer.jats

JATS v1.0 (and below) don't support `code` tags with attributes such as `language`. This means that a standard code snippet in a Markdown document produces JATS output that is invalid in the v1.0 JATS DTD.
This pull request simply updates the DTD for the JATS template to `v1.1` which makes the outputted JATS XML v1.1 compliant.
Pandoc v2.7.3
**Files**
[jats-example-files.zip](https://github.com/jgm/pandoc/files/3363134/jats-example-files.zip)
The Markdown file has a code snippet beginning with:
```r
install.packages("insight")
library(insight)
```
**Produce JATS XML using the current `default.jats` from `master`**
```
pandoc -s --metadata-file metadata.json  --template v1.0default.jats --to jats example.md -o outputv1.0.xml
```
Results in the following error using the online validator …

Updating JATS template to v1.1dtd

---

src/Text/Pandoc/Readers/RST.hs
test/command/5619.md

RST reader: keep `name` property in `imgAttr`.

---

tools/diff-zip.sh

Trying to use this script on windows (git-bash) gave several errors:
- *mktemp* complained about missing XXXs in the template (fixed by adding XXX)
- *find* didn't understand the -E switch (fixed by using the equivalent arguments)
- *terminal codes* were not being recognized by the console (-e added to echo)

Update diff-zip to support windows

---

MANUAL.txt
data/templates/default.context
src/Text/Pandoc/Writers/ConTeXt.hs
test/writer.context
test/writers-lang-and-dir.context

The type of PDF/A produced by the ConTeXt writer can be changed so that e.g. a PDF/A-2A can be produced by giving `pdfa=2a`, as discussed under [#5608](https://github.com/jgm/pandoc/issues/5608). If `pdfa` is given without value, a PDF/A-1B is produced, in accordance with the old behavior of the variable. For a list of supported types of PDF/A, see the formats beginning with `pdf/a` in [the ConTeXt source](https://source.contextgarden.net/tex/context/base/mkiv/lpdf-fmt.lua?search=pdf-fmt).
To  fix issues with tagging (which is a requirement for level A PDF/A conformance), the ConTeXt template is changed according to [discussion under #5409](https://github.com/jgm/pandoc/issues/5409#issuecomment-504637400).

Customizable type of PDF/A for the ConTeXt writer (issue #5608)

---

MANUAL.txt
data/templates/default.context

Most conversions can be reversed (with some formattings lost, though).
Generally, this isn't possible with conversions to PDFs.
This PR adds a metadata variable to include the source files in the resulting PDF so they can be extracted from the PDF afterwards (e.g. with `pdfdetach -saveall`).
Test case:
`test.md`:
```
---
title: Attachment test
includesource: true
...
Your PDF should include this source document as attachment to the file.
```
```
$ echo 'And this one (`test2.md`) too.' > test2.md
$ pandoc -t context test.md test2.md -o test.pdf
$ pdfdetach -list test.pdf
2 embedded files
1: test.md
2: test2.md
```

Add option to include source files in ConTeXt PDFs

---

CONTRIBUTING.md

from INSTALL.md and [elsewhere](https://github.com/jgm/pandoc/pull/4383#issuecomment-367379040)
I never seem to find this info easily when getting back to modifying pandoc.
I haven't removed the mostly duplicate info in INSTALL.md, let me know if I should.

Improve CONTRIBUTING.md with information on tests

---

MANUAL.txt

Unless anybody has a better idea?
The thing is, the revealjs template contains things like:
```
$if(controls)$
// Display controls in the bottom right corner
controls: $controls$,
$endif$
```
Since `0` is truthy in pandoc templates but falsy in JavaScript, this allows us to override [revealjs' default](https://github.com/hakimel/reveal.js#configuration).

MANUAL: reveal.js flags

---

src/Text/Pandoc/Writers/HTML.hs
test/command/5655.md

The web service passed in to `--webtex` may render formulas using inline
or display style by default. Prefixing formulas with the appropriate
command ensures they are rendered correctly.
This is a followup to the discussion in #5656.

HTML writer: ensure TeX formulas are rendered correctly

---

src/Text/Pandoc/Readers/LaTeX.hs

According to https://github.com/jgm/pandoc/issues/4725#issuecomment-399772217 not only the `lilypond` environment but also `ly` should be included in the verbatim list.
@jperon
https://github.com/jperon/lyluatex/issues/203

Treat `ly` as verbatim too

---

src/Text/Pandoc.hs

This blank line was breaking the code block into two. Visible at http://hackage.haskell.org/package/pandoc-2.7.3/docs/Text-Pandoc.html

Remove blank line

---

src/Text/Pandoc/Writers/Jira.hs
test/writer.jira

JIRA writer: Remove escapeStringForJira for code blocks

---

src/Text/Pandoc/Writers/XWiki.hs

Details at https://groups.google.com/forum/#!topic/pandoc-discuss/c861tTdCFTg
TL;DR:
Fix XWiki output for
```markdown
+----------+----------+
| Col A    | Col B    |
+==========+==========+
| Row A    | * Item A |
|          | * Item B |
+----------+----------+
```
from (notice that the following XWiki code renders as a table followed by a singleton list)
```
|=Col A|=Col B
|Row A|*. Item A
*. Item B
```
to
```
|=Col A|=Col B
|Row A|(((*. Item A
*. Item B
)))
```

Fix multiline table for XWiki writer

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/App/Opt.hs
test/command/5700-metadata-file-1.yml
test/command/5700-metadata-file-2.yml
test/command/5700.md

Changed optMetadataFile from Maybe FilePath to [FilePath]. This allows
for multiple YAML metadata files to be added. The new default value has
been changed from Nothing to [].
To account for this change in Text.Pandoc.App, metaDataFromFile now
operates on two mapM calls (for readFileLazy and yamlToMeta) and a fold.
Added a test (command/5700.md) which tests this functionality and
updated MANUAL.txt, as per the contributing guidelines.
This would fix #5700.

Change optMetadataFile type from Maybe to List

---

src/Text/Pandoc/App.hs
src/Text/Pandoc/Logging.hs

add UnusualConversion to LogMessage [API change]
see https://github.com/jgm/pandoc/issues/5730#issuecomment-529086055

Emit warning on `-f latex -o out.pdf`

---

pandoc.cabal

As of `cabal-install` 3.0, the solver can use the `other-extensions` field to set flags - with this commit, pandoc should cross-compile out of the box :)

Add to other-extensions field for use by cabal solver

---

src/Text/Pandoc/Readers/Org/Blocks.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
test/command/4186.md

Closes #4186.
I'm pretty sure Emacs' built-in Org-to-Markdown conversion is wrong; it doesn't respect the `-i` switch at all, for example. For this reason, I chose to use HTML instead for the test. It looks to me that Org's native HTML conversion (`org-html-export-to-html`) is consistent with what this PR suggests. I also tested by exporting to a PDF (`org-latex-export-to-pdf`) and eyeballing.

Org reader: modify handling of example blocks.

---

data/pandoc.lua
doc/lua-filters.md
test/lua/module/pandoc.lua

Attr values can now be given as normal Lua tables; this can be used as a
convenient alternative to define Attr values, instead of constructing
values with `pandoc.Attr`. Identifiers are taken from the *id* field,
classes must be given as space separated words in the *class* field. All
remaining fields are included as misc attributes.
With this change, the following lines now create equal elements:
pandoc.Span('test', {id = 'test', class = 'a b', check = 1})
pandoc.Span('test', pandoc.Attr('test', {'a','b'}, {check = 1}))
This also works when using the *attr* setter:
local span = pandoc.Span 'text'
span.attr = {id = 'test', class = 'a b', check = 1}
Furthermore, the *attributes* field of AST elements can now be a plain
key-value table even when using the `attributes` accessor:
local span = …

Lua filters: allow passing of HTML-like tables instead of Attr

---

MANUAL.txt
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Writers/OpenDocument.hs
test/command/5474-figures.md
test/command/5474-tables.md

This adds an external options +native_numbering to the
ODT writer enabling enumeration of figures and tables in
ODT output.

odt: Add external option for native numbering

---

MANUAL.txt

Added the missing documentation for the variable `hyperrefoptions` introduced in https://github.com/jgm/pandoc/pull/4925.

Add documentation for the variable `hyperrefoptions`.

---

src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/Writers/Math.hs
trypandoc/trypandoc.hs

This updates the URL and filenames to work with MathJax version 3.
The only problem is the  `--standalone` option, where loading SRE and the initial fonts fail. That should change in the near future, once v3 can webpack SRE properly. 
On the other hand for v2.7.2 the option did also not work as expected, as loading of fonts,  Menu and Zoom fails. So I feel there is not that much change there.

Updates MathJax URL to work with version 3

---

MANUAL.txt
src/Text/Pandoc/Options.hs
src/Text/Pandoc/Writers/HTML.hs

closes #5815
Is there a better way to write this? Do we have an analogue of `lookupMetaBool` for `Context` somewhere?

KaTeX: fleqn option

---

src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Shared.hs
src/Text/Pandoc/Writers/HTML.hs
test/command/5805.md

Closes #5796 .
I'm a bit unsure about adding a special case in the writer for a span with a "kbd" class because it means that any "<span class="kbd">content</span>" will be written as a `<kbd>` element which is unexpected I'd say. Moreover there are other elements like <small> that are represented as spans with a special class, just like kbd, that are not converted back to the original element.

add support for <kbd>

---

src/Text/Pandoc/Readers/HTML.hs
test/Tests/Readers/HTML.hs

Parsing support for `<samp>`  HTML element as requested in #5792 .
**Before**
```
➜  pandoc git:(issue5792) ✗ pandoc -f html -t markdown    
Output <samp>Answer is 42</samp> was printed.
Output Answer is 42 was printed.
```
**After**
```
➜  pandoc git:(issue5792) ✗ pandoc -f html -t markdown    
Output <samp>Answer is 42</samp> was printed.
Output `Answer is 42`{.sample} was printed.
```

Add Reader support for HTML <samp> element

---

changelog.md
src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Writers/HTML.hs
test/Tests/Writers/HTML.hs
test/html-reader.html
test/html-reader.native

If a `<q>` tag has a `cite` attribute, we interpret it as a link with an
inner quote.
Closes #5798

HTML reader: Handle cite attribute for quotes

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/command/5474-tables.md
test/tables.opendocument

Fixes #5681
Now table caption is placed before the table.
Example Markdown table
```markdown
Text before table.
Table: A simple table in Markdown.
| Column 1 | Column 2 | Column 3 | Column 4 |
| -------- | -------- | -------- | -------- |
| 11       | 12       | 13       | 14       |
| 21       | 22       | 23       | 24       |
| 31       | 32       | 33       | 34       |
```
gets converted to

Place caption before table in OpenDocument format.

---

src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Writers/HTML.hs
test/Tests/Readers/HTML.hs
test/Tests/Writers/HTML.hs

Change for #5799. Adds Reader/Writer support for `<var>` HTML element and Writer support for `<samp>` HTML element.
Before - 
```
➜  pandoc git:(issue5799) ✗ pandoc -t markdown -f html
<var>result</var>
result
➜  pandoc git:(issue5799) ✗ pandoc -f markdown -t html
`result`{.sample}
<p><code class="sample">result</code></p>
➜  pandoc git:(issue5799) ✗ pandoc -f markdown -t html
`result`{.variable}
<p><code class="variable">result</code></p>
```
After - 
```
➜  pandoc git:(issue5799) ✗ pandoc -t markdown -f html
<var>result</var>
`result`{.variable}
➜  pandoc git:(issue5799) ✗ pandoc -f markdown -t html
`result`{.sample}
<p><samp>result</samp></p>
➜  pandoc git:(issue5799) ✗ pandoc -f markdown -t html
`result`{.variable}
<p><var>result</var></p>
```

HTML Reader/Writer - Add support for <var> and <samp>

---

src/Text/Pandoc/Readers/LaTeX.hs

Add all titling commands to existing definition for `\dedication`.
It would be even better to handle these using the `epub:type` attribute (e.g. `extratitle` = `halftitlepage`; `uppertitleback` and `lowertitleback` = `copyright-page`), but this is a start.

LaTeX Reader: Add KOMA-Script metadata commands

---

data/templates/default.latex

Issue and solution is from below.
https://tex.stackexchange.com/questions/17292/how-to-write-spaces-between-korean-words-with-xecjk

Default latex template: patch for fixing spacing problem on CJK language.

---

src/Text/Pandoc/Readers/DokuWiki.hs
test/Tests/Readers/DokuWiki.hs

DokuWiki reader: parse markup inside monospace ('')

---

MANUAL.txt
changelog.md
doc/org.md
man/pandoc.1
src/Text/Pandoc/Readers/Org/Inlines.hs

Should be non-semantic changes, with all typo fixes in comments.

Fix easy-to-make typos

---

src/Text/Pandoc/Readers/LaTeX.hs

This was somehow missed in 884aef31c55e375cd62fcb55a71829d005087cae.

LaTeX reader: parse \micro siunitx unit command

---

src/Text/Pandoc/Writers/Jira.hs
test/tables.jira
test/writer.jira

Backslash-escaping is used instead of HTML entities, as escaped
characters are easier to read this way. Furthermore, Confluence, which
seems to use a subset of Jira markup, seems to get confused by HTML
entities.
Closes: #5858

Jira writer: improve escaping of special chars
