MANUAL.txt
data/templates/default.html4
data/templates/default.html5

Inspired by [this trick](https://github.com/jgm/pandoc/wiki/How-to-add-a-%22Table-of-Contents%22-title-in-the-HTML-template). I didn’t see a valid reason for this to remain a trick and not be included by default and that also makes it more consistent with other output formats.

Add support for $toc-title$ to HTML (4 and 5)

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writers-lang-and-dir.latex

otherwise there will be a LaTeX warning "No \author given" when the .tex file is compiled.

Keep the \author{} command even if author is not specified

---

MANUAL.txt
data/templates/default.revealjs

Second attempt to add support for background images in reveal.js title slides.
Fixes #4498.

Add title-slide-attributes variable to reveal.js template.

---

data/templates/default.context
test/writer.context

Added `\setupinterlinespace` to `title`, `subtitle` and `author` elements => otherwise longer titles that run over multiple lines will look squashed as `\tfd` etc. won't adapt the line spacing to the font size.

ConTeXt template: Adjustments to title formatting

---

doc/lua-filters.md

Metadata defaults can be given via the command line `--metadata-file`.
Adding raw format snippets is a common use case for Lua filters, so it
seems sensible to provide an example.
Thanks to @efx for proposing this filter.
Closes: pandoc/lua-filters#70

doc/lua-filters.md: replace metadata example with image centering example

---

src/Text/Pandoc/App/CommandLineOptions.hs

Since the website now redirect to https automatically, it would be nice to just use https in the help text.

Use HTTPS in copyright message

---

data/templates/default.latex

Hi, I believe, it is quite easy to overrun theTOC's frame, so I'd suggest automatic frame breaks for the toc frame.
I didn't see any other way to pass this "allowframebreaks" option to the TOC frame.
Thank you for pulling.

Allow framebreaks for beamer's TOC

---

data/templates/default.jats
test/jats-reader.xml
test/writer.jats

The current DTD for the [JATS writer template](https://github.com/jgm/pandoc/blob/6c435a17cd48af40dbf87ebbec8baf6ac6aabe27/data/templates/default.jats#L5) is for Journal Publishing (`JATS-journalpublishing1.dtd`), which does not permit `ext-link` as a valid child (https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/publisher-name.html).
This update modifies the default output template to be the less restrictive JATS archiving and interchange DTD which systems like PubMed use internally to represent their articles. The new dtd is as follows:
```
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD v1.2d1 20190208//EN" "JATS-archivearticle1.dtd">
```
As suggested by @jgm - I proposed this change to the Pandoc mailing list [a few weeks …

Update JATS dtd

---

doc/lua-filters.md

Links and anchors now follow consistent conventions, like lowercase-only
anchor names.
This breaks some links to specific sections in the document, but will
make it much easier to link documentation in the future.

doc/lua-filters.md: unify, fix anchors and internal links

---

doc/lua-filters.md
pandoc.cabal
src/Text/Pandoc/Lua/Filter.hs
src/Text/Pandoc/Lua/Init.hs
src/Text/Pandoc/Lua/Marshaling/List.hs
test/Tests/Lua.hs
test/lua/blocks-filter.lua
test/lua/inlines-filter.lua
test/lua/meta.lua

Allow filtering of lists of inlines and lists of blocks via Lua filter functions "Inlines" and "Blocks", respectively.
E.g.:
-- remove all spaces before a Cite element
function Inlines (inlns)
for i=#inlns,1, -1 do
if inlns[i] == "Cite" and inlns[i-1] and inlns[i-1].t == "Space" then
table.remove(inlns, i-1)
end
end
end

Lua: filtering element lists

---

src/Text/Pandoc/Readers/Docx.hs

There's currently `unless`, `not`, and `notParaOrPlain` in the same expression, which is a rather confusing triple negative. Replace `notParaOrPlain` with `paraOrPlain` and switch to `all` from `any` to clean this up.

Clean up a confusing triple negative

---

src/Text/Pandoc/PDF.hs

We're using maybe in redundant ways. Remove it altogether in one case and simplify it to fromMaybe in another.

Clean up overcomplicated maybe logic

---

src/Text/Pandoc/Readers/EPUB.hs
src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Writers/EPUB.hs
src/Text/Pandoc/Writers/Markdown.hs
src/Text/Pandoc/Writers/Ms.hs

Anywhere `maybe` is used with `id` as its second argument, using `fromMaybe` instead will simplify the code. Conversely, anywhere `fromMaybe` is used with the result of `fmap` or `<$>` as its second argument, using `maybe` instead will simplify the code.

Swap suboptimal uses of maybe and fromMaybe

---

src/Text/Pandoc/Readers/Odt/Generic/XMLConverter.hs

There's no need to use `catMaybes`, `uncurry`, `bool`, etc., just to get elements where the second element of a tuple is True.

Simplify an overcomplicated filtering function

---

src/Text/Pandoc/Readers/Docx/Fields.hs
src/Text/Pandoc/Writers/AsciiDoc.hs
src/Text/Pandoc/Writers/MediaWiki.hs

HLint's automatic refactoring isn't quite perfect, so some of its
changes were overcomplicated, wrong, or created new findings.
Clean these up.

Clean up after "hlint --refactor"

---

data/sample.lua

sample.lua: Fix typo in descriptive comments

---

src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Readers/RST.hs
test/rst-reader.native
test/rst-reader.rst

This PR adds the [highlight directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-highlight) from Sphinx rST to the pandoc rST reader.
This enables one to declare a default language used for highlighting in literal blocks.
```rst
.. highlight:: haskell
From now on code will be highlighted as Haskell code::
data Tree = Leaf | Node Tree Tree
Another exemple to show how terse using literal blocks becomes::
main :: IO ()
main = putStrLn "Hello World!"
We can change the language at any point in the document.
.. highlight:: python
So this block contains python code::
def main():
print("OK")
An we can still disable having a default language:
.. highlight::
::
This literal block will not be highlighted
```
As explained on [pandoc-discuss], this directive …

Add highlight directive to the rST reader

---

src/Text/Pandoc/Writers/AsciiDoc.hs

The `RawInline` case in `inlineToAsciiDoc` currenty looks like this:
https://github.com/jgm/pandoc/blob/0808c2a03f0dec1cd442e5e3cddfb70419724874/src/Text/Pandoc/Writers/AsciiDoc.hs#L490-L495
Notice how there are there are two overlapping `otherwise` guards. The second `otherwise` guard is completely unreachable, so this patch removes it.

Remove redundant `otherwise` guard in inlineToAsciiDoc

---

MANUAL.txt

Fixes #6154.
I’m not sure if I should update [man/pandoc.1](https://github.com/jgm/pandoc/blob/master/man/pandoc.1) too? The syntax is quite cryptic, and it looks like it’s actually auto-generated (with Pandoc itself maybe?). If that’s the case, I could auto-generate it (and include the result in this PR), but I’m not sure what command with what set of options I should run to achieve that :man_shrugging:.

Make MANUAL more explicit about NBSP handling by all_symbols_escapable

---

doc/lua-filters.md

Change description of BulletList parameter from 'List of Blocks' to 'List of List of Blocks'.

Fix description of BulletList Lua type

---

src/Text/Pandoc/Readers/Vimwiki.hs
test/vimwiki-reader.native
test/vimwiki-reader.wiki

Nested syntaxes are specified like this:
{{{sql
SELECT * FROM table
}}}
The preformatted code block parser has been extended to check if the
first attribute of the block is not a `key=value` pair, and in that case
it will be considered as a class.
Closes #6256.

Vimwiki reader: Add nested syntax highlighting

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/App/Opt.hs
src/Text/Pandoc/Class/CommonState.hs
src/Text/Pandoc/Class/PandocIO.hs
src/Text/Pandoc/Class/PandocMonad.hs

Hello,
This adds a `--no-check-certificate` option to the command line which instructs pandoc to disable certificate verification when fetching resources (like images) from https url with non trusted certificate (self signed for exemple).
We had to add a dependency to connection, not sure if we could have done otherwise.
It fixes #5636

Add an option to disable certificate validation

---

src/Text/Pandoc/Readers/Markdown.hs
test/Tests/Readers/Markdown.hs

This should fix #6284, as far as I can tell. All this does is moves the check for `notFollowedBy (inList >> listStart)` to after newline. I took the liberty of formatting the relevant code to hopefully be a little more readable.
Sorry for the mess I've arguably made in the tests, I've developed a splitting headache halfway through making those, and basically resorted to throwing semi-random strings at the compiler until it did what I wanted it to. The second part of the tests ("lists with X in backticks") are there basically to make sure I didn't break anything with the change. Those should pass both before and after the patch. The first part ("code with list marker ...") contains some examples that motivated the change in the first place, i.e. those fail on the current pandoc version.

[Markdown Reader] Fix inline code in lists (#6284)

---

MANUAL.txt

These should appear as separate blocks (since they can't all exist within the same document) but currently appear combined in single blocks.
Visible here: https://pandoc.org/MANUAL.html#metadata-blocks

Manual: separate adjacent verbatim code blocks

---

src/Text/Pandoc/Filter/Lua.hs

Print the Lua error properly instead of displaying their `show` string.

Lua filters: improve error messages for failing filters

---

data/templates/default.revealjs

I wanted to use an option and realized that the default pandoc template
didn't pass it through, so I went through and found all the options that
Reveal.js advertises but that Pandoc's template doesn't support.
<https://github.com/hakimel/reveal.js#configuration>
I also noticed that rollingLinks isn't a setting anymore, but it's fine
to keep it in the template because people might be using an old version
of Reveal.js (via `revealjs-url`) that still has this option.

Update revealjs template with newly available options

---

pandoc.cabal

`GPL-2` is interpreted as `GPL-2.0-only` only and is displayed as such on Hackage, however according to all the headers in the actual Haskell files the license is GPLv2 or later, i.e. `GPL-2.0-or-later` (https://spdx.org/licenses/).

Correct license listed in cabal

---

pandoc.cabal

In b3cfdc2c7 the license was changed to GPL-2.0-or-later which is an SPDX expression, however cabal only interprets the license field as an SPDX expression if cabal-version is 2.2 or later.
Starting with 2.2 cabal-version also has to be the first statement in the .cabal file.
> Starting with cabal-version: 2.2 the license field takes a (case-sensitive) SPDX expression [...]
https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-license
I noticed this because `cabal2nix` was acting up that the license was invalid.

Bump cabal-version to 2.2

---

test/Tests/Command.hs
test/Tests/Old.hs

I'm using nix and without this it can't find `zlib.so.1`, because it's not in one of the standard dirs, but somewhere inside the nix store.

Propagate (DY)LD_LIBRARY_PATH in tests

---

MANUAL.txt

With the [release of reveal.js 4.0.0](https://github.com/hakimel/reveal.js/releases/tag/4.0.0), the documentation moved from the GitHub README to the dedicated website <https://revealjs.com/>.
Note that there are [further adjustments](https://revealjs.com/upgrading/) to the [Pandoc template](https://github.com/jgm/pandoc-templates/blob/master/default.revealjs) necessary in order to make Pandoc work with reveal.js 4.0.0.

Update links to reveal.js documentation

---

.github/workflows/ci.yml
.github/workflows/commit-validation.yml

So, okay, this isn't easy to fix, because GitHub creates a merge commit on pull requests. See CI output on the last commit.

[CI] broken commit message length test

---

src/Text/Pandoc/Writers/HTML.hs

This PR fixes an issue that I have not seen reported yet but that I experienced directly.
Katex supports definition of [**global macros** that are persistent across math blocks](https://katex.org/docs/supported.html#macros).
However for this to work, you need to pass the same array as an option each time you render a block.
Taking as an example the following document `test.rst` compiled with command `pandoc --katex -s -f rst -t html -o test.html test.rst`:
```rst
Testing Katex
=============
.. math::
\gdef\foo{x^2 + y^2}
.. math::
\foo
```
Before this fix, macro `\foo` was not defined in the second math block. Now everything works as expected.
This should not break existing documents because if you want local macros you're supposed to use `\def` rather than `\gdef`.

Fixed Katex standalone script for handling macros

---

stack.yaml

On NixOS, it is necessary to compile with `stack --nix`. It is
furthermore necessary to provide zlib headers when `--nix` is enabled.

Make it possible to compile using Stack on NixOS

---

INSTALL.md

The FreeBSD port was renamed from pandoc to hs-pandoc in 2010.
The old pandoc port is still at version 1.5.1.1

doc: fix FreeBSD port link

---

src/Text/Pandoc/Writers/LaTeX.hs

Hi,
its bugging me for quite some time, that wen using the csquotes package its actually not really distinguished between single and double quotes. Therefore this PR.

Distinguish between single and double quotes when using enquote package

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-reader.docbook
test/docbook-reader.native

A <simplesect> is a section like any other, except that it never
contains an subsection, and is typically rendered unnumbered.
Fixes #6434

Docbook: map <simplesect> to unnumbered section

---

src/Text/Pandoc/Readers/DocBook.hs

A `<replaceable>` is a placeholder that a user is instructed to
replace with a value of their own, like
`<replaceable>prefix</replacable>/bin/foo`. In the standard Docbook
toolchain, this typically appears emphasized, and no other adornement.
But a `<replaceable>` is nearly always in a code element, where
emphasis won't work. So we do the same thing as for `<optional>`:
decorate the content with brackets.

Docbook: implement <replaceable>

---

src/Text/Pandoc/Readers/DocBook.hs

`<envar>` is used to refer to environment variables, and
`<systemitem>` is used to refer to system resources (like user
accounts etc).

Docbook reader: treat envar and systemitem like code

---

src/Text/Pandoc/Readers/DocBook.hs

A `<phrase>` has no semantic meaning. It is only useful to hang an
`id` or other attributes around a piece of text.

Docbook reader: implement <phrase>

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-reader.docbook
test/docbook-reader.native

A `<procedure>` contains a sequence of `<step>`'s, or `<substeps>`
that themselves contain `<step>`'s. Procedures are mapped to bullet
lists.

Docbook reader: implement <procedure>

---

pandoc.cabal

Hello,
I noticed that the `vector` package is actually never used explicitly in Pandoc. This PR removes the dependency. Most importantly, there won't be a need to track the version upper bound anymore (e.g. dce6a7388a5f546ebbfd192febcb1753b743b377 and c56669ec39b741f8b14f16603294e27415576510).

Remove unused dependency `vector`

---

src/Text/Pandoc/MIME.hs

Heyo. [Per the EPUB 3.2 spec][1], `application/x-font-truetype` is no longer a valid identifier for TrueType fonts. This fixes warnings when validating pandoc-generated EPUBs using [epubcheck][2].
References plfa/plfa.github.io#479.
References #1761.
[1]: https://www.w3.org/publishing/epub3/epub-spec.html#sec-core-media-types
[2]: https://github.com/w3c/epubcheck

Fix MIME type for TrueType fonts in EPUBs

---

MANUAL.txt

I hope I got this right?
I found the `styles.html()` thing in the default html template and took me a while to figure out what it was doing (since I hadn't memorized the newish partial and pipe syntaxes yet).

MANUAL: clarify partial naming

---

changelog.md

Shorten changelog by combining related entries; remove entry Lua
regression, it affected only in the development version.

Cleanup changelog entries for jira, Lua

---

src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Readers/MediaWiki.hs
src/Text/Pandoc/Readers/Metadata.hs
src/Text/Pandoc/Readers/TWiki.hs
src/Text/Pandoc/Readers/TikiWiki.hs

Moved from #6328 :
I removed references to RelaxedPolyRec language extension everywhere I found it. Since I believe the current pandoc source can't be built with GHC 7 and below anyway, and RelaxedPolyRec is literally impossible to turn off since at least GHC 7.6, and almost all mention of this extension is removed from GHC documentation, I'd say it's a good idea to remove this extension as obsolete.

Remove obsolete RelaxedPolyRec extension

---

src/Text/Pandoc/App/Opt.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Readers/Metadata.hs

This is prompted by https://github.com/lierdakil/pandoc-crossref/issues/259.
Apparently, pandoc doesn't parse metatdata fields in the defaults file the way it does it for Markdown files, particularly boolean fields are parsed as strings. I took a gander, and to my surprise, found that pandoc uses completely different code path for parsing defaults file metadata field compared to yaml metadata block in Markdown.
Long story short, this is a first attempt at merging those code paths. This should hopefully behave _a little_ more consistently (although I'll admit I quickly gave up on figuring out how to parse fields as Markdown while parsing defaults file -- I believe it's feasible, but likely more than a bit tricky)
P.S. This is more a request for comments than a bona fide pull request. The …

Unify defaults metadata and markdown metadata parsers

---

pandoc.cabal
src/Text/Pandoc/Writers/Ms.hs
test/Tests/Writers/Ms.hs
test/test-pandoc.hs

If a line of ms code block output starts with a period (.), it should
be prepended by '\&' so that it is not interpreted as a roff command.
Fixes #6505

Escape starting periods in ms writer code blocks

---

.github/workflows/ci.yml

This replaces Haskell setup on Linux by a GitHub-provided action https://github.com/actions/setup-haskell. At the moment, it is a bit more robust. On Linux, this action will try hvr-ghc PPA, and if that fails, install via ghcup. Windows and macOS are also supported. Certain GHC/Cabal versions are preinstalled on GitHub Action runners, the action won't reinstall those.
A transient failure on CI prompted this.
~~Actually, I think I will also fix caching while at it. Converting to draft in the meantime.~~ nevermind, it seems mostly fine as is. I could swear I've noticed something weird going on, but apparently not.

[CI] Use setup-haskell action

---

src/Text/Pandoc/Readers/Docx.hs
src/Text/Pandoc/Readers/Docx/Parse.hs
src/Text/Pandoc/Readers/Docx/Parse/Styles.hs

As discussed in #6514.
Apparently, Word will apply `bCs`/`iCs` to a run iff the run has `cs` or `rtl` property set to `true`. This is confirmed by spec. Experiments show that both `cs` and `rtl` can be inherited from styles.
Fixes #6514
**NOTE:** Without #6504 this will likely have some confusing quirks, since I reckon `cs` and `rtl` are likely to be set on paragraph styles, actually.

[Docx Reader] Only use bCs/iCs on runs with rtl or cs property

---

src/Text/Pandoc/Writers/HTML.hs
test/command/3577.md
test/command/4677.md
test/command/5121.md
test/command/5642.md
test/writer.html5

Screen readers read an image's `alt` attribute and the figure caption,
both of which come from the same source in pandoc. The figure caption is
hidden from screen readers with the `aria-hidden` attribute. This
improves accessibility.
For HTML4, where `aria-hidden` is not allowed, pandoc still uses an
empty `alt` attribute to avoid duplicate contents.
Closes: #6491

HTML writer: improve alt-text/caption handling for HTML5

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3587.md

This patch adds minimal support for `\SIRange{firstnumber}{secondnumber}{unit}` (provided by siunitx) consistent with existing support for `\SI{value}{unit}`. Implementation is an extension of the existing `dosiunitx` function in the LaTeX reader. Added unit tests for SIRange in `test/command/3587.md`. 
Code passes all new and existing unit tests and compiles without warnings*.
This PR implements a fix for issue https://github.com/jgm/pandoc/issues/6417.
LaTeX input
```latex
Something important happens \SIRange{100}{200}{\ms} after the event.
```
Markdown output
```markdown
Something important happens 100 ms to 200 ms after the event.
```
----------
*As far as I can tell... I don't see any warning messages when I compile normally. I'm completely new to haskell and `cabal build -Wall` and …

Minimal support for SIRange in LaTeX reader

---

src/Text/Pandoc/Readers/LaTeX.hs
test/Tests/Readers/LaTeX.hs

This PR fixes #6596 . It also adds a test so this problem does not come up again.

[Latex Reader] Table cell parser not consuming spaces correctly

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/3587.md

My previous PR implemented pandoc conversion of LaTeX `\SIRange` commands (https://github.com/jgm/pandoc/pull/6418), but the correct syntax is `\SIrange` (as noted by @pauliacomi [here](https://github.com/jgm/pandoc/pull/6418#issuecomment-674017020); see also this [SO question](https://tex.stackexchange.com/questions/133704/sirange-typeset-different-in-text-and-math-mode/133707) for an example of the correct syntax). That's what I get for implementing that feature on a machine without my usual LaTeX setup... Sorry about that.
This PR introduces a trivial fix by changing all references to `SIRange` to `SIrange` in the current master. Unit tests pass, and I double checked the output of pandoc against pdflatex just to be sure.

LaTeX reader SIrange fix

---

src/Text/Pandoc/Readers/LaTeX.hs
test/Tests/Readers/LaTeX.hs

This PR fixes issue #6603
The main issues that need fixing are:

[Latex Reader] Fixing issues with \multirow and \multicolumn table cells

---

doc/lua-filters.md

This makes the example a bit more realistic/valuable by checking if the metadata value "date" is already present, before changing the value.

Make the setting-the-date example conditional

---

cabal.project
pandoc.cabal
src/Text/Pandoc/Writers/Tables.hs
stack.yaml
test/Tests/Writers/Tables.hs
test/test-pandoc.hs

(I'm putting this here for comment. Not sure how this should be handled regarding https://github.com/jgm/pandoc/pull/6644.)
`Writers.Tables` includes an `AnnTable` type and a `toAnnTable` function that takes a `Table` and adds row numbers to rows, column numbers and the data of spanned columns to cells, and separates the row head cells from the row body cells. I think that should be all the HTML writer needs to render a table with a simple traversal. It should also contain the information needed for other writers to render a table without having to re-lay it on a grid, hopefully.
I'm interested in how ergonomic the `AnnTable` type is. The definitions are, when stripped of documentation:
```haskell
data AnnTable = AnnTable Attr Caption [ColSpec] AnnTableHead [AnnTableBody] AnnTableFoot …
```

Add Writers.Tables helper functions and types, add tests for those

---

src/Text/Pandoc/Writers/ICML.hs
test/command/5541-localLink.md
test/command/5541-nesting.md
test/command/5541-urlLink.md
test/writer.icml

This PR addresses #5541 by supporting internal links when generating ICML.  I added two tests - one for testing that URL links aren't broken and one for testing the new inter-doc functionality.
This is my first PR for Pandoc and my first time writing Haskell, so all comments welcome!

Implement support for internal document links in ICML (#5541)

---

src/Text/Pandoc/Writers/HTML.hs
test/Tests/Old.hs
test/tables/planets.html4
test/tables/planets.html5
test/tables/planets.native

Add support for cells spanning multiple columns or rows.
See: #6314

Support colspans and rowspans in HTML tables

---

src/Text/Pandoc/Readers/LaTeX.hs
test/Tests/Readers/LaTeX.hs

Resolves #6681.
My understanding of LaTeX tables is that a cell that spans `n` rows will overwrite all the grid positions in columns that it spans for the next `n-1` rows. This is where the empty cell padding that needs to be removed comes from. If that is correct, the reader should now properly remove just these empty cells, and hopefully leave malformed tables relatively unmangled before they reach the `table` builder.

LaTeX reader: fix improper empty cell filtering

---

MANUAL.txt
data/templates/styles.html
src/Text/Pandoc/Writers/HTML.hs
test/lhs-test.html
test/lhs-test.html+lhs
test/writer.html4
test/writer.html5

Two things that inspired this:
- questions like [this one on StackOverflow](https://stackoverflow.com/questions/63293929/pandoc-change-font-family-to-sans-while-converting-from-markdown-to-html)
- I've recently updated and streamlined the CSS I use to generate simple HTML files (or publish to my blog), and was surprised how minimal it can be, while still looking pretty good (IMHO). The idea is to rely on browser defaults as much as possible (which are fairly consistent nowadays), so you don't have to override/normalize a lot.
Maybe this has been discussed before, but what about including something like this in the default HTML template?
~~I also quickly looked into moving this into the `styles.html` partial, but there we don't have access to all those variables I assume?~~
TODO:

Add CSS to default HTML template

---

src/Text/Pandoc/Writers/AsciiDoc.hs
test/writer.asciidoc
test/writer.asciidoctor

Addresses  #6538 by implementing jgm's [proposed solution](https://github.com/jgm/pandoc/issues/6538#issuecomment-659536590).
I had to change `writer.asciidoctor` to pass the tests.
Concretely:
Given the file: `my-test.markdown`
```{markdown}
Inline-style: ![alt text](media/rId25.jpg)
Block image:
The end.
````
This patch generates, after running:
```
$ stack run pandoc -- -f markdown test/my-test.markdown -t asciidoctor -o -
```
The following file:
```
Inline-style: image:media/rId25.jpg[alt text]
Block image:
image::media/rId26.jpg[alt text 2,title="image title"]
The end.
```
I think the current basic test doesn't distinguish between inline and block figures. Should the distinction be added to the basic test?
As mentioned in  #3177, this fix is brittle for the time being.
I have only …

Asciidoctor images

---

.hlint.yaml
data/pandoc.lua
doc/lua-filters.md
pandoc.cabal
src/Text/Pandoc/Lua/Init.hs
src/Text/Pandoc/Lua/Marshaling/AST.hs
src/Text/Pandoc/Lua/Marshaling/SimpleTable.hs
src/Text/Pandoc/Lua/Module/Utils.hs
src/Text/Pandoc/Lua/Util.hs
test/lua/module/pandoc-utils.lua

Old filters using tables now require minimal changes and can use
if PANDOC_VERSION > {2,10,1} then
pandoc.Table = function(c,a,w,h,r)
return pandoc.utils.from_simple_table(pandoc.SimpleTable(c,a,w,h,r))
end
end
and
function Table (tbl)
smpl_tbl = pandoc.utils.to_simple_table(tbl)
return pandoc.utils.from_simple_table(smpl_tbl)
end
to work with the current pandoc version.

Lua filters: allow using SimpleTable instead of Table

---

data/templates/default.opendocument
src/Text/Pandoc/Writers/OpenDocument.hs

To support `--toc-depth` option for ODT, writer and template are
updated.

Support toc-depth option for ODT writer (#6696)

---

src/Text/Pandoc/Writers/OpenDocument.hs

To implement Syntax highlighting for OpenDocument, inlineToOpenDocument in OpenDocument Writer is updated based on Docx Writer.
This commit is only for inline Code because update of CodeBlock needs structual change of output document.
Currently, styles are not generated automatically in styles.xml. To implement it, additional commit for ODT Writer is needed.
Although styles are not included in styles.xml, output file can be shown in LibreOffice(7.0.0.3) like normal characters.

Syntax highlight for inline code of OpenDocument

---

src/Text/Pandoc/App/CommandLineOptions.hs

Languages appear to be sorted by their long name, which leads to
unexpected results: e.g., the long name of *m4* is *GNU m4*, so it is
listed between *gnuassembler* and *go*.

Sort languages in `--list-highlight-languages` output

---

doc/lua-filters.md

The mobdebug package and Zerobrane studio allow Lua filters to be debugged with a REPL and full control. This is really useful for those of us writing filters who are not so proficient in Lua or don't fully understand the AST structures exposed via the filter.

Add info on how to debug lua filters

---

data/sample.lua

% pandoc --version // pandoc 2.9.2.1 (but not really relevant)
This PR fixes a few obvious (I hope) typos.
Notes on the changes:
* The escape() function's in_attribute argument wasn't used. I assume it was intended to enable escaping of quote characters
* The html_align() function was global but I think it's a local helper. Maybe it should be moved to the top of the file, along with the other helpers?
There are a few other things that I could fix here (or elsewhere), but I wanted to check first:
* I think that sample.lua should aim to generate the same (or very similar) output to that generated by the built-in HTML writer (although obviously it might lag a bit). Is this agreed?
* I think it would be useful to mention all the available global variables. Only PANDOC_DOCUMENT is mentioned, …

Fix apparent typos in sample.lua

---

doc/using-the-pandoc-api.md
src/Text/Pandoc/Class/PandocMonad.hs

While reading the docs I found a couple of small typos.

Fix some small typos in the API documentation

---

MANUAL.txt
man/pandoc.1

Update pandoc's man page to reflect the fact that org is no longer a supported input format for the raw_tex extension

Man page: remove org from list of input formats supporting raw_tex

---

data/templates/default.context
test/writer.context
test/writers-lang-and-dir.context

Without this \tfd etc don't adjust line spacing.

adds \setupinterlinespace to fonts larger than normal

---

src/Text/Pandoc/Writers/HTML.hs
test/tables/nordics.html4
test/tables/nordics.html5

The html writer adds a class "odd" or "even" to each row in tables. If a row has any user-specified classes (e.g. from a filter), then this results in the tag in the output having two `class` attributes, the second one being ignored by browsers.
So this PR changes the table row code slightly so that the `even`/`odd` classes are just added to the existing `Attr` instead.

Fix duplicate "class" attribute in HTML writer

---

doc/jats.md

This adds documentation about the JATS writer and default JATS templates. Most notably, this document lists supported variables/metadata values and how they are used when producing JATS XML output.

Add documentation for pandoc's handling of JATS

---

.github/workflows/lint.yml
.hlint.yaml
src/Text/Pandoc/Citeproc.hs
src/Text/Pandoc/Citeproc/MetaValue.hs
src/Text/Pandoc/Lua/Filter.hs
src/Text/Pandoc/Readers/BibTeX.hs
src/Text/Pandoc/Readers/DocBook.hs
src/Text/Pandoc/Readers/Docx.hs
src/Text/Pandoc/Readers/Docx/Combine.hs
src/Text/Pandoc/Readers/EPUB.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Readers/Metadata.hs
src/Text/Pandoc/Readers/Odt/ContentReader.hs
src/Text/Pandoc/Readers/Odt/Generic/Utils.hs
src/Text/Pandoc/Readers/Txt2Tags.hs
src/Text/Pandoc/Writers/CslJson.hs
src/Text/Pandoc/Writers/FB2.hs
src/Text/Pandoc/Writers/HTML.hs
src/Text/Pandoc/Writers/JATS.hs
src/Text/Pandoc/Writers/Jira.hs
src/Text/Pandoc/Writers/Ms.hs
src/Text/Pandoc/Writers/OpenDocument.hs
src/Text/Pandoc/Writers/Roff.hs

This adds a new GitHub Actions workflow which checks the code with HLint for all PRs and commits to master. Most linter annotations in the code are resolved; the remaining warnings are disabled via configs.

Lint code in PRs and when committing to master

---

MANUAL.txt

Let's inform users about the `pagetitle` variable, which is handy for HTML.
I am not sure which branch this patch should go to, `master` is set by default.  And I assumed `man/pandoc.1` is generated from this text file. Correct me if it's wrong.
changed:      MANUAL.txt

Added a sentence about `pagetitle` for HTML in the man page

---

pandoc.cabal
src/Text/Pandoc/Writers/JATS.hs
src/Text/Pandoc/Writers/JATS/Table.hs
src/Text/Pandoc/Writers/JATS/Types.hs

This makes it easier to split the module into smaller parts.

JATS writer: move Table handling to separate module

---

src/Text/Pandoc/Readers/DocBook.hs
test/command/6791.md

Table width is not natively supported by docbook but is by
the docbook fo stylesheets through an XML processing instruction,
<?dbfo table-width="50%"?> . Implement support for this instruction
in the DocBook reader.

DocBook reader: Table width support

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/command/6792.md

Use the same key-value in Attr for the table as the HTML writer
to implement table width support.

OpenDocument writer: Table width support

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/command/6755.md

Spans containing an ident in the Attr will become bookmarks
in OpenDocument format.

OpenDocument Writer: Implement span with ident support

---

test/tables/nordics.native
test/tables/planets.native
test/tables/students.native

As in title, the 3 native table test cases are normalized so that it will looks exactly like it is written by some pandoc writers.
Note that apart from white space normalization, it includes other normalization such as `[Str "Nordic countries"]` to `[Str "Nordic",Space,Str "countries"]`.

test/tables/*.native: normalized

---

data/templates/default.epub2
data/templates/default.epub3

- as-is: preserveAspectRatio="none"
- to-be: preserveAspectRatio="xMidYMid"
It is not bad to have a full screen, but the cover image is distorted because the aspect ratio is not preserved.
* https://github.com/jgm/pandoc-templates/pull/15

EPUB cover image: preserveAspectRatio="xMidYMid"

---

src/Text/Pandoc/Readers/CSV.hs

Header comment in the CSV reader module says "RST" instead of "CSV".

Fix a tiny Typo in the CSV reader module

---

doc/filters.md

The new package linked for NodeJS supersedes the previous one. It contains significantly better typing, better documentation, better CI, and more.

docs: adds a new Pandoc filtering framework

---

src/Text/Pandoc/Writers/Docbook.hs

Previously, we only added xmlns attributes to chapter elements, even when running with `--top-level-division=section`. Let’s add the namespaces to part and section elements too, when they are the selected top-level divisions.
We do not need to add namespaces to documents produced with `--standalone` flag, since those will already have xmlns attribute on the root element in the template.

Docbook writer: add XML namespaces to top-level elements

---

MANUAL.txt
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Writers/OpenDocument.hs
test/command/6774.md

This commit adds two extensions to the OpenDocument writer,
`references_over_links` and `number_prefix_references`.
The first extension, `references_over_links`, substitutes document
internal links for references to headers, figures and tables.
Text in references is kept consistent with the referenced header,
table or figure which is an improvement if the document is edited
after being generated by pandoc.
The second extension `number_prefix_references` will prefix the
header references with the number according to the style of the
referenced heading in the final document. As noted in the MANUAL.txt
the document will need to have indexes updated for these numbers
to be generated - similarly to table of contents in OpenDocument.
Figure and table references are not number prefixed as the …

OpenDocument writer: Allow references for internal links

---

src/Text/Pandoc/Writers/Docbook.hs
test/Tests/Writers/Docbook.hs

Similarly to https://github.com/jgm/pandoc/commit/d6fdfe6f2bba2a8ed25d6c9f11861774001f7a91, we should handle admonitions in Docbook writer as well.

Docbook writer: handle admonitions

---

src/Text/Pandoc/Logging.hs
src/Text/Pandoc/Writers/AsciiDoc.hs
test/command/nested-table-to-asciidoc-6942.md

This PR fixes #6942.
A new field is introduced in the WriterState to track the recursion level when writing nested tables.
Tables within tables ("level 1") are written correctly and deeper nested tables are written as level 1 and enclosed by a comment explaining that the nesting depth is not supported by asciidoc.
I did not write any new tests because I don't know how. 
I found `pandoc/test/tables.asciidoc` and that it is used but I don't know which direction the conversion goes and how to extend the source table without affecting other writers' tests.
A test would verify that for:
[table.asciidoc.txt](https://github.com/jgm/pandoc/files/5725516/table.asciidoc.txt)
[table.html.txt](https://github.com/jgm/pandoc/files/5725518/table.html.txt) …

added support for writing nested tables to asciidoc

---

data/templates/default.html4
data/templates/default.html5

The `description` meta tag will make the generated HTML documents more complete and SEO-friendly.

Add the `description` meta tag to the HTML templates

---

src/Text/Pandoc/Readers/Org/Inlines.hs
test/Tests/Readers/Org/Inline.hs

This adds the `"verbatim"` class so that exporters can apply a specific
style on it. For instance, it will be possible for HTML to add a CSS
rule for code + verbatim class.

Replace org-mode’s verbatim from code to codeWith.

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/App/Opt.hs
test/command/defaults-inheritance-1.md
test/command/defaults-inheritance-2.md
test/command/defaults-inheritance-3.md
test/command/defaults3.yaml
test/command/defaults4.yaml
test/command/defaults5.yaml
test/command/defaults6.yaml
test/command/defaults7.yaml
test/command/defaults8.yaml
test/command/defaults9.yaml

This pull request adds an inheritance system for defaults files as requested in #6827.
Currently, it is not possible to share a set of options between defaults files in a flexible way. The inheritance system implemented in this branch solves that problem by allowing a defaults file to specify other defaults files to inherit from.
See #6827
Assume `defsA.yaml` looks like this:
```yaml
defaults:
- defsB
- defsC
from: html
```
Then calling `pandoc -d defsA` has the same result as calling `pandoc -d defsB -d defsC -d defsA`. Note that first `defsB.yaml` is "applied", followed by `defsC.yaml` and finally `defsA.yaml`.
Assume:
- `defsA.yaml`:
```yaml
defaults:
- defsB
```
- `defsB.yaml`:
```yaml
defaults:
- defsA
```
In this scenario `defsA.yaml` inherits from `defsB.yaml` and vice versa. As …

Implement defaults file inheritance

---

src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Readers/Markdown.hs
test/Tests/Readers/Markdown.hs

closes https://github.com/jgm/pandoc/issues/2923
Changes overview:
* Add a `Ext_markdown_github_wikilink` extension
* Added in the `githubMarkdownExtensions` list
* Added in the `getAllExtensions` list
* Add the parser `githubWikiLink` in `Text.Pandoc.Readers.Markdown`
* Added it high in the `inline` parsers list
* Add two tests, one for each form
Notes:
* It has been done as part as ZuriHac 2020
* It is my first contribution
* I am available to pair on Discord if needed
Thanks by advance for your feedback.

Markdown reader: support GitHub wiki's internal links (#2923)

---

src/Text/Pandoc/Lua/Init.hs
src/Text/Pandoc/Lua/Module/Pandoc.hs
src/Text/Pandoc/Lua/Packages.hs
src/Text/Pandoc/Lua/PandocLua.hs

The Lua modules `pandoc` and `pandoc.List` are now always loaded from the
system's default data directory. Loading from a different directory by
overriding the default path, e.g. via `--data-dir`, is no longer supported to
avoid unexpected behavior and to address security concerns.

Lua: always load built-in Lua scripts from default data-dir

---

doc/lua-filters.md
pandoc.cabal
src/Text/Pandoc/Lua/Packages.hs
stack.yaml
test/Tests/Lua/Module.hs
test/lua/module/pandoc-path.lua

The module allows to work with file paths in a convenient and
platform-independent manner.

Lua: add module "pandoc.path"

---

MANUAL.txt
data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Load the iftex package directly rather than via the ifxetex and ifluatex compatibility wrappers, which have been merged into a single package that is part of the LaTeX core. The capitalization of the commands has been changed for compatibility with older versions of TeX Live that have the version of iftex by the Persian TeX Group. This had been removed in <https://github.com/jgm/pandoc/commit/2845794c0c31b2ef1f3e6a73bb5b109da4c74f37> for compatibility with BasicTeX, but that is no longer an issue.

LaTeX template: Update to iftex package

---

MANUAL.txt
src/Text/Pandoc/Writers/EPUB.hs

This is a pull-request to support the `belongs-to-collection` metadata attribute for ePubs.
See the request on https://github.com/jgm/pandoc/issues/6199
It adds two fields to the EPUB.hs writer:
- `belongs-to-collection`: The name of the collection.
- `group-position`: the number of the publication relative in the collection.
When a `belongs-to-collection` is found; `collection-type` = "series" will be added as well. I know that that can also be "set" but I never saw that in real-life.
The patch also reformats the other metadata a bit; that's only to keep the source-formatting nice :-)
The two new attributes are also added to the MANUAL.txt.

ePub writer: `belongs-to-collection` metadata

---

MANUAL.txt

Reopening of https://github.com/jgm/pandoc-website/pull/44, but targeted at the correct website
See jgm/pandoc#7077

 Document no template fallback for absolute path

---

data/odt/styles.xml

As of now, the default style for ODT documents has a "First paragraph" style that inherits from "Standard" style and has no top or bottom margin. All subsequent paragraphs have "Text_20_body" style that inherits from "Standard" and add "0.0598in" margins on top and bottom. This makes the final document a bit ugly since the first paragraph has a small gap ("0.0598in") towards the second one, and all subsequent have double that.
The proposed fix makes "First paragraph" inherit from "Text_20_body" instead so that it also has a consistent margin.
Another approach would be to inherit "Text_20_body" and add a 0 margin on top.

Update default ODT style

---

data/templates/default.revealjs

Add option to disable vertical content centering

---

data/templates/default.latex

The current default LaTeX template writes the url colours without braces in the hypersetup block. This makes it impossible to use colour that contain commas (as in `linkcolor: "rgb:red,34;green,136;blue,51"` using xcolor extended colour expressions) because the comma clashes with the key=value parsing.
This PR fix this by simply adding braces around the colour names.

Wrap url colours in braces in the default LaTeX template

---

CONTRIBUTING.md
COPYING.md
COPYRIGHT
INSTALL.md
MANUAL.txt
README.template
doc/lua-filters.md
man/pandoc.1
man/pandoc.1.after
src/Text/Pandoc/Citeproc.hs
src/Text/Pandoc/Citeproc/BibTeX.hs
src/Text/Pandoc/Readers/Textile.hs
src/Text/Pandoc/Writers/Markdown.hs
test/txt2tags.t2t
trypandoc/index.html
windows/Makefile
windows/pandoc.wxs

I've changed a lot of `http:` URLs of which the respective web servers have properly configured HTTPS to their `https` equivalents.
Plus a bunch of URLs have simply been updated.
Cf. https://github.com/jgm/pandoc/pull/6090

Fix/update URLs and use HTTP**S** where possible

---

pandoc.cabal

This PR updates bounds for random-1.2 which was released about a year ago.
If possible a new revision on hackage would be awesome, since it is blocking commercialhaskell/stackage#5474

Update bounds for random

---

src/Text/Pandoc/Writers/Docbook.hs
test/Tests/Writers/Docbook.hs

This implements the command line option --docbook-section-attrib which,
if used, adds key-value pairs found in the attributes list of Header.Attr as
XML attributes on the corresponding section element.
It checks that the key names are allowed according to DocBook 4 or 5
respectively. Any key name not allowed as an XML attribute name is
dropped, as are xml:id (for DocBook 5)/id (for DocBook 4) to not
intervene with computed identifiers.
The default is to not enable it, to avoid suddenly populating attributes
without changing anything else.

Include Header.Attr.attributes as XML attributes on section

---

doc/lua-filters.md

The documentation for Lua filters said "The this module defines..."
This has been fixed to say "This module defines..."

Fixed "The this" typo in lua-filters.md

---

doc/lua-filters.md

This commit fixes the typo in the Lua filters documentation, see #7159
The Lua filters documentation (file https://github.com/jgm/pandoc/blob/master/doc/lua-filters.md) had a grammatical error, it said "The return of a filter function must one of the following:", which lacks the verb "be", so the correct phrase is "The return of a filter function must be one of the following:".

Fixed typo #7159

---

pandoc.cabal

```
Building executable 'trypandoc' for pandoc-2.13..
[1 of 1] Compiling Main
trypandoc/trypandoc.hs:25:1: error:
Could not load module ‘Data.Text’
It is a member of the hidden package ‘text-1.2.4.1’.
Perhaps you need to add ‘text’ to the build-depends in your .cabal file.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
25 | import qualified Data.Text as T
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
trypandoc/trypandoc.hs:26:1: error:
Could not load module ‘Data.Text’
It is a member of the hidden package ‘text-1.2.4.1’.
Perhaps you need to add ‘text’ to the build-depends in your .cabal file.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
26 | import Data.Text (Text)
| ^^^^^^^^^^^^^^^^^^^^^^^
```

Require text for trypandoc

---

src/Text/Pandoc/Writers/Org.hs
test/writer.org

Like Markdown, Org supports LaTeX fragments. However, while many Markdown flavours like the TeX-style `$` / `$$`, as mentioned in the Org manual [1], Org works better with LaTeX-style `\( \)` / `\[ \]` delimiters. It also supports LaTeX environments (`\begin{*} ... \end{*}`) without any form of escaping, but that is best left to another patch.
\[1\]: https://orgmode.org/manual/LaTeX-fragments.html

Org writer: Use LaTeX style maths deliminators

---

src/Text/Pandoc/Highlighting.hs
src/Text/Pandoc/Readers/LaTeX.hs
src/Text/Pandoc/Writers/Docbook.hs
src/Text/Pandoc/Writers/JATS.hs
src/Text/Pandoc/Writers/TEI.hs

Since Skylighting does not support Nix syntax, we need to add custom syntax definition using --syntax-definition flag, otherwise files with nix extension will be recognized as bash scripts by the default syntax map. This means that code blocks with nix class will end up with language=bash when converted to DocBook and other formats.
Unfortunately, the writers always use the default syntax map so adding custom definition will not help.
This patch corrects that, allowing the writers to see all custom definitions.
The LaTeX reader suffers from the same issue but it has not been fixed there since it would require wider changes.
```ShellSession
$ printf '```nix\nfoo\n```' | cabal exec -- pandoc -f markdown -t docbook
<programlisting language="bash">
foo
</programlisting>
$ printf …
```

writers: Recognize extra syntax definitions

---

doc/org.md

Since it seem to be a common source of confusion, this PR adds a note in org-mode documentation referring users to consult org-mode's export documentation when they find themselves in a pinch.
Fixes #7236

Add note about default export behavior of org-mode in 

---

data/templates/default.latex

With the attached file test-biblio-header-spacing.md and the default LaTeX template, I observed that the space between the bibliography and the subsequent heading is too short in the PDF output (see bad.pdf). This comes from the implementation of the hanging indentation in the CSLReferences environment. This fix redefines `\par` instead of tweaking `\everypar`.
[test-biblio-header-spacing.md](https://github.com/jgm/pandoc/files/6341980/test-biblio-header-spacing.md)
[bad.pdf](https://github.com/jgm/pandoc/files/6341981/bad.pdf)
[good.pdf](https://github.com/jgm/pandoc/files/6341983/good.pdf)
.

LaTeX template: Fix bad vertical spacing after the bibliography

---

src/Text/Pandoc/Writers/Org.hs

Closes #7252 (discssion there).
As specified in https://orgmode.org/manual/LaTeX-fragments.html, an
inline \begin{}...\end{} LaTeX block must start on a new line.

Org writer: inline latex envs need newlines

---

src/Text/Pandoc/Writers/EPUB.hs

The EPUB writer previously used the same XML id for both the book identifier and the EPUB collection. This causes an error on epubcheck.

epub Writer: Fix belongs-to-collection XML id choice

---

src/Text/Pandoc/Readers/HTML.hs
test/html-reader.native

The tags `<title>` and `<h1 class="title">` often contain the same
information, so the latter was dropped from the document. However, as
this can lead to loss of information, the heading is now always
retained.
Use `--shift-heading-level-by=-1` to turn the `<h1>` into the document
title, or a filter to restore the previous behavior.
Closes: #2293

HTML reader: keep h1 tags as normal headers

---

MANUAL.txt

Some suffixes can be misinterpreted as locators (as in `(Fenner, 2012, p. 1-15)`) (#7321).
The manual mentions the case where a suffix can be forced to be parsed as locator, but the opposite direction isn't obvious.

Add citation example for locators and suffixes

---

src/Text/Pandoc/Readers/DocBook.hs
src/Text/Pandoc/Writers/Docbook.hs
test/Tests/Writers/Docbook.hs

In https://github.com/jgm/pandoc/pull/6922, I accidentally added non-existent admonitions to the DocBook writer (taken from rST). Let’s remove them. Though `danger` is actually supported since DocBook 5.2 so let’s add it to the DocBook reader.

DocBook: correct list of admonitions

---

src/Text/Pandoc/Writers/Markdown.hs
src/Text/Pandoc/Writers/Markdown/Inline.hs

`﻿Ext_attributes` covers at least the following:
- `Ext_fenced_code_attributes`
- `Ext_header_attributes`
- `Ext_inline_code_attributes`
- `Ext_link_attributes`

CommonMark writer: do not throw away attributes when Ext_attributes is enabled

---

src/Text/Pandoc/Writers/HTML.hs
test/command/7416.md

Addresses  #7416
It prefers the explicitly provided alt attribute.
```
$ pandoc -f markdown -t html
<figure>
</figure>
```
It keeps the old behavior otherwise.
```
% pandoc -f markdown -t html
^D
<figure>
</figure>
```

Remove duplicated alt text in HTML output.

---

src/Text/Pandoc/Writers/HTML.hs
test/command/7416.md

Related to #7416 
This PR removes the `aria-hidden=true` attribute from the HTML5 output when an explicit alt text is provided.
```
% pandoc -f markdown -t html
^D
<figure>
</figure>
```
Quoting from the [w3 recommendation](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden), emphasis mine:
> aria-hidden (state)
>
> Indicates whether the element is exposed to an accessibility API. See related aria-disabled.
>
> User agents determine an element's hidden status based on whether it is rendered, and the rendering is usually controlled by CSS. For example, an element whose display property is set to none is not rendered. An element is considered hidden if it, or any of its ancestors are not rendered or have their aria-hidden attribute value set to true.
>
> Authors MAY, with caution, **use …

HTML5 writer, remove aria-hidden when explicit atl text is provided.

---

src/Text/Pandoc/Readers/HTML.hs
test/Tests/Readers/HTML.hs

If an <img> in HTML has a `data-external` attribute, keep it as a
native attribute with the `data-` part of the key stripped.  This
information can be used to tell writers such as EPUB to not
incorporate images into the resulting document.

Recognize data-external when reading HTML img tags

---

MANUAL.txt
src/Text/Pandoc/Writers/EPUB.hs

Builds upon #7429 and fixes #6543

Respect image external attribute in epub writer

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-reader.docbook
test/docbook-reader.native

Originally intended for referring to UNIX manual pages, either part of the same DocBook document as [`refentry`](https://tdg.docbook.org/tdg/5.1/refentry.html) element, or external – hence the [`manvolnum`](https://tdg.docbook.org/tdg/5.1/manvolnum.html) element. These days, `refentry` is more general, for example the element documentation pages linked are each a refentry.
As per the *Processing expectations* section of [`citerefentry`](https://tdg.docbook.org/tdg/5.1/citerefentry.html), the element is supposed to be a hyperlink to a refentry (when in the same document) but pandoc does not support refentry tag at the moment so that is moot.
This roughly corresponds to a [`manpage` role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-manpage) in rST syntax, …

DocBook reader: add support for citerefentry

---

src/Text/Pandoc/Writers/LaTeX/Table.hs
test/command/5367.md
test/command/7272.md
test/tables.latex
test/tables/nordics.latex
test/tables/students.latex

In cases where a table row's content is longer than the column width, the table is scaled to the text width.
However, only two decimal places are used for each column's size.
In some cases, with many columns, the cumulative rounding can result in a noticeable overrun out of the text area (shown here with the `showframe` package):
(This particular case can be fixed with a larger columns setting, because `$\alpha$` isn't as wide as it seems, but the overall issue remains.)
This PR simply adds two extra decimal places to the column widths, minimizing the effect:
Reproduction:
[test.md](https://github.com/peterfab9845/pandoc/files/6904737/test.md)
`pandoc test.md -o test.pdf`
Version:
```
pandoc 2.14.0.2
Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
citeproc 0.4.0.1, …
```

LaTeX table writer: Increase column width precision

---

pandoc.cabal
src/Text/Pandoc/Network/HTTP.hs
src/Text/Pandoc/Readers/Org/Meta.hs
src/Text/Pandoc/Writers/EPUB.hs
src/Text/Pandoc/Writers/FB2.hs
src/Text/Pandoc/Writers/HTML.hs
src/Text/Pandoc/Writers/Markdown/Inline.hs

Given https://github.com/osener/markup.rocks/issues/21 and https://github.com/jgm/pandoc/issues/4535, I've recently been working on getting pandoc to build with ghcjs, which I've been able to do here: https://github.com/mt-caret/pandoc-ghcjs. Unfortunately, while the build succeeds there seems to be some problems with the JavaScript emitted so it does not work as-is (I'd love some help understanding what's wrong if anybody is interested). In the meantime, there seem to be relatively trivial changes that I can upstream to make pandoc more ghcjs-friendly.
Pandoc only depends on the urlEncode function in the package, which is also provided by http-types. The HTTP package also depends on the network package, which has difficulty building on ghcjs. I've created some benchmarks and fuzzing …

Stop using the HTTP package.

---

MANUAL.txt

Clarify internal punctuation in citation keys

---

shell.nix

I find it useful to have this installed via the nix shell when working
on pandoc, so I think others may also find it useful.

Add haskell-language-server to shell.nix

---

MANUAL.txt

Addresses a comment in #7484.
I wasn't sure whether to include a remark about CSS and compatibility with other markdown flavors (so I didn't). Also, I mentioned `<u>` because that's what the HTML writer generates.

Document use of the 'underline' class

---

src/Text/Pandoc/UTF8.hs

Any literal backslash needs to be escaped: these are currently showing
up [in hackage](https://hackage.haskell.org/package/pandoc-2.14.1/docs/Text-Pandoc-UTF8.html#v:toTextLazy) as “‘r’” instead of “‘\r’”.

Escape backslashes in haddock

---

MANUAL.txt

See the ["Each YAML block is a YAML document?" pandoc-discuss thread](https://groups.google.com/g/pandoc-discuss/c/icIxqbKptDc/m/q2dTCNpAAQAJ) for background.
I am proposing just adding a new paragraph. I did wonder whether "YAML object" could also be changed to "YAML document" (I think it occurs twice) but decided not to propose this in the PR.

Clarify that each YAML block is a separate YAML document

---

pandoc.cabal
src/Text/Pandoc/Readers/LaTeX.hs
src/Text/Pandoc/Readers/LaTeX/Parsing.hs
test/command/bar-endinput.tex
test/command/input-with-endinput.md

In LaTex, `\endinput` only concerns the handling of the file containing the directive.
So if an `\endinput` is encountered within an included file, the remaining content in the parent file is still relevant and valid.
Unfortunatly, pandoc does not respect this scoping of `\endinput`.
This patch attempts to implement the correct behaviour.

LaTeX-parser: restrict \endinput to current file

---

doc/lua-filters.md

The TikZ filter in `lua-filters.md` leaks the working directory into its output. I noticed this when inspecting Jupyter Notebooks generated via Pandoc. This pull request attempts to address this by leaving out the working directory in the target file name.

Do not leak working directory in TikZ filter

---

doc/lua-filters.md

Corresponds to the Lua parameter documentation:
https://github.com/jgm/pandoc/blob/60974538b25657c9aa37e72cc66ca3957912ddec/data/pandoc.lua#L629

Add missing type for Image title

---

doc/lua-filters.md

Since `identifier`, `classes` and `attributes` are aliases for `attr`, they should follow directly after the `attr` field to avoid confusion. This is the case for all types documented above `Image`.

Improve order of Image fields

---

doc/lua-filters.md

`iff` -> `if`, two occurrences.

Fix typos in pandoc.path docs

---

src/Text/Pandoc/Readers/Ipynb.hs

As of IPython version
```python
import IPython
print(IPython.__version__)
```
7.25.0
it supports the following mime-types in output cell:
```python
ip = get_ipython()
for mime in ip.display_formatter.formatters:
print(mime)
```
text/plain
text/html
text/markdown
image/svg+xml
image/png
application/pdf
image/jpeg
text/latex
application/json
application/javascript
This PR add support to the only one not already supporting: text/markdown

Ipynb reader: add text/markdown support in handleData

---

MANUAL.txt
man/pandoc.1
src/Text/Pandoc/Writers/HTML.hs
test/Tests/Writers/HTML.hs
test/command/4235.md
test/command/7006.md
test/writer.html4
test/writer.html5

This works similarly to the markdown writer, but with special care
taken to skipping section divs with what regards to the block level.
The change also takes care to not modify the output if `EndOfDocument`
is used.
I implemented this to implement side notes without JavaScript -- see https://mazzo.li/posts/value-speculation.html for an example.

Allow --reference-location to affect HTML output

---

src/Text/Pandoc/Readers/Ipynb.hs
src/Text/Pandoc/Writers/Ipynb.hs

This issue centers around Ipynb.Raw.
- fixes a typo in the [mime type of rst](https://docutils.sourceforge.io/FAQ.html#what-s-the-official-mime-type-for-restructuredtext-data)
- add most (i.e. those relevant to pandoc) selectable formats in jupyterlab's "Raw NBConvert Format", which includes a different mime-type for rst.
- format -> raw_mimetype. See jupyter/nbformat#229. Essentially while in the nbformat spec, format should be used, in the actual implementation of nbconvert, lab and notebook (i.e. the official ecosystem around ipynb) uses raw_mimetype instead. So for practicality for now we should use `raw_mimetype` as it is the only implemented key in the wild. We'll see how nbformat is resolving that issue.
Edit: also matches the above behavior in the ipynb writer too. Especially …

Ipynb reader: improve Ipynb.Raw handling

---

MANUAL.txt

Following addition in #7171
This is currently missing from the MANUAL but the variable is available in template.

Add mention for revealjs support of title-toc in MANUAL

---

MANUAL.txt
data/templates/default.latex
src/Text/Pandoc/Writers/LaTeX.hs
src/Text/Pandoc/Writers/LaTeX/Lang.hs
src/Text/Pandoc/Writers/LaTeX/Util.hs
test/writers-lang-and-dir.latex

Previously polyglossia worked better with xelatex, but
that is no longer the case, so we simplify the code so that
babel is used with all latex engines.
This involves a change to the default LaTeX template.

Use babel, not polyglossia, with xelatex

---

MANUAL.txt
src/Text/Pandoc/Writers/EPUB.hs

This adds the ability to specify EPUB3 specific refinements on the subject tag, specifically `authority` and `term`.
Use of the plain text subject metadata, or use in EPUB2 mode will function as before.

epub: Add EPUB3 subject metadata (authority/term)

---

data/templates/default.latex

* Use `babel`'s bidi implementation
* Remove global `lang` option -- it broke eg hebrew
* Import babel languages individually instead of as package options --
was broken for greek, hebrew
* Move `header-includes` to after `babel` setup
Closes #7604

Make babel use more idiomatic

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-reader.docbook
test/docbook-reader.native

This PR resolves #7427.  This was my first Haskell patch ever, so I'm sure that my additions, although functional, are an eyesore to seasoned Haskell coders. Please feel even more free than you usually would to correct/criticize my code.

Support for <indexterm>s when reading DocBook

---

MANUAL.txt
data/reader.lua
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/Readers/Custom.hs

New module Text.Pandoc.Readers.Custom, exporting
readCustom [API change].
Users can now do `-f myreader.lua` and pandoc will treat the
script myreader.lua as a custom reader, which parses an input
string to a pandoc AST, using the pandoc module defined for
Lua filters.
A sample custom reader can be found in data/reader.lua.
TODO: documentation.

Add interface for custom readers.

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Global.hs
src/Text/Pandoc/Lua/Marshaling/ReaderOptions.hs
src/Text/Pandoc/Lua/Module/Pandoc.hs
test/lua/module/pandoc.lua

Reader options can now be passed as an optional third argument to
`pandoc.read`. The object can either be a table or
`PANDOC_READER_OPTIONS`; the latter ensures that the same options used
for main input parsing are re-used to parse the input to `pandoc.read`.
Closes: #7656

Lua: allow to pass custom reader options to `pandoc.read`

---

data/templates/default.revealjs

This allows to modify it using Pandoc variable. Default value is correctly set to false by Pandoc.
This follows change in 
https://github.com/jgm/pandoc/commit/14b2eb2aeb21b3dee7d07c7348ebd2c586d6a866#diff-ecb2d745902425cf54bfa01ba4522c26288c56cf06be7be034312601f2129b4bR137
where `disableLayout` was added in template but was hard coded to FALSE. 
Unless there is a good reason to do that, I think it should be a variable to allow modify the value. Currently, it requires to patch the template to achieve that.

Add disableLayout variable in revealjs template

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
pandoc.cabal

Tested stack update on Linux x86_64 (NixOS Unstable) with:
- `stack test`:
```
All 2940 tests passed (64.06s)
pandoc              > Test suite test-pandoc passed
```
```
Drop unnecessary windows 32-bit constraints
Update pandoc.cabal to reflect CI configuration
Udpate GHC 8.10.{2,4} to GHC 8.10.7 on CI
```

Update build files

---

src/Text/Pandoc/Readers/RST.hs
test/Tests/Readers/RST.hs

This PR fixes #7699. It includes three new tests:
**Custom role with class field**
Input:
```rst
.. role:: classy
:class: myclass
:classy:`a`
```
This is expected to create a `Span` with a singleton class list: `["myclass"]`
**Custom role with a class field containing multiple whitespace-separated classes**
Input:
```rst
.. role:: classy
:class: myclass1 myclass2
myclass3
:classy:`a`
```
This is expected to create a `Span` with three classes: `["myclass1", "myclass2", "myclass3"]`
**Custom role with an inherited class field**
Input:
```rst
.. role:: classy
:class: myclass1
.. role:: classier(classy)
:class: myclass2
:classier:`a`
```
This is expected to create a `Span` with two classes: `["myclass2", "myclass1"]`

[#7699] check :class: for custom roles

---

src/Text/Pandoc/Citeproc.hs

Make Citeproc recognize files with .yml extension as YAML-bibliography.
This is a shoot at solving #7707.

Add .yml to Citeproc formatFromExtension

---

src/Text/Pandoc/Lua/Marshaling/AST.hs
test/lua/module/pandoc.lua

Using a Lua string where a list of inlines is expected will cause the
string to be split into words, replacing spaces and tabs into
`pandoc.Space()` elements and newlines into `pandoc.SoftBreak()`.
The previous behavior was to treat the string `s` as `{pandoc.Str(s)}`.
The old behavior can be recovered by wrapping the string into a table
`{s}`.

Lua: split strings into words when treating them as Inline list

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Marshaling/AST.hs
src/Text/Pandoc/Lua/Module/Utils.hs
test/lua/module/pandoc-utils.lua

The function convert a string to `Inlines`, treating interword spaces as
`Space`s or `SoftBreak`s. If you want a `Str` with literal spaces, use
`pandoc.Str`.
Closes: #7709

Lua: add function `pandoc.utils.text`

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/Utils.hs
test/lua/module/pandoc-utils.lua

The new `pandoc.Inlines` function behaves identical on string input, but
allows other Inlines-like arguments as well.
The `pandoc.utils.text` function could be written as
function pandoc.utils.text (x)
assert(type(x) == 'string')
return pandoc.Inlines(x)
end

Lua: remove `pandoc.utils.text`

---

src/Text/Pandoc/Writers/Ipynb.hs
test/Tests/Old.hs
test/ipynb/mime.ipynb
test/ipynb/mime.native
test/ipynb/mime.out.ipynb

feat(ipynb writer): write RawBlock of markdown in code-cell output
jgm#7561 makes the ipynb reader reads code-cell output with mime "text/markdown" to a RawBlock of markdown
This commit makes the ipynb writer writes this RawBlock of markdown back inside a code-cell output with the same mime, preserving this information in round-trip
test(ipynb): "text/markdown" mime type in code-cell output
This add tests on ipynb reader (#7561) and ipynb writer (#7563)'s ability to handle a "text/markdown" mime type in a code-cell output

ipynb writer: handle cell output with raw block of markdown

---

data/creole.lua
doc/custom-readers.md
pandoc.cabal
src/Text/Pandoc/Lua/Marshal/Sources.hs
src/Text/Pandoc/Lua/Orphans.hs
src/Text/Pandoc/Lua/Util.hs
src/Text/Pandoc/Readers/Custom.hs

The first argument passed to Lua `Reader` functions is no longer a plain
string but a richer data structure. The structure can easily be
converted to a string by applying `tostring`, but is also a list with
elements that contain each the *text* and *name* of each input source as
a property of the respective name.
A small example is added to the custom reader documentation, showcasing
its use in a reader that creates a syntax-highlighted code block for
each source code file passed as input.
Existing readers must be updated.

Custom reader: pass list of sources instead of concatenated text

---

pandoc.cabal
src/Text/Pandoc/Shared.hs
test/Tests/Old.hs
test/ipynb/rank.ipynb
test/ipynb/rank.out.html

Previously, with fmt == f case and Image have a rank of 1.
In the end, e.g. from ipynb to html conversion, if both html and image exists, it actually prefers the image.
This commit changes this, so that fmt == f is always highest rank, and rank never collides.
This is achieved by keeping fmt == f case having rank 1, and every other rank increased by 1.
[just-plotly.ipynb.zip](https://github.com/jgm/pandoc/files/7691334/just-plotly.ipynb.zip)
```bash
pandoc -s -o just-plotly-pandoc.html just-plotly.ipynb -V header-includes='<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>'    
``` …

fix(IpynbOutput)!: rank always favors output format

---

cabal.project
doc/lua-filters.md
pandoc.cabal
stack.yaml

The traversal order of filters can now be selected by setting the key
`traverse` of the filter to either `'topdown'` or `'typewise'`; the
default remains `'typewise'`.
Topdown traversals can be cut short by returning `false` as a second
value from the filter function. No child-element of the returned element
is processed in that case.

Lua: support topdown traversals

---

src/Text/Pandoc/Citeproc.hs

The JATS writer was losing quotes in element-citations, as it uses the
`T.P.Citeproc.getReferences` function to get references. That function
replaces `Quoted` elements with spans. That transformation is required
in `T.P.Citeproc.processCitations`, so it has been moved there.

JATS writer: keep quotes in element-citations

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/Utils.hs
test/lua/module/pandoc-utils.lua

The function behaves like the default `type` function from Lua's
standard library, but is aware of pandoc userdata types. A typical
use-case would be to determine the type of a metadata value.

Lua: add new library function `pandoc.utils.type`.

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Marshal/ReaderOptions.hs
src/Text/Pandoc/Lua/Module/Pandoc.hs

The default behavior of `pandoc.read` is to run the parser in the IO
environment, meaning that it can access the file-system to include
subfiles, e.g. when reading LaTeX or reStructuredText. However, the
mediabag is always discarded, which can be undesirable when reading
binary input like docx or epub.
A fourth option is added to `pandoc.read` that controls the behavior of
read. It can be one of the strings `'io'`, `'global'`, or `'sandbox'`:
-   'io' is the default and gives the old behavior as described above.
-   'global' uses the same environment that was used to read the input
files; the parser has full access to the file-system and the
mediabag.
-   'sandbox' works like 'global', but prohibits file-system access.

Lua: allow to control the PandocMonad type used in pandoc.read

---

doc/custom-writers.md
src/Text/Pandoc/Writers/Custom.hs

New templates variables can be added by giving variable-value pairs as a
second return value of the global function `Doc`.
Example:
function Doc (body, meta, vars)
vars.date = vars.date or os.date '%B %e, %Y'
return body, vars
end
Closes: #6731

Lua writer: allow variables to be set via second return value of `Doc`

---

MANUAL.txt

"standard Markdown" might be confused with CommonMark.
Closes #7802.

MANUAL.txt: clarify "standard Markdown" as "original Markdown"

---

src/Text/Pandoc/Readers/Org/BlockStarts.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
test/Tests/Readers/Org/Block/List.hs

Hi, this is my first contribution to Pandoc. I'm also somewhat new to Haskell, so even though I followed the guidelines and read similar code from other readers, you may need to revise my code styling.
This adds support for counter cookies in org lists. Such cookies are used to override the item counter in ordered lists. In org it is possible to set the counter at any list item, but since Pandoc AST does not support this, I restricted the usage to setting an offset for the entire ordered list, by using the cookie in the first list item.
Note that even though unordered lists do not have counters, Org Mode still parses such cookies in unordered lists and suppresses them in the output, so in the PR I did the same.
Also, even though org-list-allow-alphabetical is disabled in Emacs by default, …

Org reader: support counter cookies in lists

---

src/Text/Pandoc/Writers/MediaWiki.hs
test/command/7808.md

Prior to this commit the MediaWiki writer always added the display
text for a wiki link:
* [[Help|Help]]
* [[Bubbles|Everyone loves bubbles]]
However the display text in the first example is redundant since
MediaWiki uses the target as the default display text. The result being:
* [[Help]]
* [[Bubbles|Everyone loves bubbles]]

MediaWiki writer: Remove redundant display text for wiki links

---

src/Text/Pandoc/Writers/Org.hs
test/Tests/Writers/Org.hs
test/writer.org

This complements #7806 by supporting writing Org ordered lists that start at a specific number.
This commit also slightly changes another thing: before, the org writer indented items to match the markers length like so
```
9.  nine
10. ten
```
I was confused about what it should do when a counter cookie was present (should its length be counted as a marker, or ignored as part of the text like checkboxes?). But then I saw that org mode in emacs did not like this indentation anyway, because when you trigger the automatic formatting (`C-c C-c` above the list) emacs removes the extra spaces. So after this commit, the aligment is removed and the last list is written as
```
9. [@9] nine
10. ten
```
Is this ok?
Also, is one test enough? I did wrote another one with an empty item that would not …

Org writer: support starting number cookies

---

MANUAL.txt
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Readers/Org/BlockStarts.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
test/Tests/Readers/Org/Block/List.hs

As discussed in #7806, this adds support for alphabetical lists in org by enabling the extension Ext_fancy_lists, mimicking the behaviour of Org Mode when org-list-allow-alphabetical is enabled.
Enabling Ext_fancy_lists will also make Pandoc differentiate between the delimiters of ordered lists (periods or closing parentheses). Org does this differentiation by default when exporting to some formats (e.g. plain text) but does not in others (e.g. html and latex), so I decided to copy Pandoc's markdown reader behaviour.
One thing I'm unsure: since this is a separate extension, should the tests be moved to a separate file? Or are they fine in List?

Org reader: support alphabetical (fancy) lists

---

doc/org.md

Document the `fancy_lists` extension introduced for the org reader in #7812

Docs: document `fancy_lists` in doc/org.md

---

data/templates/default.html4
data/templates/default.html5

MathJax expect the config comes before loading the MathJax script.
This change of order allows one to config MathJax via header-includes,
which loads before the MathJax script.
This potentially is a breaking change.
However, the only kind math supported by pandoc that is configurable
seems to be katex, and according to
src/Text/Pandoc/Writers/HTML.hs
the way it is configured is hard-coded (katex doesn't seem to offer
MathJax style config that is independent of loading MathJax.)
So it seems it is safe to change this order without breaking
others' documents.
c.f. #2750
Edit: see https://docs.mathjax.org/en/latest/web/configuration.html#configuration-using-an-in-line-script
for the doc to config MathJax.

fix(html-template)!: load header-includes before math for MathJax config

---

data/templates/styles.html
test/lhs-test.html
test/lhs-test.html+lhs
test/writer.html4
test/writer.html5

I visited https://vmchale.github.io/jacinda/ on mobile, and found we can improve our stylesheet a bit. Repro:
pandoc https://raw.githubusercontent.com/vmchale/jacinda/main/doc/guide.md -s -o guide.html --toc
Changes:
1. Make all h1 a tiny bit smaller on mobile
2. Since we have no list-markers on the TOC, we should decrease the left paddings a bit to get the same visual effect.
Feedback welcome, then I can update the tests...

CSS in HTML template: adjust #TOC and h1 on mobile

---

MANUAL.txt
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/PDF.hs

PagedJS is a polyfill and supports the Paged Media standards by the W3C.
<https://www.pagedjs.org/>

PDF: support pagedjs-cli as pdf engine

---

shell.nix

Add missing dependency to Nix shell. `pandoc-lua-marshal` is currently broken in Nixpkgs, so building in the Nix shell still fails (assuming Nixpkgs is used as input). Nevertheless, this is one step closer to a working Nix build.

Add pandoc-lua-marshal to Nix shell

---

doc/epub.md

Addresses https://github.com/jgm/pandoc/issues/7845

Update link KindleGen -> KindlePreviewer

---

src/Text/Pandoc/Writers/Docbook.hs
test/Tests/Writers/Docbook.hs

This is what MyST does:
https://myst-parser.readthedocs.io/en/latest/using/syntax.html#targets-and-cross-referencing

Docbook writer: Interpret links without contents as cross-references

---

src/Text/Pandoc/Readers/Org/DocumentTree.hs

I think the commit messages do well in explaining the changes, so I will just copy them here:
Any non-space character is allowed as property drawer key, including ":" itself (so it is not really a delimiter). The real delimiter is a space character, so in a drawer like
```
:PROPERTIES:
::k:ey:: value
:END:
```
`:k:ey:` is a key with value `value`.
This usage can be seen in the Org Manual at [orgmode.org/manual/Using-Header-Arguments.html](https://orgmode.org/manual/Using-Header-Arguments.html), where the Org snippet
```
* Heading
:PROPERTIES:
:header-args:clojure:    :session *clojure-1*
:header-args:R:          :session *R*
:END:
```
is listed as an example.
The Org Manual page at [orgmode.org/manual/Property-Syntax.html](https://orgmode.org/manual/Property-Syntax.html) says (as of …

Org reader: small property drawer tweaks

---

doc/custom-writers.md
pandoc.cabal
src/Text/Pandoc/Lua/Writer/Classic.hs
src/Text/Pandoc/Writers/Custom.hs

Check for the global function `Writer` in a custom writer. If it exists, then it is called with the document and writer options as input. Otherwise we fall back to classic custom writers, requiring a global function for each AST element type.
Closes: #7880.

Lua: support single-function custom writers

---

src/Text/Pandoc/Readers/DokuWiki.hs
test/Tests/Readers/DokuWiki.hs

Within each cell, determine the cell alignment as per
https://www.dokuwiki.org/wiki:syntax#tables. The current approach, as
per the issue treats the first row's alignment as determining
that of the entire column. Given this, it wastes some work in
determining an alignment for every cell.

Add DokuWiki table alignment for #5202

---

src/Text/Pandoc/Readers/JATS.hs
test/command/6348.md

Footnotes in `<fn-group>` elements are collected and re-inserted into
the document as proper footnotes in the place where they are referenced.
Fixes: #6348

JATS reader: improve handling of fn-group elements

---

src/Text/Pandoc/Readers/Org/BlockStarts.hs
src/Text/Pandoc/Readers/Org/Blocks.hs
test/Tests/Readers/Org/Block.hs
test/Tests/Readers/Org/Directive.hs

Looking at the definition of `org-element-latex-environment-parser`, one sees that Org is more flexible than Pandoc about LaTeX environments. In fact, it parses every char just after `\begin{xxx}` until `\end{xxx}` as content for the environment, so all the following examples are valid environments that did not work before:
```org
\begin{equation} e = mc^2 \end{equations}
```
```org
\begin{tikzcd}[ampersand replacement=\&]
A \& B \\
C \& D
\arrow[from=1-1, to=1-2]
\arrow["f", from=2-1, to=2-2]
\end{tikzcd}
```
A question: is there any reason why the verbatim case was made to parse a line like `f(x) = x^2` inside environments as `Str "f(x) = x^2"` instead of `[Str "f(x)", Space, Str "=", Space, Str "x^2"]`? If I understood things properly the latter seems more correct to me in respect to …

Org reader fix: more flexible LaTeX environments

---

src/Text/Pandoc/Writers/LaTeX.hs

If scrreport is now chosen as the latex documentclass chapters will be used instead of sections. This behaviour is intended as scrreport is an alias for scrreprt which already created chapters. Fixes #6168

Add scrreport to the latex writer chaptersClasses. Fixed #6168

---

pandoc.cabal
src/Text/Pandoc/Shared.hs

This requires at least containers 0.6.0.1, which ships with the oldest
GHC version currently supported by pandoc (GHC 8.6).

Shared: define ordNub as alias for nubOrd from containers package

---

.github/workflows/commit-validation.yml
.github/workflows/format-validation.yml
.github/workflows/lint.yml.bkp
.github/workflows/release-candidate.yml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
Signed-off-by: naveensrinivasan …

Pin actions to a full length commit SHA

---

src/Text/Pandoc/Writers/EPUB.hs

After a comment by [JGM](https://github.com/jgm/pandoc/issues/1865#issuecomment-407898949) we refactored EPUB.hs to make it more readable. This includes adding more comments, splitting up the main conversion function (which was 500+ lines long). We think that readability is improved like this, but more refactoring may be necessary before the kindle writer will be worked on. 
If you disagree with some of the changes, let us know!

Refactor of Writers/EPUB.hs

---

src/Text/Pandoc/Readers/RST.hs
test/rst-reader.native

Math elements with a name, classes, or other fields are wrapped in a
`Span` with these attributes.

RST reader: wrap math in Span to preserve attributes

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Marshal/Sources.hs
src/Text/Pandoc/Lua/Module/Pandoc.hs

Sources, the data type passed to the `Reader` function in custom
readers, are now accepted as input to `pandoc.read`.

Lua: allow to pass Sources to pandoc.read

---

MANUAL.txt

Default HTML template is also including metadata variable `abstract`

Add HTML to formats including abstract

---

data/templates/default.latex

Rename \textormath to \TextOrMath for rendering Zero Width Non-Joiner
Maybe a typo?!

Fix <200c> character rendering

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-xref.docbook
test/docbook-xref.native

`<xref>` elements can also be used to link to `<figure>` elements. Alas, the DocBook reader was not aware of this and thus generated a link text which just said 'figure_title'.
https://tdg.docbook.org/tdg/4.5/figure.html explains that `<figure>` elements can contain `<title>` elements, so let's try to use that if it is available.
Technically, this logic could be a _lot_ more sophisticated. The [docbook-xsl project's XSLT stylesheet for handling `<xref>` elements](https://github.com/docbook/xslt10-stylesheets/blob/6ff683948c5a85949e4b7661f302e8b5f12f7bf2/xsl/html/xref.xsl) is a whopping 1300+ lines of code, and a lot of that is dedicated to a comprehensive heuristic which tries to come up with a sensible link text depending on the target element being referenced. However, it took seven …

Improved reading <xref> elements in DocBook files

---

src/Text/Pandoc/App/Opt.hs

This patch makes the following `--defaults` configuration work as expected. 
```yaml
highlight-style: ${.}/my.theme
```

Allow environment variable interpolation in highlight-style in defaults files

---

src/Text/Pandoc/Writers/ConTeXt.hs
test/writer.context

Autolinks, i.e. links with content that's the same as the linked URL,
are now marked with the `\url` command. All other links, both internal
and external, are created with the `\goto` command, leading to shorter,
slightly more idiomatic code. As before, autolinks can still be styled
via `\setupurl`, other links via `\setupinteraction`.

ConTeXt writer: unify link handling

---

data/templates/default.context
src/Text/Pandoc/Writers/ConTeXt.hs
test/Tests/Writers/ConTeXt.hs
test/command/3968.md
test/writer.context
test/writers-lang-and-dir.context

The document hierarchy is now conveyed using the
`\startsectionlevel`/`\stopsectionlevel` by default. This makes it easy
to include pandoc-generated snippets in documents at arbitrary levels.
The more semantic environments "chapter", "section", "subsection", etc.
are used if the `--top-level-division` command line parameter is set to
a non-default value.
Closes: #5539

ConTeXt writer: use "sectionlevel" environment for headings

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/MediaBag.hs

The function allows to fill the mediabag with all images in a given
document. Images that cannot be fetched are replaced with a Span
containing the image description.

Lua: add function pandoc.mediabag.fill

---

src/Text/Pandoc/Readers/Org/Shared.hs

Currently, webp files are not recognized as images. This pr would make `echo "[[file:test.webp]]" | stack run -- -f org -t html -i - -o -` outputs `<p><img src="test.webp" /></p>` instead of `<p><a href="test.webp">file:test.webp</a></p>`.
I also added support for [JPEG XL](https://en.wikipedia.org/wiki/JPEG_XL) images.

org reader: recognize {webp,jxl} files as images

---

src/Text/Pandoc/Writers/LaTeX.hs

Add ctexrep, ctexbook, and elegantbook document classes to the list for detecting.  These classes are widely used in China.

Add more class for detecting.

---

doc/lua-filters.md

Relevant discussion here: https://groups.google.com/g/pandoc-discuss/c/-NoL3Ft9AC8
I felt that it could be useful to inform that walk is the only way to get a deep copy of a List. I wrote this where I think that users will likely loop up for this feature, but it may be out of place.

Make clear that walk performs a deep copy

---

MANUAL.txt
doc/faqs.md
doc/lua-filters.md
src/Text/Pandoc/App.hs
src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/App/Opt.hs

* add `--embed-resources` flag for `--self-contained` without implying `--standalone`
* deprecate `--self-contained` flag
closes #7331

add `--embed-resources` flag

---

src/Text/Pandoc/Readers/Org/Meta.hs

Small typing mistake which causes e.g. `)/emph/)` and `(/noemph/)` on the default pre-chars.

Org reader: Fix `Post` standing for `Pre` in `setEmphasisPreChar`

---

src/Text/Pandoc/Parsing/Types.hs
src/Text/Pandoc/Readers/Odt/Arrows/Utils.hs
src/Text/Pandoc/Readers/Odt/ContentReader.hs
src/Text/Pandoc/Readers/Odt/Generic/XMLConverter.hs
src/Text/Pandoc/Readers/Odt/StyleReader.hs

CLC has approved the proposal to export `liftA2` from `Prelude`
(https://github.com/haskell/core-libraries-committee/issues/50).
It means that the entirety of `Applicative` will now be exported from `Prelude`.
The implementation of the proposal is delayed at least to GHC 9.6,
but one can already future-proof code to be
compliant with this change in a backwards-compatible way. No CPP required.
Migration guide and more info:
https://github.com/haskell/core-libraries-committee/blob/main/guides/export-lifta2-prelude.md (not yet merged, draft can be seen [here](https://github.com/googleson78/core-libraries-committee/blob/lifta2-guide/guides/export-lifta2-prelude.md)

Prepare for liftA2 being exported from Prelude

---

src/Text/Pandoc/Readers/LaTeX.hs
src/Text/Pandoc/Shared.hs
test/command/7525.md

parse `\texttt{\textbf{bold code}}` as `Strong [Code ("",[],[]) "bold code"]`
closes #7525

LaTeX: Handle bold inside tt

---

data/templates/article.jats_publishing

Using the default jats template of pandoc 2.18, the https://jats4r.org/jats4r-validator/ warns: "The license URI is given in @xlink:href. For JATS 1.1d3 and later, if the license is defined by a canonical URI, then it should be specified in the <ali:license_ref> child element."
I can confirm that what JATS4R recommends here is consistent with the JATS article packages found on the FTP site for the
PubMed Central Open Access Subset <https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/> (at least with the eLife article I looked at).
This proposed change follows the JATS4R recommendation and an example eLife article on the PubMed Central FTP site.

Follow JATS4R recommendation and PudMed Central

---

src/Text/Pandoc/Writers/HTML.hs
test/command/tasklist.md

Browser will display the extra newline character between checkbox and
text as a space, which make tasklist items cannot be aligned.
I just remove it.
before:
after:

Remove extra soft break for tasklist

---

doc/filters.md

Noto Sans CJK TC, that is suggested as a character set that contains Japanese characters, may not be suitable to properly display Japanese characters. Rather, Noto Sans CJK JP is much more recommendable for that purpose.
Although some characters originated from China are quite similar among countries/regions, most of them have evolved into different shapes in Mainland China, Hong Kong, Taiwan, Japan, Korea, and Vietnam. Therefore, it is best to use a character set that the language of the country/region uses for the readability/recongnizability sake. See also [an webpage that discusses the glyph appearance issue in Chinese, Japanese, Korean, and Vietnamese languages](https://heistak.github.io/your-code-displays-japanese-wrong/).
[README of Noto …

Update filter.md Noto Sans CJK TC -> JP

---

MANUAL.txt

In the manual, there is an indication that Math is rendered in all output formats, yet there is no mention of PowerPoint below, when specifying how it is rendered.

Document math support in PowerPoint

---

MANUAL.txt

I corrected some mistakes such as `yyyy[mm[dd]]]` (instead of `yyyy[mm[dd]]`) and `LaTex` (instead of `LaTeX`).
**Note:** `` `beameroption` `` appears with the first backtick in the HTML output, I do not know why that is.

Fix mistakes in the User’s Guide

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/Pandoc.hs

The set of supported input and output formats is made available to Lua
users.

Lua: add fields `pandoc.readers` and `pandoc.writers`.

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/System.hs

The module now has the additional functions `list_directory`,
`make_directory`, and `remove_directory`. This makes it easier to write
cross-platform scripts that need to inspect or modify the file system.

Lua: extend pandoc.system module.

---

MANUAL.txt

I've bumped into two links that broke because the section headings they link to have changed.

Fix links in manual

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release-candidate.yml

GitHub Action is sunsetting the macOS 10.15 Actions runner. It will stop working intermittently until being completely removed by 2022-8-30.
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
The PR bumps the `runs-on` from `macos-10.15` to `macos-11`.

CI: update macos container version

---

src/Text/Pandoc/App.hs

The mediabag is filled with document resources after the filters have
run. This allows, for example, filter authors to modify image paths
before pandoc tries to fetch the images.
Lua filters that rely on a filled mediabag can use the new
`pandoc.mediabag.fill` function to perform that action in the filter.
Closes: #8099

Populate mediabag after filters have run.

---

src/Text/Pandoc/Readers/Markdown.hs
test/command/4102.md
test/command/nested-spanlike.md

Spans with "smallcaps" as the first class are converted to *SmallCaps*
elements. While previously no other classes or attributes were allowed,
additional classes, attributes, and an identifier are not permitted and
kept in a *SmallCaps* wrapping *Span* element.
The same change is applied to underline spans, where the first class
must be either "ul" or "underline".
Closes: #4102

Markdown reader: allow more attributes in special spans

---

data/templates/styles.html
test/lhs-test.html
test/lhs-test.html+lhs
test/s5-basic.html
test/s5-fancy.html
test/s5-inserts.html
test/writer.html4
test/writer.html5

This allows to render an arbitrary number of columns, while the previous
approach assumed exactly two columns.

HTML: use CSS flex boxes for columns

---

src/Text/Pandoc/Class/PandocMonad.hs

Images that cannot be fetched are replaced with a Span that contains the
image's description. The span now also retains all original image
attributes and inherits all attributes of the image. Furthermore, the
classes `image` and `placeholder` are added, and path and title are
store in attributes `original-image-src` and `original-image-title`,
respectively.
Closes: #8099

fillMediaBag: Keep attributes of original image on Span

---

doc/lua-filters.md
src/Text/Pandoc/Lua/Module/Utils.hs

The function runs the *citeproc* processor on a Pandoc document.
Exposing this functionality to Lua allows to make citation processing
part of a filter or writer, simplifies the creation of multiple
bibliographies, and enables the use of varying citation styles in
different parts of a document.

Lua: add function `pandoc.utils.citeproc`

---

data/templates/styles.html
src/Text/Pandoc/Writers/HTML.hs
test/command/1710.md
test/lhs-test.html
test/lhs-test.html+lhs
test/s5-basic.html
test/s5-fancy.html
test/s5-inserts.html
test/writer.html4
test/writer.html5

The default `flex` and `overflow-x` properties of a column are set to
`auto`. In combination, these changes allow to get good results when
using columns with or without explicit widths.

HTML writer: revert to using `width` property for column widths

---

INSTALL.md

The current link on @master and on the _pandoc.org_ webpage brings to the site via a redirect: 
https://packages.fedoraproject.org//pandoc
which returns with a 404 site.
This PR fixes the link. I am not sure whether the pandoc.org site uses this very _INSTALL.md_ file or another one which I did not find; if so, please let me know so I could extend the current PR with updating the link there as well.

Fix link to fedora package site.

---

MANUAL.txt
src/Text/Pandoc/Readers/Markdown.hs
test/command/8174.md

This allows the combination of the fenced code block shortcut form with attributes, described in #8174:
````md
```haskell {.lineNumbers #id}
qsort [] = []
```
````
The code syntax class will be combined with the attribute classes, in this case `haskell` and `lineNumbers`.
This syntax allows for more intuitive writing of code blocks and for better compatibility with other Markdown parsers such as GitHub or Codeberg.
Code blocks using the old syntax on GitHub (`{.haskell .lineNumbers}`):
```{.haskell .lineNumbers}
qsort [] = []
```
Using the adapted shortcut form:
```haskell {.lineNumbers}
qsort [] = []
```
---
I'm new to such complex Haskell code, so feel free to suggest stylistic improvements.

Markdown reader: fenced code block shortcuts with attributes (#8174)

---

src/Text/Pandoc/Readers/HTML.hs
src/Text/Pandoc/Readers/MediaWiki.hs
test/command/2649.md
test/mediawiki-reader.native

Currently mediawiki table cells are constructed by `simpleCell` which unable to pass rowspan & colspan attributes. But [wikitext table syntax supports rowspan & colspan attributes](https://en.wikipedia.org/wiki/Help:Table#Combined_use_of_COLSPAN_and_ROWSPAN) like HTML tables. This PR would parse mediawiki span attributes like HTML table parser.
Code changes from #8200 are included here too.

Parse mediawiki table cell with attribs, to support rowspan, colspan

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/App.hs
src/Text/Pandoc/Shared.hs
test/command/6384.md
test/command/file1.txt
test/command/file2.txt

This change only affects the case where `--file-scope` is used and more than one file is specified on the command line.
In this case, identifiers will be prefixed with a string derived from the file path, to disambiguate them. For example, an identifier `foo` in `contents/file1.txt` will become `contents__file1.txt__foo`.  Links will be adjusted accordingly: if `file2.txt` links to `file1.txt#foo`, then the link will be changed to point to `#file1.txt__foo`.  Similarly, a link to `file1.txt` will point to `#file1.txt`.  A Div with an identifier derived from the file path will be added around each file's content, so that links to files will still work.
Closes #6384.
[API change]: Text.Pandoc.Shared exports `textToIdentifier`.

Add prefixes to identifiers with `--file-scope`.

---

MANUAL.txt
Makefile
doc/pandoc-lua.md
pandoc-cli/src/pandoc.hs
pandoc.cabal
src/Text/Pandoc/Lua.hs

A program name of `pandoc-lua`, e.g., when the binary was invoked through a symlink with that name, will make pandoc behave like a Lua interpreter: the first command line argument is run as a Lua script, and the remaining arguments are passed to the interpreter in the global table `arg`. Lua options are not supported yet.

Make pandoc behave like a Lua interpreter when called as `pandoc-lua`.

---

doc/filters.md

I noticed that you already use it on the same page and thought that it'd make it more consistent (not to mention, more fail-safe).

doc: use cabal's --package-env more

---

src/Text/Pandoc/Writers/RST.hs
test/command/4564.md

When a table is marked with a "list-table" attribute class, it will now be rendered using the list table syntax documented here http://docutils.sourceforge.net/docs/ref/rst/directives.html#list-table

rST writer: list tables rendering, closes #4564

---

data/sample.lua
doc/custom-writers.md
pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Init.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Pandoc.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/PandocLua.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Writer.hs
pandoc-lua-engine/test/Tests/Lua/Writer.hs
src/Text/Pandoc/App/OutputSettings.hs
src/Text/Pandoc/Scripting.hs

New-style custom Lua writers can now define an alternative entry function `ByteStringWriter`. If a function with that name is defined, then pandoc will treat the returned string as binary output. This allows to generate formats like docx and odt with custom writers.
`T.P.Lua.writeCustom` function changed to reflect the possibility of a ByteString writer being returned.
Closes: #8313

[API Change] Support binary custom writers.

---

pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Init.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Format.hs
pandoc-lua-engine/test/Tests/Lua/Module.hs
pandoc-lua-engine/test/lua/module/pandoc-format.lua

The module provides functions to query the set of extensions supported by formats, and the set of extension enabled per default.

Lua: add new module `pandoc.format`.

---

data/templates/default.latex
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

Beamer themes such as metropolis and saintpetersburg change the default fonts. This PR gives precedence to the user font settings by moving them after the loading of the Beamer theme.
This fixes #6260

latex template: set fonts after Beamer theme

---

doc/lua-filters.md

Zerobrane IDE does not yet include Lua 5.4. I had tried to get 5.3 working with pandoc debugging but the debugger never triggered. Then I used a 5.4 install (I installed from homebrew) with mobdebug and luasocket installed. Setting this in Zerobrane's settings and configuring it in the IDE and remote debugging worked again. I've modified the instructions. Note I'm not a Lua person so I hope the details are clear...

Update Lua filter doc: modify Zerobrane instructions to use Lua 5.4

---

src/Text/Pandoc/Readers/Org/Inlines.hs
test/Tests/Readers/Org/Inline.hs
test/Tests/Readers/Org/Meta.hs

The main issue with the original implementation is that it kept the assumption that no emphasis markers may occur directly after most non-whitespace chars, e.g. in the middle of the word (in Pandoc terms: following native `Str`). But with the possibility to modify which chars are allowed around emphasized text, Pandoc should remain indifferent in that respect.
These commits allow it and modify some tests accordingly. This is both:
1. in accordance with Org-mode's behavior when customizing `org-emphasis-regexp-components`.
2. reasonable in many languages[^1] (but rare in English).
Resolves #8059.
[^1]: which is the case in Hebrew and German, both of which I speak.

Make #+pandoc-emphasis-pre work as expected (#8059)

---

doc/lua-filters.md
pandoc-lua-engine/src/Text/Pandoc/Lua/Marshal/Context.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Template.hs

The functions converts Meta values to template contexts; the intended use is in combination with `pandoc.template.apply`.

Lua: add function `pandoc.template.meta_to_context`.

---

.gitattributes
doc/custom-writers.md
pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Writer.hs
pandoc-lua-engine/test/Tests/Lua/Writer.hs
pandoc-lua-engine/test/writer-template.lua
pandoc-lua-engine/test/writer-template.out.txt
src/Text/Pandoc/App/OutputSettings.hs
src/Text/Pandoc/Scripting.hs

The template is only used if no template file is found in the *templates* data directory. Custom template files in `data/templates/` are expected to have a `.tmpl` extension.
Example use (using an example from pandoc-discuss):
``` lua
local stringify = pandoc.utils.stringify
function Writer (doc, opts)
assert(doc.blocks[1] and doc.blocks[1].t == 'Table', 'expected a table')
local tbl = pandoc.utils.to_simple_table(doc.blocks[1])
local result = pandoc.List{}
for _, row in ipairs(tbl.rows) do
local meta = pandoc.Meta(doc.meta)   -- clone
for i, cell in ipairs(tbl.header) do
meta[stringify(cell)] = pandoc.utils.blocks_to_inlines(row[i])
end
result:insert(pandoc.write(pandoc.Pandoc({}, meta), 'markdown', opts))
end
return table.concat(result, '\f\n') .. '\f\n'
end
Template = …
```

Lua: Allow custom writers to define a default template

---

MANUAL.txt
src/Text/Pandoc/Error.hs
src/Text/Pandoc/Parsing.hs
src/Text/Pandoc/Parsing/General.hs
src/Text/Pandoc/Readers/BibTeX.hs
src/Text/Pandoc/Readers/CSV.hs
src/Text/Pandoc/Readers/CommonMark.hs
src/Text/Pandoc/Readers/DokuWiki.hs
src/Text/Pandoc/Readers/LaTeX.hs
src/Text/Pandoc/Readers/LaTeX/Citation.hs
src/Text/Pandoc/Readers/Man.hs
src/Text/Pandoc/Readers/Muse.hs
src/Text/Pandoc/Readers/RST.hs

T.P.Parsing now exports `fromParsecError`, which can be used to turn a parsec ParseError into a regular PandocParseError (the appearance to the user should be unchanged in every case).
[API change]
Closes #8382.

T.P.Error: Remove PandocParsecError constructor from PandocError.

---

MANUAL.txt

Previous versions of the documentation did not clarify much which options of font selection are available for the generation of .pdf via `-t ms`.  Nor was there a description how to extend the set of of fonts provided by ghostscript/pdfgroff.  This commit equally hints to Peter Schaffter's script install-fonts.sh to facilitate greatly the later, too.
This PR addresses some of the findings relevant to the issue report filed earlier ([issue 8405](https://github.com/jgm/pandoc/issues/8405)).

clarify font selection for pdf -t ms

---

data/templates/styles.html
test/lhs-test.html
test/lhs-test.html+lhs
test/writer.html4
test/writer.html5

When creating PDF output via HTML the background of `body` element is `transparent`, so it uses the color of `html` which is set to `#fdfdfd` by default. This may potentially lead to wasted printer ink. The introduced fix changes the default color for printing to `white` while respecting the case of user setting a custom background color.
Run
```sh
$ echo foo | pandoc -o foo.pdf -t html
```

Change default background color of PDFs generated via HTML

---

MANUAL.txt
data/templates/default.latex
man/pandoc.1
test/lhs-test.latex
test/lhs-test.latex+lhs
test/writer.latex
test/writers-lang-and-dir.latex

It would be neat if there was an option to change the URL style for LaTeX documents with an option. By default, Pandoc sets the `urlstyle` to `same` which I do not like because it results in me being unable to differenciate URLs and regular text. If you still want to set the default to `same`, feel free to make that change in my pull request.

Add LaTeX option `urlstyle`

---

src/Text/Pandoc/Writers/HTML.hs
src/Text/Pandoc/Writers/MediaWiki.hs
src/Text/Pandoc/Writers/Shared.hs
test/Tests/Old.hs
test/command/4794.md
test/tables.mediawiki
test/tables/nordics.mediawiki
test/tables/planets.mediawiki
test/tables/students.mediawiki

~~Fixes issue #6992~~ (on closer reading, that issue seems to be about the mediawiki reader, this fixes the writer.)
Now the MediaWiki tables can have colspan and rowspan.
The align-attribute has been replaced with a styling option.
See https://www.mediawiki.org/wiki/Help:Tables for more info on formatting mediawiki tables. As can be read there, mw tables do not have the possibility of having `thead`/multiple `tbody`s/`tfoot` or `colgroup`, so I ignored quite a lot of information regarding those.
Most of the code is similar to the html writer, which is why I moved some html-functions to the Shared file, such that it could also be used by mediawiki. 
I am very unexperienced with Haskell, and eager to learn, so please do not hesitate to give codestyle tips or other feedback.
Edit: I also …

Rewrite the MediaWiki Writer to use the new tables

---

pandoc-lua-engine/pandoc-lua-engine.cabal

Tested with GHC 9.2.4 by running `for action in build test ; do cabal $action --enable-tests --constrain 'mtl == 2.3.1' --allow-newer=jira-wiki-markup:mtl --allow-newer=servant-server:mtl --allow-newer=servant:mtl || break ; done`.
The bound in jira-wiki-markup will be bumped by https://github.com/tarleb/jira-wiki-markup/pull/21. I couldn't update the Servant code, so perhaps this PR should be blocked until they bumped it themselves.

Allow mtl 2.3.1

---

src/Text/Pandoc/Readers/Textile.hs
test/command/2465.md

Firstly, thanks for the awesomeness that is Pandoc! 
I recently ran into a need to read Textile ordered lists that do not restart at 1, and stumbled across this issue #2465. 
According to [the docs](https://textile-lang.com/doc/numbered-ordered-lists), Textile supports two means of starting a list at a number other than 1:
1. the start attribute
```
#8 Item 8
```
2. the continuation character `_`
This PR looks for the start attribute (if any), and `readMaybe`s it to the `ListAttribute` of the ordered list.
I'm not really sure how to handle the continuation character using Parsec without introducing a whole second pass or changing the list attributes to capture "continue numbering" and modifying the start `Int` it afterwards... But with this small change I believe the start attributes …

Textile reader: Add parser to look for ordered list start numbers

---

doc/custom-readers.md
doc/lua-filters.md
pandoc-lua-engine/src/Text/Pandoc/Lua/Marshal/Format.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Pandoc.hs
pandoc-lua-engine/test/Tests/Lua/Writer.hs
pandoc-lua-engine/test/lua/module/pandoc.lua
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Format.hs

This allows to pass structured values as format specifiers to
`pandoc.write` and `pandoc.read`.

Lua: allow table structure as format spec.

---

doc/lua-filters.md
pandoc-lua-engine/pandoc-lua-engine.cabal
stack.yaml

Lua: add function `pandoc.text.toencoding`.

---

src/Text/Pandoc/Writers/DocBook.hs
test/Tests/Writers/DocBook.hs

Markdown allows marking a heading as unnumbered, which is stored as a class token internally. This change will recognize this particular class token and append it to the role attribute, or create a role attribute with it if needed. This does not imply any processing in DocBook but is intended to let customized stylesheets identify these sections and act accordingly.
The enrichRole function is intentionally designed to be able to take more class tokens in the future by extending the `cand` list
fixes #1402

Store "unnumbered" class in DocBook role attribute

---

src/Text/Pandoc/Readers/MediaWiki.hs

This PR would fix wrong link text for Chinese or JCK languages which words are not seperated by blank space. Could anyone share the purpose for this `linktrail` variable?
For example:
`是[[台灣|台式]]的傳統[[月餅]]`
would be parsed as below, which is abviously unreasonable.
```
{
"t": "Str",
"c": "是"
},
{
"t": "Link",
"c": [
[
"",
[],
[]
],
[
{
"t": "Str",
"c": "台式的傳統"
}
],
[
"台灣",
"wikilink"
]
]
},
{
"t": "Link",
"c": [
[
"",
[],
[]
],
[
{
"t": "Str",
"c": "月餅"
}
],
[
"月餅",
"wikilink"
]
]
},
```
After this fix, json output would be:
```
{
"t": "Str",
"c": "是"
},
{
"t": "Link",
"c": [
[
"",
[],
[]
],
[
{
"t": "Str",
"c": "台式"
}
],
[
"台灣",
"wikilink"
]
]
},
{
"t": "Str",
"c": "的傳統"
},
{
"t": "Link",
"c": [
[
"",
[],
[]
],
[
{
"t": "Str",
"c": "月餅"
}
],
[
"月餅",
"wikilink"
]
]
},
```
Original data: …

Fix MediaWiki reader on internalLink for JCK languages

---

MANUAL.txt
data/templates/default.context
src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Writers/ConTeXt.hs
test/writer.context

Paragraphs are enclosed by `\startparagraph` and `\stopparagraph`
commands. This ensures better tagging results in PDF output.

ConTeXt writer: tag paragraphs

---

src/Text/Pandoc/Extensions.hs
src/Text/Pandoc/Readers/CommonMark.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Writers/Markdown/Inline.hs
test/Tests/Readers/Markdown.hs
test/command/wikilinks_title_after_pipe.md
test/command/wikilinks_title_before_pipe.md

Adds commonmark extensions `wikilinks_title_after_pipe` and
`wikilinks_title_before_pipe`. The former enables links of style `[[Name
of page|Title]]` and the latter `[[Title|Name of page]]`. Titles are
optional in both variants, so this works for both:
`[[https://example.org]]`, `[[Name of page]]`.
The writer is modified to render links with title `wikilink` as a
wikilink if a respective extension is enabled.
Pandoc will use `wikilinks_title_after_pipe` if both extensions are
enabled.
Closes: #2923

Markdown, CommonMark: add support for wiki links. [API change]

---

doc/lua-filters.md
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/MediaBag.hs
src/Text/Pandoc/Class/IO.hs

Allows to write the complete mediabag, or just a specific file, to a given directory.

Lua: Add function `pandoc.mediabag.write`.

---

MANUAL.txt

(just `compact_definition_lists` doesn't get autolinked)

Refer to proper section name

---

src/Text/Pandoc/Readers/Textile.hs
test/textile-reader.textile

Backlinking from footnotes is already the behavior of `Note` values when writing HTML. This adds parsing support for the explicit backlinking syntax in Textile as described here:
https://textile-lang.com/doc/footnotes
Previously, these lines would be interpreted as a new paragraph beginning with "fn2^." in text.

Add support for Textile footnote backlinks

---

README.template

required to correct also in README.md

correct year in footer for licensing (2022->2023)

---

doc/lua-filters.md
pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Init.hs
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/JSON.hs
pandoc-lua-engine/test/Tests/Lua/Module.hs
pandoc-lua-engine/test/lua/module/pandoc-json.lua
stack.yaml

- Use latest pandoc-lua-marshal release, version 0.2.1.
- Lua: add module `pandoc.json` to handle JSON encoding

Provide a pandoc.json Lua module

---

MANUAL.txt
data/templates/default.context
test/writer.context
test/writers-lang-and-dir.context

I have added `\setupurl[style=]` to the ConTeXt template, and updated the relevant tests. This gives the same default behaviour as the LaTeX template, which is that URLs are the same as the main text.

URL style in ConTeXt

---

doc/lua-filters.md
pandoc-lua-engine/pandoc-lua-engine.cabal
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/System.hs
stack.yaml

The function returns the CPU time consumed by pandoc and can be used to
benchmark Lua computations.

Lua: add new function pandoc.system.cputime.

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-xref.docbook
test/docbook-xref.native

_xref_ elements can also be used to link to _table_ elements. The DocBook reader did not correctly select the content of the referenced _table_'s _title_. The problem of link name selection is rather complex, as described in #8065. But it seems that the most used target elements have been covered so far. 
Closes #8626.

fixed <xref> references to tables in DocBook files

---

doc/lua-filters.md

Changed:
"Filter the given doc by passing it through the a JSON filter."
to:
"Filter the given doc by passing it through a JSON filter."

Doc: fix typo in run_json_filter

---

data/templates/default.asciidoc
data/templates/default.asciidoctor

Revision line syntax [is only valid in combination with an author line](https://docs.asciidoctor.org/asciidoc/latest/document/revision-line/#when-can-i-use-the-revision-line). The documentation indicates that [the metadata attributes must be set explicitly](https://docs.asciidoctor.org/asciidoc/latest/document/revision-attribute-entries/) when the author line is missing, so the template has been updated to match.
Fixes #8637

asciidoc{,tor} template: fix revision date when author is unset

---

data/templates/default.latex

The XeLaTex supports `CJKsansfont` and `CJKmonofont` which is useful to change the CJK fonts for titles and codes.
The following args were tested and worked well.
```
---
mainfont: "Noto Serif SC"
sansfont: "Noto Sans SC"
monofont: "Ubuntu Mono"
CJKmainfont: "Noto Serif SC"
CJKsansfont: "Noto Sans SC"
CJKmonofont: "Noto Sans SC"
...
```

feat: Add CJKsansfont and CJKmonofont for XeLatex

---

data/templates/default.latex

Fix background image in Beamer when there are figure environments, replicating the pull request done in the pandoc-templates repository with the updated template.

Fix background image in Beamer when there are figure environments

---

src/Text/Pandoc/Writers/HTML.hs

Many EPUB readers are thrown off by pandoc's current footnote output.  Both the ol and the fact that the footnote backlink is at the end of the note seem to pose problems.
With this commit, we now create a list of aside (or div) elements, instead of an ordered list. Each element begins with a note number that is linked back to the note reference.  (So, the backlink occurs at the beginning rather than the end.)
References:
- https://kindlegen.s3.amazonaws.com/AmazonKindlePublishingGuidelines.pdf
- http://kb.daisy.org/publishing/docs/html/notes.html
Obsoletes #8672, closes #5583.
Thanks to @Porges and @lewer.

HTML writer: Use different structure for epub footnotes.

---

pandoc.cabal

Exposed the `Text.Pandoc.App.FormatHeuristics` module.

expose formatFromFilePaths (jgm#7590)

---

src/Text/Pandoc/Readers/Org/Inlines.hs
src/Text/Pandoc/Readers/Org/ParserState.hs
test/Tests/Readers/Org/Inline.hs

Allow the character U+200B to be used as an escape character as described in the Org-mode documentation https://orgmode.org/manual/Escape-Character.html
Closes issue #8716.

Org reader: Allow zero width space as an escape character

---

doc/org.md

Add zero width space to the default values of pandoc-emphasis-pre and pandoc-emphasis-post. Zero width space was added to solve issue #8716.

Update documentation for org-mode

---

src/Text/Pandoc/Writers/MediaWiki.hs
test/command/8738.md

Fixes issue https://github.com/jgm/pandoc/issues/8738
I am not sure if this is the most desired way to do it.
Other thing to consider:
```hs
removeLinks :: [Inline] -> [Inline]
removeLinks = walk go
where
go (Link _ ils _) = Underline ils
go x = x
```

Remove links from inside links in mediawiki writer

---

src/Text/Pandoc/Readers/JATS.hs
test/jats-reader.native
test/jats-reader.xml

See [this issue](https://github.com/jgm/pandoc/issues/8408) for background
Parse the colspan, rowspan and alignment attributes of Jats table into the Cell node

Add rowspan, colspan and alignment to cells in jats table reader

---

MANUAL.txt

The section about pandoc's template syntax used to state that
spaces and tabs following the closing delimiter around variables
and control structures will be ignored. Some quick testing with
pandoc version 2.9.2.1 suggests that this is not the case. Spaces
and tabs _preceding_ the closing delimiter, however, are indeed
ignored. I therefore assume that this is simply a slight inaccuracy
in the manual; possibly produced by copying the sentence about the
opening delimiter and forgetting to adjust that word.

Fix apparent inaccuracy in MANUAL.txt

---

data/templates/default.epub2
data/templates/default.epub3

Hi,
in default.epub2 and default.epub3 templates, the `lang` attribute is missing in the `<html>` tag (it is there in the default.html4 and default.html5 templates)
This has the effect of raising USAGE(HTM_021) [Content file doesn't contain lang attribute.] when checking the epub with epubcheck. When setting the `lang` attribute, the usage message disappears.
Following https://kb.daisy.org/publishing/docs/html/lang.html
>Is it necessary to specify both the lang and xml:lang attributes?
>
>For optimal accessibility both should be specified when creating XHTML content. Assistive technologies may only recognize one or the other attribute.

Add lang attribute to html tag in epub tpl

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/command/8256.md

The only element in meta for which data/templates/default.opendocument
allows block element content appears to be "abstract", which is already
filtered out of meta' at this point, so simply convert all blocks to
linebreak-separated inlines.
Fixes: #8256

    Writers.OpenDocument: fix invalid text:p inside text:p from meta

---

src/Text/Pandoc/Writers/OpenDocument.hs
test/command/8764.md

not sure if the 2nd commit is a good idea, guess it depends on how "common" various different shapes of HTML (or other) tables are, please read the commit message...

8764 Writers.OpenDocument: don't lose row header column

---

MANUAL.txt

This PR appears also to have deleted some trailing spaces in other parts of the file. Hope that's OK.

MANUAL: Note that fancy_lists don't work with commonmark

---

MANUAL.txt

It should have the same labels as the table that comes 10 lines later. I didn't file an issue for this since it's so small.

MANUAL: fix typo

---

src/Text/Pandoc/Readers/JATS.hs
test/jats-reader.native
test/jats-reader.xml

Fixes #8718
There were a number of elements where the jats reader did not parse their `title` and `label` into headers. This PR fixes that

Improve title and label parsing in the Jats reader

---

src/Text/Pandoc/Readers/JATS.hs
test/jats-reader.native
test/jats-reader.xml

Fixes: #8765
Essentially the Jats reader was not parsing table footers or multiple bodies, which are both valid jats XML.

Add Footer and Multiple body parsing to Jats table reader

---

pandoc-lua-engine/pandoc-lua-engine.cabal

Should fix the following error when running tests from Hackage tarball:
```
pandoc.mediabag:                            [WARNING] Could not fetch resource lua/module/sample.svg: replacing image with description
FAIL
fetch // populates media bag:
File lua/module/sample.svg not found in resource path
DEBUG:root:haskell-pandoc-lua-engine:
fill // populates media bag:
lua/module/pandoc-mediabag.lua:70:
expected values to be equal, got 'nil' and 'image/svg+xml'
```

Include lua/module/sample.svg in hackage tarball

---

src/Text/Pandoc/Writers/MediaWiki.hs

Fix for this SO question: https://tex.stackexchange.com/questions/563778/how-to-get-f-syntax-highlighting

fix: add highlight for F# language

---

INSTALL.md

- Updated Arch link (previous one was 404'ing)
- Standardised some other links that weren't pointing to the package or the distro-specific search results

Update Linux install links

---

pandoc-lua-engine/src/Text/Pandoc/Lua/Init.hs
src/Text/Pandoc/Logging.hs

Lua 5.4 added the option to raise warnings with the `warn` function. This PR adds these warnings to the list of log messages and reports them together with the other logging events.
E.g.
``` lua
warn('This is the last warning!')
print(pandoc.json.encode(PANDOC_STATE.log[#PANDOC_STATE.log]))
```
```
[WARNING] Lua warning at ../testing/test.lua:1:  This is the last warning!
{"message":"This is the last warning!","position":"../testing/test.lua:1: ","type":"LuaWarning","verbosity":"WARNING"}
```

Integreate Lua warnings in pandoc's logging system.

---

INSTALL.md

Pandoc's default engine to generate pdf is LaTeX.  In reply
to an issue report,[1] and with the documentation in mind,
INSTALL.md now hints one can equally use other tools for this
task, too.
[1] https://github.com/jgm/pandoc/issues/8769

mention alternatives to LaTeX to generate pdf

---

src/Text/Pandoc/Readers/Textile.hs
test/textile-reader.native
test/textile-reader.textile

Textile supports what it calls a "link alias", which is analogous to Markdown's reference-style links.
During the parser's first-pass, we can collect link references in addition to footnotes. Textile differs from Markdown in that reference definitions don't have titles nor attributes, so the stored values in `stateKeys` is relatively sparse.
I modeled the parser after the Markdown, and the new test cases are passing, but let me know if there's anything essential from Markdown's reference parsing that I missed.

Textile reader: Add support for link references

---

src/Text/Pandoc/Readers/HTML/Table.hs
test/html-reader.html
test/html-reader.native

Recently I noticed that if a HTML table have different number of leading `th` tag in each row, colspan would be lost and some `td` cells would be converted to `th` cells. I looked into the HTML table parsing code, and currently the `TableBody` data struct assume each row have the same number of leading `th` tags.
This PR will set `RowHeadColumns` to the minimum value of each row, to reduce such abnormal colspan cases. Actually I believe this `RowHeadColumns` should be discarded, and we should move `CellType` to `Cell` attribute instead.
For example the Infobox in this page: https://en.wikipedia.org/w/index.php?title=Anna_Sorokin&oldid=1139601226 , the image is in a `td` cell with `colspan="2"`, but for the rows below, each row got one leading `th` cell.

Update TableBody RowHeadColumns caculation: change from max to min

---

MANUAL.txt
src/Text/Pandoc/App/CommandLineOptions.hs

This pull request introduces an optional value to the --embed-resources flag. To ensure backward compatibility, the default value is set to true unless false is explicitly provided.
Resolves #8788

Fix for #8788: update boolean flags to take an optional 'true' or 'false' value

---

stack.yaml

Without this, some dependencies refuse to build.

stack: add pkg-config to nix packages

---

stack.yaml

Commit 921b0949f4400af2e602982806e48222b7611bd9 bumped the skylighting-core version, which requires a newer version of xml-conduit than is available in lts-21.0.
Bump the version in stack.yaml

Fix build (transitive dep not in lts)

---

doc/faqs.md

Fixes the link to the manual that wasn't creating an anchor tag in HTML on line 119.
I also suggest that the link to the issue had a text like the all other links in this page.

Documentation - FAQs - Links

---

data/templates/styles.html

Converting to standalone html uses a template with a type with a semicolon where there should be a colon in the inline CSS.

Change semicolon to colon in inline CSS in HTML template

---

src/Text/Pandoc/Readers/Org/BlockStarts.hs
test/command/8997.md

See the regexp at https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/org-element.el?h=d1e4b9351941aa9241ab3aa0a34256376b7eca94#n2420.
Fixes #8997.

Org reader: allow example lines to end immediately after the colon

---

src/Text/Pandoc/Readers/JATS.hs

Replacement of wrong element name "attribution" by the correct one "attrib"

Correct name of JATS element <attrib>

---

src/Text/Pandoc/Readers/Org/Inlines.hs
test/Tests/Readers/Org/Inline.hs

Fixes https://github.com/jgm/pandoc/issues/9025

Org reader: allow escaping commas in macro arguments

---

src/Text/Pandoc/Writers/HTML.hs
test/command/4235.md

In general, the ID prefix makes it possible to combine multiple pieces of Pandoc-generated HTML with no possibility that IDs will conflict. One exception to this was that the footnotes were always put into an element like
<aside id="foonotes" ...>
This commit applies the ID prefix to this ID as well.

HTML writer: use the ID prefix in the ID for the footnotes section.

---

src/Text/Pandoc/Readers/JATS.hs
test/jats-reader.xml

The content of the <processing-meta> element is metadata and as such we fix it so that it is not displayed in the output.

Ignore <processing-meta> element

---

data/templates/default.latex

When using a CSL style which has an item with the `display="block"` attribute, the vertical space after the block depends on if the block item is the last item of the bibitem, or otherwise. This fixes that. Examples with the block item bordered by an `\fbox` for illustration:
---
---
---

LaTeX template: fix \CSLBlock vertical space

---

data/epub.css

This PR contains mostly cosmetic changes, namely:
1. Combine identical styles
2. Wrap to 80 characters
3. Use consistent whitespace for brackets and indentation
It also includes one meaningful change:
1. Apply styles to `h6`. It looks like there was a typo in the previous rules, with two sets being applied to `h5` and none to `h6`.
Thanks for this incredible piece of software!

Clean up epub CSS

---

src/Text/Pandoc/Writers/HTML.hs

This PR attempts to close out the `HTML` writer portion of #8880. 
The change implement seeks to check whether `f` is part of the supported HTML slide formats. Thus, if we have a code block in `revealjs` of:
````md
```{=revealjs}
Hello there!
```
````
The text will be retained and treated as raw in the output format, e.g. 
```
Hello there!
```
Presently, the text will be deleted in the output, e.g. 
````md
````
We've supplied a sample test document.
If this is okay, we can submit a follow-up PR to address the EPUB issue or add it into this PR.
<details>
<summary> Test Markdown Document </summary>
````markdown
---
title: Test HTML Raw Fix
author: JJB
date: Sept 29, 2023
---
```{=revealjs}
Retain this text as we're under `revealjs`
```
```{=s5}
Retain this text as we're under `s5`
``` …
```

Check if supplied FORMAT matches with an HTML slide deck value. Return True for isRawHtml.

---

MANUAL.txt

https://github.com/jgm/pandoc/issues/8737

Fix legacy option for citation in `MANUAL.txt`

---

src/Text/Pandoc/Readers/LaTeX/SIunitx.hs

In the siunitx implementation, the abbreviation for "astronomicalunit" is currently "ua". It should be "au" (see table 3 of the [official documentation](https://ctan.mirrors.hoobly.com/macros/latex/contrib/siunitx/siunitx.pdf)). This PR corrects that.

Fix abbreviation for astronomical unit

---

src/Text/Pandoc/Readers/Creole.hs

Handle empty table cells of the form `|||` correctly.  Without this fix empty cells must at least contain one space like so `| | |` which shouldn't be necessary.

Handle empty cells correctly in creole reader. Fixes #9141

---

src/Text/Pandoc/Extensions.hs

`Ext_pipe_tables` and `Ext_raw_html` each appear two times in the list. This commit deletes 2nd occurrence of each.
```haskell
getDefaultExtensions "commonmark_x"    = extensionsFromList
[ Ext_pipe_tables
, Ext_raw_html
, Ext_gfm_auto_identifiers
, Ext_strikeout
, Ext_task_lists
, Ext_emoji
, Ext_pipe_tables
, Ext_raw_html
, Ext_smart
, Ext_tex_math_dollars
, Ext_superscript
, Ext_subscript
, Ext_definition_lists
, Ext_footnotes
, Ext_fancy_lists
, Ext_fenced_divs
, Ext_bracketed_spans
, Ext_raw_attribute
, Ext_implicit_header_references
, Ext_attributes
, Ext_yaml_metadata_block
]
```

remove duplicates for Ext_raw_html and Ext_pipe_tables

---

src/Text/Pandoc/Writers/Typst.hs
test/writer.typst

An `#image` by itself in typst is a block-level element. To force images to be inline (as they are in pandoc), we need to add a box with an explicit width. When a width is not given in image attributes, we compute one from the image itself, when possible.
Closes #9104, supersedes #9105.

Typst writer: add `#box` around image to make it inline.

---

data/templates/default.typst

Typst now supports CSL for its native citation engine, so Pandoc should pass that as a priority in the template, falling back to `bibliographystyle`
https://typst.app/docs/reference/meta/bibliography/

Update default.typst to support csl

---

src/Text/Pandoc/Readers/LaTeX/Math.hs
test/command/8872.md

This patch addresses the bug raised in #8872.
In the current implementation , theorem labels in `theoremEnvironment` are determined by the `LastLabel` in the current state. This approach works well when the `\label{thm}` is placed at the end of the theorem body (, which is a standard place to put a label.)
However, when a label is placed at the beginning of the theorem (another common practice) and additional labels follow in the theorem body, `theoremEnvironment` incorrectly picks the last label (e.g., `\label{item2}` in #8872).
This patch addresses the issue by extracting the label extraction independently of the `LastLabel` state.

Fixed theorem label issue in Latex

---

src/Text/Pandoc/App.hs
src/Text/Pandoc/Writers/LaTeX.hs
test/Tests/Writers/LaTeX.hs

Latex Writer converts
`emph (str "This sentence" <> note (para (str "paragraph1") <> para (str "paragraph2")) <> str " has footnote.")` to
`"\\emph{This sentence}\\footnote{paragraph1\n\n  paragraph2}\\emph{ has footnote.}"` instead of
`"\\emph{This sentence\\footnote{paragraph1\n\n  paragraph2} has footnote.}"`

Bug fix for the Latex writer issue #8982

---

src/Text/Pandoc/Readers/Docx/Parse.hs
src/Text/Pandoc/Writers/Docx.hs

Header and footer references may be absolute in the reference.docx.
E.g. editing it with dotnet's Open-XML-SDK causes this error:
```
+ pandoc test.md -t docx --reference-doc referenceh.docx -o test.docx
word//word/header1.xml missing in reference docx
```
There was already code in pandoc to handle relative vs absolute paths in references, so use it.
Modified [referenceh.docx](https://github.com/jgm/pandoc/files/13763071/referenceh.docx) produced by the following F# code:
(for convenience creating, building, running the F# code and then pandoc on the new reference.docx is all in a single script below)
```
#!/bin/sh
set -eu
dotnet new console -lang F# -o AddHeader -f net6.0 >/dev/null
cd AddHeader
dotnet add package DocumentFormat.OpenXml >/dev/null
cat >Program.fs <<EOF
open System.Linq …
```

fix(docx): support absolute header/footer paths

---

.github/workflows/commit-validation-pr.yml
.github/workflows/commit-validation.yml

The PR event doesn't include the actual commits, just a count and a URL to fetch it.
But we've already checked out the entire git history, so we might as well use `git` itself to walk the commit history.
(Using the remote commits URL would be useful only if we'd want to do a shallow clone because we have too many commits)
We can revisit this once pandoc's commit history grows large enough that this takes too long. For now it should unblock the CI.

ci(commit-validation): use git to walk commits

---

data/templates/default.latex

Fixing #8803 . The changes introduced in #8707 makes the highlighting works with lualatex, but changes in the template are still needed for pdflatex and xelatex. I tested these changes with pdflatex and lualatex both with standard and beamer output and it works.

Fix beamer highlights

---

src/Text/Pandoc/Readers.hs
test/Tests/Readers/Man.hs

It looks like `readMan` is missing in the list of exports of the module `Text.Pandoc.Readers`. I couldn't see why, so I've added it here.

Add `readMan` to `Text.Pandoc.Readers` exports

---

data/templates/default.latex

This allows low-effort PDF generation from Unicode source.
e.g. I can write `src.md`:
```markdown
---
title: Demo Document
mainfont: Latin Modern Sans
mainfontfallback:
- "FreeSans:"
- "NotoColorEmoji:mode=harf"
---
Look, the empty set! → ∅ ←
Emoji work too 😎!
```
Then convert with `pandoc -s src.md -o out.pdf --pdf-engine=lualatex`
The PDF file then contains the Unicode as expected:
Notes:
* Only the `lualatex` PDF engine is supported
* Since this patch calls `luaotfload`
* Other PDF engines are unaffected
* `mainfont`, `sansfont`, and `monofont` can each be given a separate fallback chain
* For each `XXXfontfallback` to work, the YAML option `XXXfont` must also be set
* I could not work out how to control `fontspec` without knowing the names of fonts

LaTeX template: support font fallback

---

data/templates/default.latex

Follow up to #9204. Also sets `mainfontfallback` when the main font is set with `\babelfont`.

LaTeX writer: set font fallback for babel main font

---

pandoc-lua-engine/src/Text/Pandoc/Lua/Custom.hs

The CommonState (`PANDOC_STATE` in Lua) may change between the time that a custom writer script is first loaded and when the writer is run. However, the writer was always using the initial state, which led to problems, e.g. when the mediabag was updated in a filter, as those updates where not visible to the writer.
The state is now updated right before the writer function runs.
Fixes: #9229

Custom writers: fix handling of common state

---

src/Text/Pandoc/Writers/Texinfo.hs
test/command/8534.md

Fixes #8534
Implements @jgm's suggestion, checking if the "variable" class is contained in the attributes, and without consolidation of adjacent code elements.

Add @var support in Texinfo Writer #8534

---

src/Text/Pandoc/Writers/EPUB.hs
src/Text/Pandoc/Writers/HTML.hs

Roles are added to some elements within epub for accessibility best practices.
Footnote references are given role "doc-noteref",footnote text gets
"doc-footnote", and nav gets "doc-toc". Cf.
https://kb.daisy.org/publishing/docs/html/roles.html for reference.

EPUB accessibility: roles

---

MANUAL.txt

Markdown and MultiMarkdown are proper nouns and thus start with an uppercase letter.

Harmonize spelling of Markdown and MultiMarkdown

---

.github/workflows/docx-validation.yaml
tools/validate-docx2.sh

Upstream https://github.com/mikeebowen/OOXML-Validator/commit/29af1086b5c78b6a213e70d2e1cb8da2a8e5b876 has added support for building with .Net 8.0.
But that means OOXML-Validator can now be built for both .Net 6.0 and .Net 8.0, so we need to pick which one we want when running, otherwise we get an error:
```
Unable to run your project
Your project targets multiple frameworks. Specify which framework to run using '--framework'.
```
This should fix the failure mentioned in https://github.com/jgm/pandoc/pull/9277#issuecomment-1925604065, and be future proof against more runtime changes upstream because we've now picked a version explicitly (at least until `net8.0` support is dropped).

fix(ci): explicitly choose a .Net version

---

src/Text/Pandoc/Writers/HTML.hs
test/command/8770-block.md
test/command/8770-document.md
test/command/8770-section.md

The HTML5 writer generates an `<aside>` tag grouping all footnotes written to a particular location, and gives it a `#footnotes` ID for ease of navigation.  However, it gives that *same* ID for every `<aside>` if the footnotes occur in multiple locations within the file (`--reference-location=block` or `=section`).  This PR adds a counter to the writer state to track how many footnote-blocks have been written, and uses that to uniquely identify each `<aside>`.
The first ID remains simply `#footnotes` for backwards compatibility with incoming links and for cases where only a single `<aside>` is needed, but all following ones are given a suffix `#footnotes-2`, `#footnotes-3`, and so on (one-indexed to match the individual-note numbering style).  As far as I could tell, none of the other …

Distinguish mutiple HTML5 footnote section ids

---

data/templates/default.latex

`block-headings: true` seems to break unnumbered paragraphs and subparagraphs. This is due to the fact, that the unnumbered version uses the star macros `\paragraph*` and `\subparagraph*`. See issue #6018 for details.

fix block headings support for unnumbered paragraphs

---

data/templates/default.typst
pandoc.cabal
src/Text/Pandoc/Writers/Typst.hs
test/Tests/Old.hs
test/tables.typst
test/tables/nordics.typst
test/tables/planets.typst
test/tables/students.typst
test/writer.typst

- colspans
- rowspans
- cell alignment overrides
- relative column widths
- header and footer
- multiple table bodies with intermediate headers
Row heads are not yet supported.
The default typst template has been modified so that tables don't have lines by default. As is standard with pandoc, we only add a line under a header or over a footer. However, a different default stroke pattern can easily be added in a template.
Closes #9588.

Typst writer: support Typst 0.11 table features.

---

src/Text/Pandoc/Writers/ConTeXt.hs

ConTeXt now depreciates `\sc` in favor of `\setsmallcaps`, closes #9618

ConTeXt writer: replace depreciated `\sc` with `\setsmallcaps`

---

MANUAL.txt

This commit https://github.com/jgm/pandoc/commit/bde3d7622ddd2cda7adabc309335bb2865c1d520 allowed `custom-style` to work with ODT but this is not mentioned in the manual. I tested what happens when the Style is not present and updated the text accordingly. I edited via Github web interface so hard wrapping is approximate. I hope the anchor to the reference doc works as expected (`#option--reference-doc` is the anchor as far as I could determine)...

Update MANUAL.txt to mention custom-style works with ODT

---

src/Text/Pandoc/SelfContained.hs
test/command/9652.md
test/command/9652.svg

Closes https://github.com/jgm/pandoc/issues/9652.

merge 'class' attr when both img and svg specify it

---

MANUAL.txt

Harmonizes the usage of typographic dashes to ~~the most frequently used type: *spaced en dash*~~ *unspaced em dashes*
I systematically checked all occurences (with some simple regex).
cf. https://en.wikipedia.org/wiki/Dash#Parenthetic_and_other_uses_at_the_sentence_level

Harmonize typographic dashes

---

src/Text/Pandoc/Options.hs

When [`--katex`](https://pandoc.org/MANUAL.html#math-rendering-in-html) is specified without a URL, this change makes Pandoc insert CDN URLs[^url1] into the compiled output that always point to the *latest* released KaTeX version. This is in line with the behaviour for `--mathjax`, which falls back to a CDN URL that also points to the latest released MathJax version[^url2].
[^url1]: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js etc.
[^url2]: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js; note that [there would also be versioned URLs available from cdn.jsdelivr.net for MathJax](https://www.mathjax.org/#gettingstarted)

Use latest KaTeX CDN asset

---

src/Text/Pandoc/Readers/RST.hs
test/command/7473.md

Fixes #7473 
This PR implements the following:
1. It seems `figclass`es are currently not being extracted correctly since the wrong key-values are used - this PR extracts them from `keyvals` instead of the key-value output from `imgAttr`
2. `figclass` and `align` annotations are implemented following the [rst docs](https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure): these options apply to the figure while other options are passed onto the underlying image.

RST reader: fix `figclass` and `align` annotations for figures

---

data/templates/default.typst
data/templates/template.typst
test/writer.typst

This PR adds support for `subtitle` in Typst template.

feat: add subtitle to Typst template

---

MANUAL.txt

Current pandoc-lua does support REPL and `-i` as far as I understand.

Update MANUAL.txt to remove false info on Lua mode not supporting -i

---

MANUAL.txt

There is no [!INFO] alert and Pandoc does not trigger the alerts syntax if you try to use it, replace it with [!TIP] which does exist and does work.

Update MANUAL.txt to fix alerts example

---

doc/typst-property-output.md
src/Text/Pandoc/Writers/Typst.hs
test/command/9777-b.md
test/command/9777.md

This is intended to close #9777 in a configurable way.
It also supports a slight generalization of the solution in https://github.com/jgm/pandoc/issues/9574 by enabling control of the `kind` parameter for `#figure()`.
I didn't know how to add classes and attributes to a plain markdown table in a clean way and so I used a Lua filter for that, but of course that can be changed if there's a better way to do it.
EDIT: I see that the test failure comes from CI on windows building Pandoc without Lua support. I'm going to change the tests to provide native input.

typst,table - support '.typst-no-figure' and 'typst-figure-kind=kind'

---

doc/lua-filters.md
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Template.hs
pandoc-lua-engine/test/lua/module/pandoc-template.lua

The function allows to specify a template with the same argument value that would be used with the `--template` command line parameter.
Closes: #9854

Lua: add function `pandoc.template.get`.

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release-candidate.yml

In January 2024, GitHub announced the [deprecation of macOS 11](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal) and the removal of the runner image by June 2024. The macOS 11 runner image will be removed on 6/28/2024.

Update macOS version in GitHub workflows to `macos-12`

---

data/templates/default.latex
src/Text/Pandoc/Writers/LaTeX.hs
test/Tests/Writers/LaTeX.hs
test/command/3450.md
test/command/5476.md
test/command/7181.md
test/command/9045.md
test/writer.latex

Instead of relying on graphicx internals, we now define a macro that gets used with images when explicit size information is not provided. This macro prevents the image from overflowing vertically or horizontally.
Templates will have to be updated to include the new macro.
Closes #9660.
The macro should be credited to @mrpiggi. See https://github.com/mrpiggi/svg/issues/60 for discussion.

New approach to preventing image overflow in LaTeX (fixes #9660)

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release-candidate.yml

There is a [warning message](https://github.com/jgm/pandoc/actions/runs/9641649564) of nightly workflow: `pkg-config 0.29.2_3 is already installed and up-to-date. To reinstall 0.29.2_3, run: brew reinstall pkg-config`.
`pkg-config` has been pre-installed on `macos-12` runner since June, 2023, see https://github.com/actions/runner-images/commit/0a6e640250d4b1406160dabadcf2f832e0ec6393 and https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md.

Remove `pkg-config` installation step in nightly workflow

---

data/templates/default.latex

The default.latex template defines "part title", "section title" and "subsection title" via \setbeamertemplate. But for "section title" and "subsection title", the beamercolorbox also used the "part title" parameter instead of the "(sub)section title". This had the effect that for (sub)section pages the color attributes of the part title were used instead of the ones for (sub)section title.
PS: It's my first pull request, please let me know if I'm doing something wrong or against good practice. I wasn't sure if I should open an issue first (or in addition to the pull request). Since this fix seems quite trivial, I just created the pull request.
Best,
Jonathan

default.latex: wrong beamer color in (sub)section page

---

MANUAL.txt

In "Specifying bibliographic data," update the URL for CSL YAML/JSON HTML-like markup: that section is no longer part of the officia
In section [Specifying bibliographic data] of the _Pandoc User's Guide_ there's a broken link:
> In BibTeX and BibLaTeX databases, pandoc parses LaTeX markup inside fields such as title; in CSL YAML databases, pandoc Markdown; and in CSL JSON databases, an [HTML-like markup]:
The original page/anchor no longer exists, but can still be viewed via Wayback Machine:
<https://web.archive.org/web/20220205142608/https://docs.citationstyles.org/en/1.0/release-notes.html#rich-text-markup-within-fields>
That section referred to a **citeproc-js** specific feature, its documentation has now been moved to the citeproc-js documentation: …

User Guide: Fix CSL Docs broken link

---

INSTALL.md

See #10069 -- the static linked pandoc on other OSes also have a limitation to use binary lua packages. So added this point at the top of the document. In addition conda-forge is cross-platform way to install pandoc and other tools, added to Windows, macOS and Linux sections. I wrapped at 75 characters, is that right?

INSTALL.md — reorganise info on static binaries and add conda-forge install options

---

src/Text/Pandoc/Writers/Docx/Table.hs

This is a suggested fix to support the `custom-style` attribute for docx tables. I'm referring to the issues https://github.com/jgm/pandoc/issues/9603, https://github.com/jgm/pandoc/issues/7549, https://github.com/jgm/pandoc/issues/6496, https://github.com/jgm/pandoc/issues/4697. I needed this feature to support multiple table styles in one document and saw a lot of issues addressing this feature. With absolutely no prior experience in Haskell, I just gave it a shot :) 
The conversion from html to docx with and without it, worked fine. With the `table[custom-style="CustomStyle"]` attribute, it used the CustomStyle for the table and if omitted, the fallback/default style is "Table".
I hope the code is okayish, but happy to change it if needed.

Support custom-style attribute for docx table

---

src/Text/Pandoc/Readers/Docx.hs

When converting DOCX -> Markdown with embedded citations using Zotero Plugin, the standard citation mode was `NormalCitation` (see current version, l. 529). This was not optimal since it meant that one had to manually go through the Markdown and mark suppressed author citations with -. The proposed change forwards the information from `CitationItem.citationItemType` to `citationMode`. I tested it with several DOCX files using Zotero plugin, and it worked for me.
I have the impression that this was a requested feature, see among others here: https://github.com/jgm/pandoc/issues/9116 (the last comments).
Please note that I am a complete Haskell noob, I know other programming languages, but not Haskell. Adjustments and comments are thus very much appreciated.

--docx+citations: Add "SuppressAuthor" and "AuthorOnly" to citationMode

---

src/Text/Pandoc/URI.hs

In order to detect properly `gemini://` links I propose to add it as an unofficial URI scheme.
More info regarding this scheme at [wikipedia](https://en.wikipedia.org/wiki/Gemini_(protocol)) and their [official website](https://geminiprotocol.net/).

Add gemini URI scheme

---

src/Text/Pandoc/Shared.hs

Remove Text.Pandoc.Shared.stripEmptyParagraphs [API change]

---

src/Text/Pandoc/Writers/ANSI.hs
test/ansi-test.ansi
test/ansi-test.txt

The ANSI Superscript writer was copy-pasted and incompletely modified to create the Subscript output writer and I forgot to call the right function, so subscripts were getting rendered with superscripted numbers. Adds a line for this to the ANSI golden test.

Fix copy-pasteo in ANSI writer subscripts

---

src/Text/Pandoc/Readers/DocBook.hs
test/docbook-reader.docbook
test/docbook-reader.native
test/docbook-xref.native

Add parsing of id (xml:id), class, and tabstyle XML attributes for the table and informaltable elements in the DocBook reader. The tabstyle value is put in the 'custom-style' attribute.
fixes #10181

Parse id, class, and tabstyle on tables in DocBook Reader

---

MANUAL.txt

Suggest documentation to preemptively address user issues like #6704

Suggest documentation for syntax highlighting issues on Windows

---

MANUAL.txt

That seems to me to be a typo:
```
${months[, ]}$
${articles:bibentry()[; ]$
```
> To mark variables and control structures in the template,
either `$`...`$` or `${`...`}` may be used as delimiters.
The styles may also be mixed in the same template, but the
opening and closing delimiter must match in each case.

MANUAL.txt: fix typo in template syntax

---

src/Text/Pandoc/Writers/HTML.hs
test/command/10328.md

Divs are unwrapped if the only purpose of the div seems to be to control whether lists are presented incrementally on slides.
Closes: #10328

HTML writer: unwrap incremental divs without other attributes

---

.github/workflows/nightly.yml

The macOS 12 Actions runner image [will be fully unsupported](https://github.com/actions/runner-images/issues/10721) by 12/3/24. This PR addresses this by bumping os version to latest version 15.

GitHub workflow 'nightly': bump Mac OS version

---

src/Text/Pandoc/Readers/JATS.hs
test/command/bits-title-supress.md

For `title` element, JATS defines the attribute [`suppress`](https://jats.nlm.nih.gov/extensions/bits/tag-library/2.0/attribute/suppress.html). In the source code, `suppress` is misspelled (one single `p`only) therefore code will not work as intended. This PR fixes that issue.

JATS: correct suppress attribute

---

src/Text/Pandoc/Writers/ANSI.hs
src/Text/Pandoc/Writers/Markdown.hs
test/ansi-test.ansi
test/ansi-test.txt
test/command/jabberwocky.md

The plain writer behaved as a markdown variant with Ext_line_blocks turned off, and so empty lines in a line block would get eliminated.  This is surprising, since if there's anything where the intent can be preserved in plain text output it's empty lines.
It's still a bit surprising to have nbsps in plain text output, as in the test, where the distinction doesn't really matter, but that'd be an orthogonal change.
As presented here the change ignores whether the `line_blocks` extension is enabled. As a write-only format, I'm not sure whether it makes sense for the `plain` writer to behave differently in the presence or absence of this extension.
Ditto ANSI writer.

Respect empty LineBlock lines in plain and ansi writers

---

src/Text/Pandoc/Format.hs

If .typ is typst, but .typ is also typst, which one wins?

Text.Pandoc.Format: remove duplicate typst entry

---

src/Text/Pandoc/ImageSize.hs
src/Text/Pandoc/Writers/Docx/OpenXML.hs
src/Text/Pandoc/Writers/Powerpoint/Output.hs

My code feels a bit messy and I've tested it with like precisely one WebP image per variant (lossy, lossless, and extended). I found myself having/wanting to combine attoparsec (to get `Alternative` and backtracking) and Data.Binary.Get (to get numbers); maybe there's a less awkward looking way to do this.
This is an API change because the constructors of ImageType are public.
Closes #9561

Add WebP support to ImageSize

---

src/Text/Pandoc/Writers/TEI.hs

Copy-pastes left behind since introduction in 2015

Fix comments in TEI writer referring to DocBook

---

data/templates/common.latex
data/templates/default.beamer
data/templates/default.latex

The \nocite command will now be in the document body.
This works with both bibtex and biblatex.
Closes https://github.com/jgm/pandoc/issues/10461

Move nocite

---

data/templates/default.openxml
src/Text/Pandoc/Writers/Docx/OpenXML.hs

This change affects the default openxml template as well as the OpenXML writer.
Closes #10282 (regression introduced in pandoc 3.5).

Docx writer: use styleIds not styleNames for Title, Subtitle, etc.

---

src/Text/Pandoc/Readers/Textile.hs
test/command/9878.md

The span needs to be separated from its surroundings by spaces. Also, a span can have attributes, which we now attach.
Closes #9878.

Textile reader: improve parsing of spans.

---

src/Text/Pandoc/Parsing/General.hs

The given example wasn't actually functional because `anyChar` parses a `Char` and `charsInBalanced` wants a `Text` parser as its inner parser.

Correct example in charsInBalanced

---

src/Text/Pandoc/Readers/RST.hs
test/command/10484.md

This case was missed when changing the reference link strategy for RST to allow a single pass.
Fixes #10484

RST reader: handle explicit reference links

---

src/Text/Pandoc/Error.hs

I noticed that asciidoct is not supported as input format, so in this case its
better to be clear about what the failure is about.
```
fursixnine@pakhet cndk8 % pandoc -t markdown  ./CNDK8.adoc $OUTPUT.md
Unknown input format asciidoc
```
This should improve the error being presented to the user.

Improve message for asciidoc input error #8416

---

MANUAL.txt
pandoc.cabal
src/Text/Pandoc/Format.hs
src/Text/Pandoc/Readers.hs
src/Text/Pandoc/Readers/Pod.hs
test/Tests/Old.hs
test/Tests/Readers/Pod.hs
test/pod-reader.native
test/pod-reader.pod
test/test-pandoc.hs

Pod ("Plain old documentation") is a markup languaged used principally to document Perl modules and programs. Since it was originally meant to be translated pretty directly to man, the semantics are fairly simple.
This Pod reader was developed with reference to the canonical user and implementer documentation of Pod: https://perldoc.perl.org/perlpod and https://perldoc.perl.org/perlpodspec.
There are 1490 .pod, .pl, and .pm in the Perl 5.34 distribution found in /System/Library/Perl on my mac. Of those, this reader dies with a parse error on 7 of them. All of them seem to be cases where pod commands are found within a non-colon-prefixed =begin/=end. perlpodspec says I may treat this as an error.

Add Pod reader

---

src/Text/Pandoc/Readers/Mdoc/Standards.hs

Following mandoc:
https://cvsweb.bsd.lv/mandoc/st.c?rev=1.19&content-type=text/x-cvsweb-markup

Add mdoc St for C23

---

MANUAL.txt

... so it links to the latest major release rather than a specific major release (which there are two of every year)

replace LibreOffice PDF documentation link to latest

---

data/templates/styles.html
test/writer.html4
test/writer.html5

Hi all,
I propose to change the way horizontal rules are styled in HTML exports from applying a `background-color` to using `border-top`. This change does not affect how they are displayed; so all exports will still look like before.
However, this way, horizontal rules will be printed out if someone decides to save a document exported to HTML to PDF or print it.
I just had a user mentioning that, if you use a horizontal rule in a document, export it to HTML and then print it, the horizontal rule doesn't show up (see https://github.com/Zettlr/Zettlr/issues/5562). After some fiddling around, I found that in the styles section, Pandoc applies a background instead of a border color. By default, every browser will not print backgrounds to save toner/ink, which applies even if someone wants to …

fix: default HR styling from `background-color` to `border-top`

---

src/Text/Pandoc/Readers/Pod.hs
test/command/10537.md
test/pod-reader.native

I neglected to properly consume empty lines after =encoding commands, which produced various incorrect parses depending on the content between there and the next command. If I had actually looked closely at the golden test I originally generated I might have noticed the problem!
Fixes #10537

Consume blanks after =encoding in pod reader

---

src/Text/Pandoc/MediaBag.hs
test/Tests/MediaBag.hs

Currently, remote images added to the MediaBag are stored at paths with extensions determined based on the external URI. For instance, an image from https://example.com/image.png is stored as <hash>.png. If the URI does not contain an extension (e.g., https://example.com/image), then the content-type of the downloaded image is used to determine the extension.
This change switches the precedence such that content-type is preferred over extensions contained in the URI. This is necessary because some images are located at URIs with misleading extensions -- shields.io, for instance, serves SVGs from URIs with .yml extensions. With this change, the image/svg+xml content-type is now preferred over the .yml URI extension. This fixes a bug in the PDF writer in which such an image would be …

Prefer MIME type when determining extensions for MediaBag items

---

test/command/4470.md

Closes #4470
(Or you could just close that and this if you think LaTeX reader macro expansion is adequately tested elsewhere, I didn't scrutinize the other existing tests that thoroughly.)

Test \{,re}newcommand arguments

---

doc/lua-filters.md

Add a paragraph to the pandoc Lua filter documentation (in the [debugging](https://pandoc.org/lua-filters.html#debugging-lua-filters) section) mentioning static analysis via [`luacheck`](https://github.com/mpeterv/luacheck), and a link to [pandoc-luacheckrc](https://github.com/rnwst/pandoc-luacheckrc).

doc/lua-filters.md: Add static analysis paragraph to debugging section

---

src/Text/Pandoc/Readers/Docx.hs
test/Tests/Readers/Docx.hs

This fixes #10571 by also allowing `Div` as a block element

DOCX reader: do not issue warning for comments with ext. `+styles`

---

doc/lua-filters.md

See #10568. I used the wrong luacheck URL in my earlier PR. Sorry about that!

Correct luacheck URL in doc/lua-filters.md

---

MANUAL.txt

Note the Docx support for top-level-division added in <https://github.com/sthagen/jgm-pandoc/commit/b6aff2145231a7284b47b030c08a6410fb114ec1> in the manual.

Document top-level-division functionality with Docx

---

data/docx/word/document.xml
data/docx/word/footnotes.xml

The line breaks are interpreted as whitespace, resulting in extra leading and trailing spaces in the reference file.

Remove extra spaces in default reference docx

---

src/Text/Pandoc/Readers/DocBook.hs

Include id attribute.
The code should be credited to @tombolano.
Closes #8664.

DocBook reader: better handle informalequation

---

AUTHORS.md
data/templates/article.jats_publishing
doc/jats.md
src/Text/Pandoc/Writers/JATS.hs
test/command/10152.md

Closes #10152
Enable annotating author roles using the [Contribution Role Taxonomy (CRediT)](https://credit.niso.org/contributor-roles) and export this information in conformant JATS (#10153, Charles Tapley Hoyt and Jez Cope).
I'm motivated to add this to Pandoc since I want the Journal of Open Source Software (JOSS), which is built on top of Pandoc, to be able to create compliant JATS. We're already adding support for encoding this information in article metadata in parallel in https://github.com/openjournals/inara/pull/87.
Now, you can specify an authors' role(s) in the metadata like this:
```yaml
title: CRediT Test
author:
- name: Max Mustermann
roles:
- credit: software
credit-name: Software    # optional, looked up automatically
degree: Lead             # optional
name: Programas …
```

Add CRediT roles to JATS

---

cabal.project
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Readers/MediaWiki.hs
src/Text/Pandoc/Readers/Vimwiki.hs
src/Text/Pandoc/Writers/Markdown/Inline.hs
stack.yaml
test/Tests/Readers/Markdown.hs
test/command/2649.md
test/command/8853.md
test/command/wikilinks_title_after_pipe.md
test/command/wikilinks_title_before_pipe.md
test/mediawiki-reader.native
test/vimwiki-reader.native

Once upon a time the only metadata element for links in Pandoc's AST was a title, and it was hijacked to track certain links as having originated in the wikilink syntax. Now we have Attrs and we can use a class to handle wikilinks instead.
Requires coordinated changes to commonmark-hs: https://github.com/jgm/commonmark-hs/pull/160

Track wikilinks with a class instead of a title

---

.github/workflows/ci.yml

This adds a new element to the `ci.yml` configuration to include the newer version of `ghc` in testing. Possibly related to #10597

Add testing on ghc v9.12

---

MANUAL.txt
data/templates/common.latex
data/templates/default.latex
src/Text/Pandoc/Writers/LaTeX.hs
test/command/9472.md
test/writers-lang-and-dir.latex

Closes #8283.
- Add babel languages to global options.
- Remove languages in `\usepackage{babel}`.
- Remove `\babelprovide` commands.
- Add `babeloptions` variable.
The LaTeX writer will give a default `babeloptions` that makes sense given the main language. If the main language is not well supported in "traditional" babel (i.e., via an .ldx file) then `provide=*` will be added to the babel package options, which will load the .ini file.
This should give better results for the mostly European languages that are supported by .ldx files, while working about the same as current pandoc for other languages.
Untested and perhaps not working without manually setting `babeloptions`: main language English, secondary language Arabic.
Credit to @mxpiotrowski for the template changes.

LaTeX template: babel changes.

---

MANUAL.txt
pandoc-cli/man/pandoc.1

As metadata suggests 3 possible values I correct a 'doublon': "just a title, a title and an author" to take 'a date' in account.
This avoids repetition.

MANUAL: correct missing 'date' as possible block entry in metadata

---

data/templates/default.beamer

This allows one, for example, to set a custom \date in the header-includes of the rmarkdown yaml frontmatter. Without this conditional, the custom \date in the frontmatter would be overridden by a (potentially empty) date from this template later.

data/templates/default.beamer: only emit \date if set

---

src/Text/Pandoc/Writers/LaTeX/Util.hs

https://tex.stackexchange.com/questions/228973/argument-of-captionydblarg-has-an-extra

Latex: allow phantomsection in captions

---

src/Text/Pandoc/Readers/LaTeX/Table.hs
test/command/7512.md

In LaTeX's tabular environment, the tabular newline takes an optional argument that we skip. But it only takes a single optional argument, and any further square-bracketed text that follows shouldn't be skipped.
Fixes #7512, specifically [the followup issue](https://github.com/jgm/pandoc/issues/7512#issuecomment-905245320) identified by @fedeinthemix, and also adds a test for the original problem raised in that issue which was already fixed at some point.

Skip at most one argument to LaTeX tabular newline

---

src/Text/Pandoc/MIME.hs

AVIF is an image file extension. Image was previously written incorrectly as impage. This commit corrects that error.

Typo: impage should be image

---

src/Text/Pandoc/Readers/Org/Shared.hs

AVIF is an image extension. This commit enables the Org reader to recognise AVIF files as images to be displayed, and not simply as links.
I'm unsure whether this pull request should be merged though, as currently the default Emacs (and hence org-mode) image file name extensions are `("png" "jpeg" "jpg" "gif" "tiff" "tif" "xbm" "xpm" "pbm" "pgm" "ppm" "pnm" "svg" "webp")` and do not include `avif`. However, AVIF is already recognised by pandoc in `MIME.hs` so it seems remiss to not let the Org reader recognise AVIF as an image.

Add AVIF to Org Reader image extensions

---

src/Text/Pandoc/Writers/Markdown.hs
test/command/10812.md

Allows using `-t plain+four_space_rule` to emulate the output of pandoc before #7172. This is useful for users that use pandoc e.g. to autoformat commit messages.
Fixes #10812.

Plain writer: Support the four_space_rule extension.

---

doc/typst-property-output.md

Mention in the docs that `typst:no-table` is a class, not an attribute.
Resolves #10815

Fix docs for typst:no-figure class

---

doc/lua-filters.md
pandoc-lua-engine/src/Text/Pandoc/Lua/Module/Pandoc.hs
pandoc-lua-engine/test/lua/module/pandoc.lua
src/Text/Pandoc/Class/Sandbox.hs

The `pandoc.read` function now allows to populate the ersatz file system of the sandbox via the (optional) fourth parameter. The given value must be a table that lists the files which will be read from the file system before entering the sandbox. It's also possible to use a mapping from filenames to contents in the table.

Lua: allow to fill the ersatz file system of the read sandbox

---

src/Text/Pandoc/Writers/Typst.hs

This is the name expected by the default template. This should fix the `--number-sections`/`-N` option when used with Typst.

Typst writer: rename *numbering* variable to *section-numbering*.

---

doc/lua-filters.md

This PR adds a code example of how to use the pandoc.Table constructor in a Lua filter and a few notes on the `colspec` and `bodies` parameters. These changes were made under the pandoc.Table constructor section of the documentation. I think that this will help provide enough information for someone to use this constructor without prior knowledge. This may be relevant to [#6569](https://github.com/jgm/pandoc/issues/6569) and [#6571](https://github.com/jgm/pandoc/issues/6571).

Add example in documentation on using pandoc.Table constructor.

---

src/Text/Pandoc/Readers/Pod.hs
test/Tests/Readers/Pod.hs

Translating entities by name ultimately relies on
Commonmark.Entity.lookupEntity, which de facto requires the entity name to be followed by a semicolon. Paste a semicolon onto the end of the entity name read from POD to look it up.
Fixes #11015
It's noteworthy that `lookupEntity`, when called with a numeric entity, is _indifferent_ to the presence of a trailing semicolon in the query, whereas for named entities it depends entirely on the weirdness of the table in the HTML spec. This isn't documented by `lookupEntity` either way.
```
ghci> lookupEntity (T.pack "#8482")
Just "\8482"
ghci> lookupEntity (T.pack "#8482;")
Just "\8482"
ghci> lookupEntity (T.pack "trade")
Nothing
ghci> lookupEntity (T.pack "#8482;")
Just "\8482"
ghci> lookupEntity (T.pack "aacute")
Just "\225"
ghci> lookupEntity …
```

Fix named entity lookup in POD reader

---

src/Text/Pandoc/Readers/LaTeX/Inline.hs
src/Text/Pandoc/Writers/LaTeX/Util.hs

The `\-` command is parsed as a soft hyphen character; likewise, the character is written as that command when outputting LaTeX.

LaTeX reader and writer: add support for soft hypens

---

MANUAL.txt
data/templates/default.latex
src/Text/Pandoc/Writers/LaTeX.hs

The `SOURCE_DATE_EPOCH` environment variable is used to trigger reproducible PDF compilation, i.e., PDFs that are identical down to the byte level for repeated runs.
Closes: #6539

LaTeX writer: set `pdf-trailer-id` if `SOURCE_DATE_EPOCH` envvar is set

---

src/Text/Pandoc/App/CommandLineOptions.hs
src/Text/Pandoc/Options.hs

When using WebTeX in a defaults file without giving a URL, it doesn't use the default URL <https://latex.codecogs.com/png.latex?> given in the documentation. I think it is because in Options.hs, the URL defaults to a blank string instead. This PR replaces the blank string with the default URL <https://latex.codecogs.com/png.latex?>.
https://github.com/jgm/pandoc/blob/7639e800c5af85e5ded862a6e218d54489d17bfc/src/Text/Pandoc/Options.hs#L117
https://github.com/jgm/pandoc/blob/7639e800c5af85e5ded862a6e218d54489d17bfc/src/Text/Pandoc/App/CommandLineOptions.hs#L1023-L1029

Add default WebTeX URL to Options.hs [API change]

---

src/Text/Pandoc/Readers/LaTeX.hs
test/command/10635.md

LaTeX reader: parse `\minisec` as unlisted level 6 headings.

---

src/Text/Pandoc/Writers/Docx.hs
src/Text/Pandoc/Writers/Docx/OpenXML.hs

Any leading section separator is removed from the result.
Closes: #10578

Docx writer: ensure that documents don't start with a section separator

---

MANUAL.txt
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Writers/LaTeX.hs
test/Tests/Readers/Markdown.hs
test/Tests/Writers/LaTeX.hs

This PR resolves #10369 by using the `latex-pos` attribute of a figure to set its [positioning](https://www.overleaf.com/learn/latex/Positioning_images_and_tables#The_figure_environment) in LaTeX output. Additionally, the MD reader removes this attribute from the image in a figure and passes it to the figure itself. Originally, only the image's identifier is passed to the figure while all the other attributes are kept with the image.
I think that the LaTeX reader should store a figure's positioning as well, but I am not sure how to edit the reader to do this.

Add figure placement for MD to LaTeX

---

src/Text/Pandoc/Parsing/GridTable.hs
src/Text/Pandoc/Readers/Markdown.hs
src/Text/Pandoc/Readers/RST.hs
test/command/10338-rst-multiple-header-rows.md

This adds support for multiple header rows into tables.
In order to accomplish this, the shared `GridTable` module was to extended to also be able to handle tables with multiple header rows.
Also adjusted the `simpleTableRow` function to prevent headless tables from being interpreted as multiple header rows and fixed hlint warnings about redundant `$`.
Fixes #10338

RST Reader: Add multiple header rows

---

src/Text/Pandoc/Class/IO.hs

HTTP requests that don't return a 200 error code are now treated as an
error. This ensures that a warning is triggered when using
`--embed-resources` or `--extract-media`.

PandocMonad: Let fetching fail if the HTTP request is not successful.

---

src/Text/Pandoc/Readers/Typst.hs
test/command/11101.md

add support for reading typst pagebreak

---

src/Text/Pandoc/Writers/RST.hs
test/command/10127.md

Together with the reader part from https://github.com/jgm/pandoc/pull/11115 this writer part fixes #10127

RST writer: Add col spans for simple tables

---

MANUAL.txt

In documenting LaTeX packages used by generated documents, don’t mention
some packages twice in one (already long) paragraph.
This addresses part of #11178.

MANUAL.txt: remove some redundancy

---

src/Text/Pandoc/Writers/LaTeX.hs
test/command/9366.md

As in #1294 `\url` and `\href` need to be protected inside an mbox for soul commands.
Fixes: #9366

LaTeX writer: Fix strikeout in links
